### ISSUE TITLE
Can't put Global Search in panel anymore

### ISSUE THREAD

**Issue by johanlef** [microsoft/vscode#100559]
- VSCode Version:
```YML
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (1 day ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```
- OS Version: OS X 10.14.6

Steps to Reproduce:

1. I had configured to put the global search to appear in the panel (right or bottom) instead of the side bar (left)
2. Since the update 1.46, it appears in my left side bar instead of the panel and I can't find the settings anymore to put it back in the panel

Does this issue occur when all extensions are disabled?: **Yes**/~~No~~
