### ISSUE TITLE
[less] support rule set mixins

### ISSUE THREAD

**Issue by dogancelik** [Microsoft/vscode#10258]
- VSCode Version: 1.4.0
- OS Version: Windows 8

The code below compiles with no errors or warnings in Less compiler.
So VSCode should not show **error**.

```less
@min-container: {
  min-height: 600px;
};

#doc-container {
  margin-top: 70px;
  @min-container();
}
```

![1](https://cloud.githubusercontent.com/assets/486818/17460111/7417bd3a-5c60-11e6-9c18-ac1207dbbd25.png)
![2](https://cloud.githubusercontent.com/assets/486818/17460112/7418c57c-5c60-11e6-8987-f65d2f7da2e1.png)
![3](https://cloud.githubusercontent.com/assets/486818/17460113/74191676-5c60-11e6-900c-a340ce864231.png)

Output (no errors, no warnings):

```css
#doc-container {
  margin-top: 70px;
  min-height: 600px;
}
```
