### ISSUE TITLE
Snippet variable `$LINE_COMMENT` is incorrect when inside CSS

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#102611]
- VSCode Version: latest
- OS Version: macOS latest

Steps to Reproduce:

1. Create a snippet with config
   ```json
   {
     "TODO": {
       "prefix": "todo",
       "body": "$LINE_COMMENT TODO: "
     }
   }
   ```
2. Inside CSS, run the snippet (place cursor after `todo`, open suggestions, then execute)
   ```css
   .foo {
        todo
        color: grey;
    }
   ```

Actual:

```css
.foo {
     TODO: 
    color: grey;
}
```

Expected:

```css
.foo {
    /* TODO:  */
    color: grey;
}
```

This is how the "add line comment" works, so I would expect the snippet variable to behave similarly.

Does this issue occur when all extensions are disabled?: Yes

Related: https://github.com/microsoft/vscode/issues/102609
