### ISSUE TITLE
Loading external resources in VSCode Extension Webview fails due to CORS Policy

### ISSUE THREAD

**Issue by ahmed-shehata** [microsoft/vscode#102959]
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z (4 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

## Tested with insiders as well:
Version: 1.48.0-insider
Commit: 6c21258b65e4c9448323c930fabb1ac6b734c597
Date: 2020-07-20T05:27:28.503Z (9 hrs ago)
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.5.0

## Issue
It seems like [this change](https://github.com/microsoft/vscode/pull/97777) broke loading external `vscode-resource`s.
A similar issue: https://github.com/microsoft/vscode/issues/99190

Steps to Reproduce:

Loading external resources (ttf font for example), produces the following error in Webview console

```
index.html:1 Access to font at 'vscode-webview-resource://users/test/extension/out/fonts/font.ttf' from origin 'vscode-webview://7803497a-8232-4556-988a-7a1636d48b30' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
font.ttf:1 Failed to load resource: net::ERR_FAILED
```

This used to work fine in previous versions.

I have updated the webview HTML to support the new "vscode-webview-resource" as follows

```

      <meta http-equiv="Content-Security-Policy"
            content="default-src 'none';
                    font-src * data: blob: 'unsafe-inline' vscode-webview-resource:;
                   ">
```

Fonts are getting loaded in `<style>` tag as such:

![image](https://user-images.githubusercontent.com/4982099/87953460-f9a3dd80-caa2-11ea-9c3e-8219245b7269.png)

Related issue: https://github.com/microsoft/vscode/pull/97777

Does this issue occur when all extensions are disabled?: Yes

cc: @mjbvz

**Comment by mjbvz** [comment]
Can you please share some example extension code that demonstrates the issue

**Comment by ahmed-shehata** [comment]
I have done some digging and cornered down the issue to the following change:

it seems that `asWebviewUri` API has changed something with regard to the path, specifically adding a `file///` in the path.

### Before:

![Screenshot 2020-07-23 at 4 10 17 pm](https://user-images.githubusercontent.com/4982099/88304744-8e574700-cd00-11ea-9697-e17b13743d69.jpg)

### After:
![Screenshot 2020-07-23 at 4 10 32 pm](https://user-images.githubusercontent.com/4982099/88304754-91eace00-cd00-11ea-8399-3a624ab6ca83.jpg)


Since we are relying on [path](https://nodejs.org/api/path.html) to join the webview uri to the resource path, this `file///` gets [normalized](https://nodejs.org/api/path.html#path_path_normalize_path) to `file/`, which is a broken uri to VSCode resource management.

The solution/workaround is to pass the full joined path to `vscode.Uri.file(...)`before calling `asWebviewUri` on the path.

I'm not sure if this is an intended change or a bug, feel free to close it if it is intended.

**Comment by mjbvz** [comment]
Yes sounds like it may be a bug in the extension code. Can you share the code that generates the font's uri?

**Comment by ahmed-shehata** [comment]
### Old way (worked before 1.47.2):

#### JS:
```js
const fontPath = path.join(extensionPath, "out", "fonts", "font.ttf");
```
#### CSS:
```css
@font-face {
        font-family: 'Font Name';
        font-style: normal;
        font-weight: normal;
        src:
          url(vscode-resource:${fontPath}) format('truetype');
      }
```
### Fixed way:

#### JS
```js
const fontPath = panel.webview.asWebviewUri(vscode.Uri.file(
    path.join(extensionPath, "out", "fonts", "font.ttf")
  ));
```
#### CSS
```css
 @font-face {
                      font-family: 'Font Name';
                      font-style: normal;
                      font-weight: normal;
                      src:
                        url('${fontPath}') format('truetype');
                    }
```
