### ISSUE TITLE
Debug panel syntax highlights does not match user specified color theme

### ISSUE THREAD

**Issue by rekaerst** [microsoft/vscode#104741]
- VSCode Version:1.48.0
- OS Version:Windows_NT x64 10.0.19041

Syntax highlighting in debug panel honors neither current color theme nor editor.tokenColorCustomizations->textMateRules, they just match the default dark+ theme.
Their  color can be changed by modifying css, but this method is not convenient and updates may break them;
```css
.monaco-workbench .monaco-list-row .expression .value.string, .monaco-workbench .debug-hover-widget .value.string {
    color: #ce9178;
}
```

![image](https://user-images.githubusercontent.com/52642831/90327338-5e305a80-dfc5-11ea-9071-29fac46b264e.png)

Does this issue occur when all extensions are disabled?: Yes expecting user color theme
