### ISSUE TITLE
"Move line down" messes up indentation of existing YAML lines

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#105439]
In this YAML, I've put `three:` in the wrong place - I wanted it to be a child of the `two` under `one2`. To fix it, I would expect to put the cursor on the line `three: four` and execute "Move Line Down" (`option`+`down`) 4 times.

```yaml
one:
  two:
    three: four # Move this line to be a child of line 7
  two2:

one2:
  two:
  two2:
```

It should end up like this:

```yaml
one:
  two:
  two2:

one2:
  two:
    three: four # Move this line to be a child of line 7
  two2:
```

However what actually happens is this:

```yaml
one:
  two:
    two2:
      
      one2:
        two:
          three: four # Move this line to be a child of line 7
  two2:
```

![Aug-26-2020 17-11-49](https://user-images.githubusercontent.com/1078012/91328797-46c05100-e7bf-11ea-8156-e9ad96193c50.gif)
