### ISSUE TITLE
Autohide Minimap

### ISSUE THREAD

**Issue by cbarrick** [microsoft/vscode#107116]
# Motivation

There are already a few feature requests to autohide the minimap:

- #28310
- #81550

These requests are somewhat awkward, but there is a common sentiment: These users like the minimap in some cases, but it gets in the way in others.

# Proposal

***Autohide the minimap. Show on scroll and hover.***

I think this is better than the previous proposals:

- Autohide is a familiar UI pattern.
- It should be easier to implement and maintain.
- It mostly solves the use cases described in the previous proposals. 

# Proof of Concept

First define the animation in CSS, and fixup the current-line highlight:

```css
/* 0.5s fade in/out for the minimap */
.minimap {
    opacity: 0.0;
    transition: opacity 0.5s;
}
.minimap:hover, .minimap:focus, .minimap.scrolling {
    opacity: 1.0;
}

/* Fix the current-line highlight to be full-width */
.view-overlays {
    width: 100% !important;
}
.current-line {
    width: 100% !important;
}
```

Since there is no way to detect scrolling in CSS, we also need some custom code:

```javascript
/** Autohide the Minimap.
 * 
 * @param {Node} editor The DOM node of the Monaco editor.
 */
function autohideMinimap(editor) {
    let isScrolling = false;
    let timeoutId = null;

    editor.addEventListener('wheel', (event) => {
        // Throttle to 10Hz.
        if (isScrolling) {
            return;
        } else {
            isScrolling = true;
            setTimeout(() => { isScrolling = false; }, 100);
        }

        // Add the `.scrolling` class to the minimap.
        // Remove it 2s after scrolling stops.
        let minimap = editor.querySelector('.minimap');
        minimap.classList.add('scrolling');
        clearTimeout(timeoutId);
        timeoutId = setTimeout(() => {
            minimap.classList.remove('scrolling');
        }, 2000);
    })
}
```

This function must be called every time a new editor is created, e.g. when switching tabs.

I am not familiar with the vscode internals. I hacked this up by playing in the dev tools, but I'm sure there's a better way to do it with the Monaco API.
