### ISSUE TITLE
[yaml] highlighting issue of single quotes in a value

### ISSUE THREAD

**Issue by JacobGunther12** [Microsoft/vscode#10746]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

When you put a ' symbol in a YML file variables, it will syntax color everything until it reaches another '. Usually this isn't an issue while doing double (''), but the game Minecraft recognizes the single ' as a ' and you don't have to put double '.

Steps to Reproduce:
1. Open a .YML file
2. Make a variable and include a ' in the value (examplevalue: This is an example's value)

**Comment by aeschli** [comment]
@JacobGunther12 Can you add an example?
I tried this
```yaml
# An employee record
martin:
    name: Martin D'vloper
    job: Developer
    skill: Elite
```
and it seems to colorize fine
