### ISSUE TITLE
Unbound breakpoint for Node.js app running in a Docker container

### ISSUE THREAD

**Issue by ShocKwav3** [microsoft/vscode#108418]
I have been having very very hard time to setup VSCode debugger for a project in a docker container(locally) ran using babel-node. The debugger attaches fine but whenever I set a breakpoint, it goes grey holo circle and says "Unbound breakpoint". One thing to mention is, if I start the server with `--inspect-brk` then, the server does wait on first line and when I connect the debugger, I can step through!

I understand that this might be a source mapping issue but I have setup the necessary configs for that and the issue still persists. I have setup a minimal project in a repository(links below) for this.

I have looked through the web trying different configs, reading VSCode documentations and explored issues on this repository but nothing came any close to fix this. I have also tried the old debugger and I still get same issue. I would highly appreciate if someone could take a kind look on this.

### Here are the relevant configurations:
**Dockerfile:**
```FROM node:12
WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn install
COPY . .
```
**Docker compose**
```
version: '3'
services:
  server:
    image: babel-node-test-image
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - servernet
    command: ["yarn", "start"]
    tty: true
networks:
  servernet:
```

**.babelrc:**

```
{
    "presets": [
        "@babel/preset-env"
    ],
    "sourceMaps": "inline",
    "retainLines": true
}

```

**launch.json:**

```
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Debug docker app",
            "port": 9229,
            "restart": true,
            "trace": true,
            "address": "localhost",
            "localRoot": "${workspaceFolder}/src",
            "remoteRoot": "/usr/src/app/src",
            "protocol": "inspector",
            "sourceMaps": true,
            "smartStep": true
          }
    ]
}
```

**Command to start the server:** `nodemon --exec babel-node --inspect=0.0.0.0 src/app.js`

- VSCode Version: Latest
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Add the above configurations
2. Attach and try to set breakpoint

Does this issue occur when all extensions are disabled?: Yes
