### ISSUE TITLE
Color preview won't work with whitespace syntax

### ISSUE THREAD

**Issue by guilhermetod** [microsoft/vscode#108681]
Hey, I apologize in advance if this is a duplicate but I really couldn't find a issue reporting this. Currenly, the color preview doesn't seem to support hsl and rgb color without the comma syntax, even though browser do.

- VSCode Version: 1.50.0
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Paste the following in VS Code. Only "background-color" syntax show the color preview: 

```css
.my-class {
  background-color: rgb(12, 122, 231, 50%);
  color: rgb(12 122 231 / 50%);
}
```

![image](https://user-images.githubusercontent.com/53096593/96035217-18630780-0e39-11eb-9ff4-9a54978ac515.png)

2. Paste the same in a browser, verify both syntax are valid.

Does this issue occur when all extensions are disabled?: Yes
