### ISSUE TITLE
"F5" run the wrong "preLaunchTask", if preLaunchTask is a default custom task name

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode#109939]
- VSCode Version: 1.51.0-insider
- OS Version: Win64

This issue comes up when VsCode has to run the `preLaunchTask` mentioned in the launch.json, before launching the debugger.

1. Define a custom task e.g. `CustomTask` for .cpp files.
3. From the command pallet choose `Task: configure task` and generate a custom task. A custom task with _default task name_  and _default configurations_ will be created like below:
![image](https://user-images.githubusercontent.com/16143955/98045861-fcbaa380-1ddd-11eb-9261-024e0bb6d5a5.png)

2. Open a launch.json file and define a launch task as below. Set the `preLaunchTask` to the task that was generated in the previous step:
![image](https://user-images.githubusercontent.com/16143955/98044855-66d24900-1ddc-11eb-9e74-79cc316321cc.png)

3. press F5, the default task will run as the  `preLaunchTask` with default configurations as expected.

4. Now modify the task in tasks.json file (don't change the default name though), and don't change the launch.json either.

3. press F5, again the default task will run as the  `preLaunchTask` with default configurations, and the new changes won't take into consideration. 

This issue happens only when the default task name is being used (that's why I think this is a VsCode issue, not an extension issue). If the name of the task is modified, the changes will be taken into consideration.

My guess is that when choosing the `preLaunchTask` from a set of custom-defined tasks, Vs Code gives priority to `detected tasks` instead of `existing tasks` from tasks.json. for example, if there is a `detected task` with the default name, and there is an `existing task` which also uses the default name, `preLaunchTask` should choose the existing one, rather than the detected one.  This issue also doesn't exist with non-custom tasks like shell.

@sean-mcmanus @alexr00

**Comment by sean-mcmanus** [comment]
I don't think this is a duplicate.

**Comment by 8549** [comment]
Thank you for the issue, i thought i was crazy after spending the entire morning tracking down an error in my launch/tasks configuration. I can confirm that a customized task with a default name doesn't get picked up by VS Code.

tasks,json:
```yaml
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "cppbuild",
      "label": "C/C++: gcc build active file",
      "command": "/usr/bin/gcc",
      "args": [
        "-g",
        "${file}",
        "-Wall",
        "-O0",
        "-lm",
        "-o",
        "${fileDirname}/${fileBasenameNoExtension}"
      ],
      "options": {
        "cwd": "/usr/bin"
      },
      "problemMatcher": [
        "$gcc"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "detail": "compiler: /usr/bin/gcc"
    }
  ]
}
```

launch.json:
```yaml
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "gcc - Build and debug active file",
      "type": "cppdbg",
      "request": "launch",
      "program": "${fileDirname}/${fileBasenameNoExtension}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ],
      "preLaunchTask": "${defaultBuildTask}",
      "miDebuggerPath": "/usr/bin/gdb"
    }
  ]
}
```

ouput:
```shell
> Executing task: C/C++: gcc build active file <

Starting build...
Build finished with error:

/usr/bin/ld: /tmp/ccvgnwl2.o: in function `modulus':
/home/[redacted]/infoA/lab6/2.c:24: undefined reference to `pow'
/usr/bin/ld: /home/[redacted]/infoA/lab6/2.c:24: undefined reference to `pow'
/usr/bin/ld: /home/[redacted]/infoA/lab6/2.c:24: undefined reference to `sqrt'
collect2: error: ld returned 1 exit status

The terminal process failed to launch (exit code: -1).

Terminal will be reused by tasks, press any key to close it.
```
If i manually run the default build task and then debug the executable it all works correctly.
