### ISSUE TITLE
Ubuntu `lxc profile show default > default.yml'` on zsh fails to redirect

### ISSUE THREAD

**Issue by pjgoodall** [microsoft/vscode#110281]
Issue Type: <b>Bug</b>

From settings select shell `/bin/zsh` or `/usr/bin/zsh`

then if in the vscode terminal, I redirect output of lxc profile I get an empty file. This is true for the snap installs of both `code` and `code-insiders`
```
% lxc profile show default > t1.yml
% wc t1.yml
0 0 0 t1.yml
```

If I do this same operation in a normal ubuntu 20.04 terminal I get the expected result:

```
% lxc profile show default > t1.yml
% wc t1.yml
 14  26 209 t1.yml
```
This file has the expected output.
```
% cat t1.yml                  
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/instances/fossa

```
whereas a simple redirect seems to work in the vscode terminal:

```
% ls > ls.txt                      
[0] % wc ls.txt                 
  28   28 1151 ls.txt
```

I reported this on the container users forum too - 
https://discuss.linuxcontainers.org/t/lxc-redirecting-profile-into-text-file-fails-identified-as-vscode-terminal-problem/9435

VS Code version: Code - Insiders 1.52.0-insider (24b28f57be22fe3029cb17a1dd72d8d9c2d6468b, 2020-11-06T05:40:12.937Z)
OS version: Linux x64 5.4.0-52-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1245 v3 @ 3.40GHz (8 x 3508)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|15.42GB (0.23GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 446f8467-2185-4e65-b6f3-71361ea528a8|
|Screen Reader|no|
|VM|50%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by Tyriar** [comment]
Does this work for you when using the deb package? It might be an issue with the snap sandbox.

**Comment by pjgoodall** [comment]
@Tyriar  The default way of installing lxc is by snap. It is likely that there will be no other way soon. 

I am building some test configs so I can try installing vs-code from deb. I will report back soon.

**Comment by pjgoodall** [comment]
It looks like the problem is something related to the packaging of Visual Studio Code as a snap.

My tests will be 
(lxc + bash)
(lxc + (vs-code from snap /shell=bash))
(lxc + (vs-code from deb /shell=bash))

### (lxc + bash)
```
peterg@ubuntu:~$ lxc profile show p1 > p1-profile.yml
peterg@ubuntu:~$ wc p1-profile.yml 
 13  25 184 p1-profile.yml
peterg@ubuntu:~$ cat p1-profile.yml 
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: p1
used_by: []
```
### (lxc + (vs-code from snap /shell=bash))

```
:~$ sudo snap install code --classic
code e5a624b7 from Visual Studio Code (vscode✓) installed
:~$ code .
```
Now from code terminal bash:  **FAIL**

```
:~$ lxc profile copy default p2
:~$ lxc profile ls
+---------+---------+
|  NAME   | USED BY |
+---------+---------+
| default | 0       |
+---------+---------+
| p1      | 0       |
+---------+---------+
| p2      | 0       |
+---------+---------+
:~$ lxc profile show p2
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: p2
used_by: []
:~$ lxc profile show p2 > p2-profile.yml
:~$ wc p2-profile.yml 
0 0 0 p2-profile.yml
```
### (lxc + (vs-code from deb /shell=bash))
Reverted to `LXD snap install and init only` VMware snapshot.

Install vs-code from ms repository
```
[...]
> sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
sudo apt install code
[...]
> code .
```
results from within vscode terminal bash:  **Success**
```
~$ lxc profile copy default p3
~$ lxc profile show p3
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: p3
used_by: []
~$ lxc profile show p3 > p3-profile.yml
~$ wc p3-profile.yml 
 13  25 184 p3-profile.yml
```
