### ISSUE TITLE
Support for CSS3 speech properties voice-family, voice-pitch, voice-range and voice-stress

### ISSUE THREAD

**Issue by gdsotirov** [microsoft/vscode#111133]
Using CSS3 speech properties in a style sheet currently causes Code to display warnings "Unknown property", so I'd like to request you add support for the following properties:

- `voice-family`
- `voice-pitch`
- `voice-range`
- `voice-stress`

Example style sheet:

```css
@media speech {
  h1, h2, h3, h4, h5, h6 {
    voice-family: paul, male;
    voice-stress: reduced;
  }

  h1 {
    voice-pitch: x-low;
    voice-range: +75%;
  }

  h2 {
    voice-pitch: x-low;
    voice-range: +60%;
  }

  h3 {
    voice-pitch: low;
    voice-range: +45%;
  }
}
```

These are completely legitimate properties and the example style sheet is validated OK by [W3C's CSS Validation Service](https://jigsaw.w3.org/css-validator/).

For reference please, see [W3C's CSS Speech Module](https://www.w3.org/TR/css-speech-1/).
