### ISSUE TITLE
Width of tooltip window for inspection of debug variables is unpractical

### ISSUE THREAD

**Issue by sredko** [microsoft/vscode#111917]
- VSCode Version: Version: 1.51.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Start a debug session, pause process execution.
2.  Hover mouse over struct variable to inspect its fields that have long string content.

Actual result: tooltip window appears with variable content truncated.
Expected result: UI should provide convenient means to see full content of a variable.

Does this issue occur when all extensions are disabled?: Yes/No
![issue](https://user-images.githubusercontent.com/1440380/101224395-4e578780-3643-11eb-9c11-c7e1780f3ad6.jpg)

**Comment by ashtongao** [comment]
The limit of max width in the debugHover.css is the reason for this problem.

```css
.monaco-editor .debug-hover-widget .complex-value {
	max-width: 700px;
}
```

Try to change the max width from 700px to fit-content，problem is sovled.

```css
.monaco-editor .debug-hover-widget .complex-value {
	max-width: fit-content;
}
```

[Problem]

![image](https://user-images.githubusercontent.com/45849828/101234254-9edcec80-36f8-11eb-8f96-7c38b52e66c9.png)

[After Fix]

![image](https://user-images.githubusercontent.com/45849828/101234245-84a30e80-36f8-11eb-9b0d-f0b618d6830b.png)
