### ISSUE TITLE
[css] Funny coloring of CSS property

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#11216]
![image](https://cloud.githubusercontent.com/assets/5047891/18091507/2a4ca5f0-6ec9-11e6-84ed-92ef414f1b2e.png)
- Theme: Light+
- open file `editor.css`:

``` css
.monaco-editor {
    position: relative;
    overflow: visible;
    -webkit-text-size-adjust: 100%;
    -ms-high-contrast-adjust: none;
    -webkit-font-feature-settings: "liga" off, "calt" off;
    font-feature-settings: "liga" off, "calt" off;
}
```
