### ISSUE TITLE
[yaml] [syntax-highlighting] Multi-line implicit strings break the file's syntax highlighting if they end in a single quotation mark

### ISSUE THREAD

**Issue by munael** [microsoft/vscode#112392]
- VSCode Version: 1.52.0
- OS Version: Windows 10 2004

Steps to Reproduce:

```yaml
foo:
- bar:
  - foo '{
    }'
# Highlighting is broken starting here (shows as continuation of the string): --->>>
  baz:
  - foo
```

Does this issue occur when all extensions are disabled?: Yes
