### ISSUE TITLE
[css] linear keyword is not coloured

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11569]
``` css
.foo {
    animation: fadein 100ms linear;
    animation: fadein 100ms ease-in;
}
```

`ease-in` will be coloure, but not `linear`.
