### ISSUE TITLE
Add transition to window buttons

### ISSUE THREAD

**Issue by chaitunya** [microsoft/vscode#116076]
When using the custom titlebar option in VS Code, hovering over the window buttons does not produce an smooth transition. Certain other apps, such as Edge, Chrome, File Explorer, and Windows Terminal have have this smooth transition. I would like to add a transition to the window buttons in the custom titlebar option for VS Code. That would involve adding this CSS code to `src/vs/workbench/browser/parts/titlebar/media/titlebarpart.css`:

```css
.monaco-workbench .part.titlebar > .window-controls-container > .window-icon:hover {
	transition: background 0.25s;
}
```

Before:

https://user-images.githubusercontent.com/13303232/107177420-a9309680-6986-11eb-8396-8a9492e4ea7b.mp4

After:

https://user-images.githubusercontent.com/13303232/107177459-bfd6ed80-6986-11eb-9e25-b47af6665cd0.mp4
