### ISSUE TITLE
Don't allow tabs to expand when using editor.wrapTabs

### ISSUE THREAD

**Issue by jjspace** [microsoft/vscode#116145]
When tabs wrap to a new line the they start to stretch and expand to fill available space on the new row. This is conflicting behavior with how they behave if there are not enough tabs to fill the first row. In this case they all keep the max width they should take up and *no more*. I would expect all tabs to act this way regardless of which row they are on, not expand. I find the expanding looks wrong, the close `X` is too far away from the file name. Same problem when combined with the new `editor.decorations.badges`, they can be very "far" from the filename.

Please at least add an option to not allow the tabs to expand.

- VSCode Version: 1.53.0

Steps to Reproduce:

1. Enable `editor.wrapTabs`
2. Open enough tabs that they wrap to a new line

**Comment by jjspace** [comment]
I'm not super familiar with the VSCode code but playing around with the inspector it seems removing this style rule *almost* achieves what I'm looking for.
```css
.monaco-workbench .part.editor>.content .editor-group-container>.title>.tabs-and-actions-container.wrapping .tabs-container>.tab.sizing-fit {
    flex-grow:1;
}
```
However it does seem this has the side-effect of allow a row that's not the "last" one have empty space at the end of it which I assume is why this rule was created in the first place. I think a good solution might be to prevent the `flex-grow` on only tabs in the last row. However I'm not sure how easy that would be within the structure of this app.
