### ISSUE TITLE
Make status bar overflow-x scrollable

### ISSUE THREAD

**Issue by nathanrpage97** [microsoft/vscode#117494]
When the bottom statusbar is overpopulated it simply cuts-off and there is no way to access  hidden content.

By setting:

```css

.statusbar {
    overflow-x: scroll;
}

.statusbar::-webkit-scrollbar {
    display: none;
}

.statusbar .right-items {
    flex-wrap: nowrap; /* prevent right-items from wrapping to new hidden lines */
}
```

You can now scroll through the statusbar content.
