### ISSUE TITLE
Storing secrets in user settings

### ISSUE THREAD

**Issue by g3n35i5** [microsoft/vscode#119015]
I would like to know if it is planned that you can save secrets in the user settings. I think of an implementation like it was done for example at [Home Assistant](https://www.home-assistant.io/docs/configuration/secrets/): Passwords or tokens can be stored in the separate file `secrets.yaml` and referenced in the configuration with `!secret secretVariableName`.

```yaml
http_password: "YOUR_PASSWORD"
```
```yaml
homeassistant:
  auth_providers:
   - type: legacy_api_password
     api_password: !secret http_password
```
I am aware that there is already similar feature request https://github.com/microsoft/vscode/issues/15909 (Extending settings files), but I think that my feature request would at least be a useful addition to this approach.
