### ISSUE TITLE
Feature Request: Add Guide lines to indicate folder structure

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#11902]
Currently, it's hard to figure out where the `code` folder is in the tree structure:

![image](https://cloud.githubusercontent.com/assets/4033249/18447562/0ba25cd6-78dc-11e6-92da-a6023798e117.png)

Would be great if such guide lines should be added (of course not red color):

![image](https://cloud.githubusercontent.com/assets/4033249/18447857/43afaf9c-78dd-11e6-87aa-7a14e8b87ea1.png)

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by octref** [comment]
@isidorn 

![image](https://user-images.githubusercontent.com/4033249/33090894-5b106e3c-ceaa-11e7-95f5-f1c66be4a413.png)

Can we reconsider it?

**Comment by octref** [comment]
@v0lkan

**Comment by v0lkan** [comment]
Hi guys,

The reason I made the change was because there are lots of `index.scss` and `index.js` entry points in the project that I’m working; and it was hard to visually discern where I was at without the guidelines.

In addition, I have a very mild form of dyslexia and some astigmatism (similar to %30 of the general population) — So aside from aesthetics, the guides also provide an accessibility aid.

It would be nice to have this feature, turn it off by default, and hide behind a flag maybe.

Just my 2c.

— 

As an aside, the hack took, like 30mins of my time tops, and it was just about overriding a bunch of `monaco-foo` styles.

Here is roughly what I did:

```css
.monaco-tree-row {
overflow: hidden;
position: relative;
}

.monaco-tree-row:before {
content: '';
background: rgba(255, 255, 255, 0.4);
position: absolute;
width: 1px;
height: 100%;
}

.monaco-tree-row:after {
content: '';
background: rgba(255, 255, 255, 0.4);
position: absolute;
width: 14px;
height: 1px;
top: 50%;
}

.monaco-tree-row:not([aria-level="1"]):not([aria-level="2"]):before {
box-shadow:  -20px 0 0 0 rgba(255, 255, 255, 0.4),
-40px 0 0 0 rgba(255, 255, 255, 0.4),
-60px 0 0 0 rgba(255, 255, 255, 0.4),
-80px 0 0 0 rgba(255, 255, 255, 0.4),
-100px 0 0 0 rgba(255, 255, 255, 0.4),
-120px 0 0 0 rgba(255, 255, 255, 0.4),
-140px 0 0 0 rgba(255, 255, 255, 0.4),
-160px 0 0 0 rgba(255, 255, 255, 0.4),
-180px 0 0 0 rgba(255, 255, 255, 0.4),
-200px 0 0 0 rgba(255, 255, 255, 0.4),
-220px 0 0 0 rgba(255, 255, 255, 0.4),
-240px 0 0 0 rgba(255, 255, 255, 0.4),
-260px 0 0 0 rgba(255, 255, 255, 0.4);
}

.monaco-tree-row[aria-level="1"]  { padding-left:   0px !important; }
.monaco-tree-row[aria-level="2"]  { padding-left:  20px !important; }
.monaco-tree-row[aria-level="3"]  { padding-left:  40px !important; }
.monaco-tree-row[aria-level="4"]  { padding-left:  60px !important; }
.monaco-tree-row[aria-level="5"]  { padding-left:  80px !important; }
.monaco-tree-row[aria-level="6"]  { padding-left: 100px !important; }
.monaco-tree-row[aria-level="7"]  { padding-left: 120px !important; }
.monaco-tree-row[aria-level="8"]  { padding-left: 140px !important; }
.monaco-tree-row[aria-level="9"]  { padding-left: 160px !important; }
.monaco-tree-row[aria-level="10"] { padding-left: 180px !important; }
.monaco-tree-row[aria-level="11"] { padding-left: 200px !important; }
.monaco-tree-row[aria-level="12"] { padding-left: 220px !important; }
.monaco-tree-row[aria-level="13"] { padding-left: 240px !important; }
.monaco-tree-row[aria-level="14"] { padding-left: 260px !important; }
.monaco-tree-row[aria-level="15"] { padding-left: 280px !important; }

.monaco-tree-row[aria-level="1"]:before { display: none; }
.monaco-tree-row[aria-level="2"]:before   { left:  11px; }
.monaco-tree-row[aria-level="3"]:before   { left:  31px; }
.monaco-tree-row[aria-level="4"]:before   { left:  51px; }
.monaco-tree-row[aria-level="5"]:before   { left:  71px; }
.monaco-tree-row[aria-level="6"]:before   { left: 91px; }
.monaco-tree-row[aria-level="7"]:before   { left: 111px; }
.monaco-tree-row[aria-level="8"]:before   { left: 131px; }
.monaco-tree-row[aria-level="9"]:before   { left: 151px; }
.monaco-tree-row[aria-level="10"]:before  { left: 171px; }
.monaco-tree-row[aria-level="11"]:before  { left: 191px; }
.monaco-tree-row[aria-level="12"]:before  { left: 211px; }
.monaco-tree-row[aria-level="13"]:before  { left: 231px; }
.monaco-tree-row[aria-level="14"]:before  { left: 251px; }
.monaco-tree-row[aria-level="15"]:before  { left: 271px; }

.monaco-tree-row[aria-level="1"]:after { display: none; }
.monaco-tree-row[aria-level="2"]:after   { left:  11px; }
.monaco-tree-row[aria-level="3"]:after   { left:  31px; }
.monaco-tree-row[aria-level="4"]:after   { left:  51px; }
.monaco-tree-row[aria-level="5"]:after   { left:  71px; }
.monaco-tree-row[aria-level="6"]:after   { left: 91px; }
.monaco-tree-row[aria-level="7"]:after   { left: 111px; }
.monaco-tree-row[aria-level="8"]:after   { left: 131px; }
.monaco-tree-row[aria-level="9"]:after   { left: 151px; }
.monaco-tree-row[aria-level="10"]:after  { left: 171px; }
.monaco-tree-row[aria-level="11"]:after  { left: 191px; }
.monaco-tree-row[aria-level="12"]:after  { left: 211px; }
.monaco-tree-row[aria-level="13"]:after  { left: 231px; }
.monaco-tree-row[aria-level="14"]:after  { left: 251px; }
.monaco-tree-row[aria-level="15"]:after  { left: 271px; }
```

So, my gut feeling is, the actual implementation should not take a big effort; and it would be a right step towards making Visual Studio Code more accessible.

### Additional Notes

My current quote “fix” is just a hack. Here are some observations:

* Not all icon themes worked alike; it worked well with “sublime pro” set of icon themes though. – That said, most icon themes did pretty well.
    * In particular, it did not work well with narrow ones like “Ayu”; and “indented a lot” ones like "Rusty Icons”,
* When the colorscheme is white, the guides are barely noticeable.
* When I changed a bunch of icon themes back and forth, the sidebar got totally messed up — though I’m using the “insider” version of VS code, so something else might be causing that too. — I was not able to reliably reproduce it.

Just wanted to share.

V.
