### ISSUE TITLE
Update snap to use `base:`

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#119436]
More info: https://github.com/microsoft/vscode/pull/118116#issuecomment-802251920

https://snapcraft.io/blog/all-about-that-base

**Comment by joaomoreno** [comment]
From @igorljubuncic:

>Some notes:
>
>1. Code-oss needs to be built in a 20.04 docker container, so you will need to amend the docker line to use a 20.04 image, build your own image, or configure the container to have core20 installed. Otherwise, it will either segfault on pixbufs, or hang on launch.
>
>Re: docker/image, we have some of this documented:
>https://github.com/snapcore/snapcraft/blob/master/docker/Dockerfile
>This is a direct link to a Dockerfile that can be parametrized to build the right thing.
>
>2. For reference, I built vscode from deb on a 20.04 machine, and it works just fine.
>I ran it in both Ubuntu and Fedora.

VS Code:

```yaml
name: vscode
version: "1.0"
summary: Code editing. Redefined.
description: |
  Visual Studio Code is a new choice of tool that combines the
  simplicity of a code editor with what developers need for the core
  edit-build-debug cycle.

architectures:
  - build-on: amd64
    run-on: amd64

grade: stable
confinement: classic
base: core20

parts:
#  gnome:
#    plugin: nil
#    build-packages:
#      - software-properties-common
#    override-pull: |
#      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
#      apt -y update

  code:
#    after:
#      - gnome
    plugin: dump
    source: ./code_1.54.3-1615806378_amd64.deb
    source-type: deb
    stage-packages:
      - libx11-xcb1
      - libx11-6
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxrandr2
      - libasound2
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libcairo2
      - libdrm2
      - libgbm1
      - libgdk-pixbuf2.0-0
      - libgtk-3-0
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libsecret-1-0
      - libxcb1
      - libxkbcommon0
      - libxkbfile1
#    prime:
#      - -usr/share/doc
#      - -usr/share/fonts
#      - -usr/share/icons
#      - -usr/share/lintian
#      - -usr/share/man

apps:
  code:
    #extensions: [gnome-3-34]
    command: usr/share/code/bin/code
    common-id: code.desktop
    environment:
      DISABLE_WAYLAND: 1
      GSETTINGS_SCHEMA_DIR: usr/share/glib-2.0/schemas

  url-handler:
    command: usr/share/code/bin/code --open-url
    environment:
      DISABLE_WAYLAND: 1
      GSETTINGS_SCHEMA_DIR: usr/share/glib-2.0/schemas
```

OSS:

```yaml
name: @@NAME@@
version: @@VERSION@@
summary: Code editing. Redefined.
description: |
  Visual Studio Code is a new choice of tool that combines the
  simplicity of a code editor with what developers need for the core
  edit-build-debug cycle.

architectures:
  - build-on: amd64
    run-on: @@ARCHITECTURE@@

grade: stable
confinement: classic
base: core20

parts:
#  gnome:
#    plugin: nil
#    build-packages:
#      - software-properties-common
#    override-pull: |
#      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
#      apt -y update

  code:
#    after:
#      - gnome
    plugin: dump
    source: .
    stage-packages:
      #- libc6 # without it, pixbuf segfaults, with it code-oss runs on non-xenial-built images but is not responsive
      - libx11-xcb1
      - libx11-6
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxrandr2
      - libasound2
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libcairo2
      - libdrm2
      - libgbm1
      - libgdk-pixbuf2.0-0
      - libgtk-3-0
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libsecret-1-0
      - libxcb1
      - libxkbcommon0
      - libxkbfile1
#    stage-packages:
#      - ibus-gtk3
#      - fcitx-frontend-gtk3
#      - gvfs-libs
#      - libasound2
#      - libgconf-2-4
#      - libgdk-pixbuf2.0-0
#      - libglib2.0-bin
#      - libgnome-keyring0
#      - libxkbfile1
#      - libgbm1
#      - libgtk-3-0
#      - libnotify4
#      - libnspr4
#      - libnss3
#      - libpcre3
#      - libpulse0
#      - libsecret-1-0
#      - libxss1
#      - libxtst6
#      - zlib1g
#    prime:
#      - -usr/share/doc
#      - -usr/share/fonts
#      - -usr/share/icons
#      - -usr/share/lintian
#      - -usr/share/man

apps:
  @@NAME@@:
    #extensions: [gnome-3-34]
    command: electron-launch $SNAP/usr/share/@@NAME@@/bin/@@NAME@@
    common-id: @@NAME@@.desktop
    environment:
      DISABLE_WAYLAND: 1
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas

  url-handler:
    command: electron-launch $SNAP/usr/share/@@NAME@@/bin/@@NAME@@ --open-url
    environment:
      DISABLE_WAYLAND: 1
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
```
