### ISSUE TITLE
Hide fold bar in Zen mode

### ISSUE THREAD

**Issue by tejasvi** [microsoft/vscode#122896]
Fold bar in Zen mode is very distracting with nested markdown lists. It will be nice to hide it _without_ disabling folding (with `   "editor.folding": false`). I am aware of `"editor.showFoldingControls": "mouseover"` but it leaves empty space in full screen.

![image](https://user-images.githubusercontent.com/45873379/116963447-803e4a00-acc6-11eb-9c99-18730f7e0892.png)

**Comment by isidorn** [comment]
Let's close as dup of https://github.com/microsoft/vscode/issues/45617
Since that issue could be used to resolve this

**Comment by tejasvi** [comment]
In case someone else stumbles here, apply the below css using [Custom CSS and JS loader](https://github.com/be5invis/vscode-custom-css).
```css
.fullscreen .monaco-scrollable-element.editor-scrollable.vs {
  left: 0px !important;
  width: 2736px !important; /* Needs adjustment */
}
```
