### ISSUE TITLE
Getting Started: Polish quote padding

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#123476]
Repro:

- Use `> ...` in a markdown walkthrough step

![image](https://user-images.githubusercontent.com/2193314/117670851-1ce86800-b15d-11eb-8929-f89f453d3801.png)

Something like this would fix:

```css
blockquote > p:first-child {
  padding-top: 0;
}
```
