### ISSUE TITLE
:focus-visible and :user-invalid pseudoclasses are not properly highlighted

### ISSUE THREAD

**Issue by wojtekmaj** [microsoft/vscode#124369]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: macOS Big Sur

Steps to Reproduce:

1. Write the following CSS

```css
a:hover         { color: red; }
a:focus         { color: red; }
a:focus-visible { color: red; }
a:invalid       { color: red; }
a:user-invalid  { color: red; }
```

Expected result:

All pseudoclasses correctly highlighted

Actual result:

<img src="https://user-images.githubusercontent.com/5426427/119154338-59b43900-ba52-11eb-897f-e3837e098c5b.png" width="434" />
