### ISSUE TITLE
[themes] Customize the icons of ignore resources

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/vscode#126189]
`gitignore` foreground color only applies to the text label.
Would be great to customise `gitignore`d icons in the Explorer:

<img alt="workbench" src="https://user-images.githubusercontent.com/82655227/121827775-4b55e780-ccb5-11eb-9b1a-6744ec76247a.png" height="150px" width="500px" />

The CSS that I used to achieve that effect:
```css
.file-icons-enabled.monaco-workbench.vs-dark .monaco-decoration-iconBadge--9ieymw::before {
    filter: saturate(0);
    opacity: 0.25;
}
.file-icons-enabled.monaco-workbench.vs .monaco-decoration-iconBadge--9ieymw::before {
    filter: saturate(0);
    opacity: 0.5;
}
```

This feature as supported in Atom's Git integration:

<img src="https://user-images.githubusercontent.com/82655227/122053786-f8784f00-cdde-11eb-9df9-f9d3f268eb0b.png" height="400px" width="600px" />

Related to https://github.com/PKief/vscode-material-icon-theme/issues/224.
