### ISSUE TITLE
Customize pylance in pyproject.toml

### ISSUE THREAD

**Issue by Ierezell** [microsoft/vscode#126264]
Instead of configuring Pylance from `.vscode/settings.json` configure it within the `pyproject.toml`. 

I've seen it's working for Pyright and I have this configuration : 

```toml
[tool.pyright]
root = ['src']
include = ["src"]
exclude = ["**/node_modules", "**/__pycache__"]

useLibraryCodeForTypes = true

strict = ["src"]
typeCheckingMode = "strict"

reportMissingImports = "information"
reportMissingTypeStubs = "information"
reportUnknownMemberType = "information"
```

But I'm not able to make Pylance work with it (for exemple missings stubs are still flagged as error)

Have a great day
