### ISSUE TITLE
[scss] map value override => identifier expected

### ISSUE THREAD

**Issue by nicolashenry** [microsoft/vscode#126507]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create a `test..scss` file:
```scss
$test: (
    test1: red,
    test2: blue
);
```
2. Create a `test2..scss` file:
```scss
@use 'sass:map';
@use './test';

test.$test: (
    test1: green,
    test2: yellow
);

.test {
    color: map.get(test.$test, 'test1');
    background-color: map.get(test.$test, 'test2');
}
```
And see that Visual Studio Code display an `identifier expected scss(css-identifierexpected)` error:

![image](https://user-images.githubusercontent.com/139160/122260760-ec21ee00-ced3-11eb-8ba8-ba96b40e5412.png)

4. In command line (with npm `sass` package `1.35.1` installed globally), type:
```sh
sass test2.scss
```
and see that there is no error (so the syntax is supposed to be ok):
![image](https://user-images.githubusercontent.com/139160/122261010-399e5b00-ced4-11eb-8698-f7a6fef5fbc9.png)

I don't know if this was supposed to work since I have not found any documentation about overriding variable from a module namespace. But it seems to be actually a valid syntax so Visual Studio Code should probably not complain :) (or is this a bug in sass ?) 

Note that it also trigger an `identifier expected` error also for simple variables (so not only maps)
