### ISSUE TITLE
CSS no longer produces warning in this case

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126658]
Following snippet:

```css
.foo{}body {
  padding: 50px;
  font: 14px "Lucida Grande", Helvetica, Arial, sans-serif;
}

a {
  color: #00B7FF;
}
```

No longer results in a warning and thus makes the smoke test fail.
