### ISSUE TITLE
[css] support /*csslint ignore:start,end */ directives

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#13003]
- VSCode Version: 1.6.0
- OS Version: Windows 10

Steps to Reproduce:
1. This happens while working with [css-modules](https://github.com/css-modules/css-modules).
2. Write this css:

``` css
.error {
  /* csslint ignore:start */
  composes: content from "./Modal/Modal.module.css";
  /* csslint ignore:end */
  border-color: #DE3A3A;
  box-shadow: 0 0 20px -2px #DE3A3A;
  color: white;
  text-align: center;
}
```
1. vscode should not lint those lines. Ref: https://github.com/CSSLint/csslint/wiki/Ignoring-parts-of-CSS-during-linting
