### ISSUE TITLE
@property [color syntax] - hex values irregularities

### ISSUE THREAD

**Issue by tomasmoberg** [microsoft/vscode#130826]
Issue Type: <b>Bug</b>

For hex colors beginning with a letter, the subsequent semicolon becomes red:

```css
@property --light-blue { syntax: '<color>'; inherits: false; initial-value: #ace; }
```

For hex colors beginning with a number, the subsequent semicolon becomes white (as it should):

```css
@property --dark-gray { syntax: '<color>'; inherits: false; initial-value: #123; }
```

VS Code version: VSCodium 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-09T15:54:41.116Z)
OS version: Linux x64 5.4.0-81-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) 2955U @ 1.40GHz (2 x 1311)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|3.75GB (0.23GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none
