### ISSUE TITLE
Add selection.foreground and let WebViews style textareas like those in settings and the search panel

### ISSUE THREAD

**Issue by panayot-cankov** [microsoft/vscode#131696]
I am styling input and textarea elements in a WebView extensions, and I try to keep them as close as possible to the user selected theme. The selection is a struggle though. One thing to note is there is a CSS variable for `selection.background` and the following works well for themes that define it:

``` CSS
input::selection {
    background: var(--vscode-selection-background);
}
```

But the default selection for the light+ theme uses blue background and white foreground, where the white foreground is different from the default dark gray text foreground color. Once the following input::selection rule is added it changes the the **foreground** color of the selection as well. But there is no `selection.foreground` variable that I could add in. Then for some themes the `selection.background` is not set, and trying to use a fallback in CSS, that implements the default selection colors goes something like:

``` CSS
input::selection {
    background: var(--vscode-selection-background, blue);
    color: var(--vscode-selection-foreground, white);
}
```

However then the themes that actually set `selection.background` get the wrong foreground. In VSCode this is handled here by adding the `::selection` conditionally:
https://github.com/microsoft/vscode/blob/d163f3f3d458fb65f4bb336d14ce6bdb323a0c9f/src/vs/workbench/browser/style.ts#L34-L37

I am about to try to port something similar in my js for my WebView extensions. But it would be so much easier if the --vscode-selection-background AND --vscode-selection-foreground were always provided to CSS, and when the keys were missing in the theme, were somehow interpolated, inferred or we got some defaults, that would let the following just work and style inputs the same as the search text fields and inputs:
``` CSS
input::selection {
    background: var(--vscode-selection-background, blue);
    color: var(--vscode-selection-foreground, white);
}
```

Other than that, using high contrast selection background color, would often require setting the foreground as well. For me it makes perfect sense to add selection.foreground to the selection.background, even if we don't get them in CSS when they are not set. I found a few issues about selection colors and some work has been done on them, but I wonder, if there is chance something like this could be added?
