### ISSUE TITLE
Does travis not load the workspace anymore?

### ISSUE THREAD

**Issue by buehler** [Microsoft/vscode#13191]
- VSCode Version: 1.5.3
- OS Version: Travis CI v??? :-)

Steps to Reproduce:

1. Code a test that uses stuff from the workspace.
2. Run tests on headless travis ci

It seems that the workspace is not correctly loaded since some releases (1.5 I presume).
When I use some workspace files in my tests, they aren't correctly loaded and my tests fail.

The travis yaml seems complete (I hope at least):

```yaml
sudo: false

language: node_js
node_js:
- '6'

os:
- osx

install:
- npm run bootstrap
- npm run build

script:
- npm test --silent

env:
  global:
    - CODE_TESTS_WORKSPACE=$TRAVIS_BUILD_DIR/.test/
```

Did I forget something?

When I run the following command on my OSX, it works like a charm: `CODE_TESTS_WORKSPACE=$PWD/.test/ npm test`

Cheers
