### ISSUE TITLE
[css] Word highlight is computed wrong when in CSS comments

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#1324]
```css
.monaco-editor .inlineKeybindingMismatch:before {
	margin: 0.1em 0.1em 0 0.1em;
	content:" ";
	display:inline-block;
	height:1em;
	width:1em;
	/*line-height:1em;*/
	/*border:0.1em solid #000;*/

	background: url(status-error.svg) 0px 0px no-repeat;
	background-size: 1em;
}
```

![css-word](https://cloud.githubusercontent.com/assets/5047891/11808987/1ab22de8-a324-11e5-8da5-0ef05daaa1e1.gif)
