### ISSUE TITLE
Bracket pair colorization and language mode override not working

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#132979]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Ubuntu 20.04.2 LTS (using remote coding with Windows 10 version 18363.1734)

Steps to Reproduce:

1. Configure this:
```json
  "editor.bracketPairColorization.enabled": true,
  "[helm-template]": {
    "editor.bracketPairColorization.enabled": false
  },
```
2. Install the 'Kubernetes' extension.
3. Add this to a file:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test
  annotations:
    {{- if .Values.annotations }}
    {{- .Values.annotations | toYaml | nindent 4 }}
    {{- end }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    resourceNames: [""]
    verbs:
      - list
      - watch
```
4. Make sure the file has the language mode `helm-template`

Notice how bracket colorization is still done in the file.
