### ISSUE TITLE
Incorrect context submenu position caused by transform ancestor

### ISSUE THREAD

**Issue by crimx** [microsoft/vscode#133595]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: 1.60.1
- OS Version: web

The issue occurs when trying to intergrate VSCode (or Monaco) into a `transform` parent element.

Steps to Reproduce:

1. https://github.com/microsoft/vscode/blob/33c149f3ad49db462cb451f4db2e01d64b15e40b/src/vs/workbench/browser/media/style.css#L44-L46
   Replace the `body.web {}` with:
   ```css
   body.web {
     position: absolute;
     left: 0;
     top: 0;
     will-change: transform;
     transform: translate(100px, 100px);
   }
   ```
2. Run `yarn watch` and `yarn web`.
3. Right click the editor and move the mouse to a context menu item with submenu.
4. The submenu is in incorrect position.
   ![image](https://user-images.githubusercontent.com/6882794/134338793-3f181e56-ccbc-4869-a12b-85ce024dc9ea.png)

Reason:

This is because `transform` ancestor [behaves as the containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/position#values) of fixed descendants.

Here is the code that causes the issue:

https://github.com/microsoft/vscode/blob/83bd43bc519d15e50c4272c6cf5c1479df196a4d/src/vs/base/browser/ui/menu/menu.ts#L920-L921

A PR has been made for this issue.
