### ISSUE TITLE
Incorrect syntax highlighting with YAML plain flow scalar multiline strings

### ISSUE THREAD

**Issue by izhess** [microsoft/vscode#134264]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.2
- OS Version: macOS Big Sur, Version 11.6

Steps to Reproduce:

1. Write YAML with multiline string, like this:

```yaml
bar: Multiline start
  | newline pipe character is valid in Plain Flow Scalar, but is highlighted as error
baz: quux
```
2. Save the YAML-file and notice the syntax highlight is incorrect:

![image](https://user-images.githubusercontent.com/85281836/135588957-010ec606-146f-4511-a7aa-00565f6a51a9.png)
