### ISSUE TITLE
Scrollable shadow no longer using the theme color

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#137337]
The shadow color on the views no longer uses the theme color -- it's still there in the css, but its specificity is less than the default.

This was a very recent change, I think related to https://github.com/microsoft/vscode/commit/d2587206e45be30cc398f3173285f424bb635878

![image](https://user-images.githubusercontent.com/641685/142086435-a668dac4-97b6-4bb6-9768-74d801b2178c.png)

/cc @misolori @alexdima

**Comment by alexdima** [comment]
@eamodio I cannot reproduce. Here is what I have tried:
```
"workbench.colorCustomizations": {
	"scrollbar.shadow": "#ff0000"
},
```
and that works for me:
![image](https://user-images.githubusercontent.com/5047891/142159383-891fcbf5-18ce-4904-a308-1e34a24e2796.png)

Is there a specific theme that I can use to reproduce?

**Comment by eamodio** [comment]
@alexdima so I did some more digging -- and it looks like it only happens after you open a menu (and you probably need to be using custom menus). Once the menu opens, it causes a new style block to get added which takes precedence:

```css
.monaco-scrollable-element > .shadow.top {
    display: block;
    top: 0;
    left: 3px;
    height: 3px;
    width: 100%;
    box-shadow: #ddd 0 6px 6px -6px inset;
}
```
