### ISSUE TITLE
[less] Errors with !important declaration in variables

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#14120]
- VSCode Version: 1.6.1 + 1.7.0
- OS Version: Windows 10

``` less
@a: #fff;
@b: @a !important;

.test {
    background-color: @b;
}
```

![image](https://cloud.githubusercontent.com/assets/7034281/19576793/1926b08c-971d-11e6-8fb0-891c1647804c.png)

Proof: [less2css](http://less2css.org/#%7B%22less%22%3A%22%40a%3A%20%23fff%3B%5Cn%40b%3A%20%40a%20!important%3B%5Cn%5Cn.test%20%7B%5Cn%20%20%20%20background-color%3A%20%40b%3B%5Cn%7D%22%7D)
