### ISSUE TITLE
Configure tooltip max width

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#14165]
When you hover over a type in a TypeScript file, the tooltip that appears has a very low max width, making it difficult to read long type signatures.

**Comment by OliverJAsh** [comment]
I would include a screenshot but it's not easy to take a screenshot keeping the tooltip on screen!

**Comment by maxhoffmann** [comment]
![2017-01-03 14 38 46](https://cloud.githubusercontent.com/assets/1227441/21610898/75c0566a-d1c2-11e6-9898-4239d5a34c63.gif)

Errors are quite unreadable if the width does not adapt to the font size.

**Comment by rakkarage** [comment]
![2017-02-16 2](https://cloud.githubusercontent.com/assets/962340/23047121/d3344064-f47b-11e6-9f0f-7ec6841cb7ff.png)
it would be nice if the tip used the available space instead of wrapping at an arbitrary point

**Comment by rakkarage** [comment]
![2017-03-09 2](https://cloud.githubusercontent.com/assets/962340/23755841/b0bc60f4-04af-11e7-8f48-df0da13ebfcb.png)

**Comment by anowell** [comment]
![tooltip](https://cloud.githubusercontent.com/assets/2629687/25759705/d0fe8384-3190-11e7-8061-8b2e4e61ee63.png)

Same problem using rust's language server.

**Comment by crucialfelix** [comment]
General styling control would be very helpful. Also line-height.  

Another approach would be to have a bottom panel that displays the full error and the tooltip displays a shortened version.

**Comment by rakkarage** [comment]
![2018-02-15](https://user-images.githubusercontent.com/962340/36287949-29004eba-1286-11e8-89da-22a114bb2f2c.png)

**Comment by Tiedye** [comment]
![image](https://user-images.githubusercontent.com/6187173/37847674-0187f43a-2ea8-11e8-9211-8105f92d1622.png)

When using the auto import feature it is often impossible to differentiate whats what as the import path is cut off due to the limited width of the suggestions window.

**Comment by MikhailArkhipov** [comment]
Same in Python. We have to just through hoops trying to flow doc nicely. And when it appears OK on Windows, it breaks on Mac... 

![image](https://user-images.githubusercontent.com/12820357/38449834-94ddf334-39c9-11e8-8646-6eb6729a9951.png)

And it is inconsistent. Ex, hover is OK

![image](https://user-images.githubusercontent.com/12820357/38449878-db4a38fa-39c9-11e8-9c95-ed5b51a5fdb6.png)

But completion list decides to wrap. What gives?

![image](https://user-images.githubusercontent.com/12820357/38449890-0bc533f4-39ca-11e8-951f-8eb4bc0d7aad.png)

**Comment by rakkarage** [comment]
![2018-04-15_li](https://user-images.githubusercontent.com/962340/38780926-a8ab6656-40ab-11e8-93c7-21170b8f5529.jpg)

**Comment by KaelWD** [comment]
Someone say long type signatures?
![image](https://user-images.githubusercontent.com/16421948/39526258-94e2689a-4e61-11e8-818c-a06e3a05138d.png)

**Comment by ShenHongFei** [comment]
Here is a workaround by hacking the file "C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css"

```css
    /* suggest-widget size */
        .monaco-editor .suggest-widget.docs-side {
            width: 1600px;
        }
        .monaco-editor .suggest-widget.docs-side > .details {
            width: 70%;
            max-height: 800px !important;
        }
        .monaco-editor .suggest-widget.docs-side > .tree {
            width: 30%;
            float: left;
        }
        
    /* parameter-hints-widget */
        .editor-widget.parameter-hints-widget.visible {
            max-height: 800px !important;
        }
        .monaco-editor .parameter-hints-widget > .wrapper {
            max-width: 1600px;
        }
```

Simply append the code above after the original content of file, and restart VSCode. (Title bar may alert a warning message "Not Supported" and hacked changes would be overridden by updating VSCode)

![0062](https://user-images.githubusercontent.com/15074472/42794438-59789898-89b1-11e8-9480-84c8e9816ba7.png)
