### ISSUE TITLE
block math render is strange

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#142171]
Issue Type: <b>Bug</b>

build in markdown math render
1. code
2. that is build-in render
3. that is MPE extension
![image](https://user-images.githubusercontent.com/1876302/152504687-dad28bfb-5bb3-41f1-b600-ccf9e981a2e8.png)

VS Code version: Code - Insiders 1.65.0-insider (921264bfe3ffbbfe5ec8c4b08214b88e2148fa3e, 2022-02-04T05:16:29.546Z)
OS version: Windows_NT x64 10.0.22543
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.68GB (4.98GB free)|
|Process Argv|--crash-reporter-id 5e27f758-146f-47b2-bbc6-7cfdf6237a31|
|Screen Reader|no|
|VM|40%|
</details>

**Comment by Lemmingh** [comment]
Looks like KaTeX styles are not properly applied to those elements in your environment.

Could you check the DevTools:

* When opening the Markdown preview, are KaTeX stylesheets and fonts loaded, according to the **Network** panel?

* In the preview, are KaTeX styles applied, according to the **Elements** panel?

---

Anyway, I cannot repro your problem with:

```markdown
block math is very strange

$$
a \equiv \frac{b}{b}
$$
```

```yaml
Version: 1.65.0-insider (system setup)
Commit: 921264bfe3ffbbfe5ec8c4b08214b88e2148fa3e
Date: 2022-02-04T05:16:29.546Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

All installed extensions are disabled.
