### ISSUE TITLE
[css] support unicode-range wildcard

### ISSUE THREAD

**Issue by marknn3** [microsoft/vscode#142516]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: any
- OS Version: any

Steps to Reproduce:
VS Code incorrectly flags css unicode-range wildcards as syntax error. A red squiggle will appear on the unicode-range line and on the closing bracket.

Example:
```css
@font-face {
	font-family: 'MyWebFont';
	src: url('myfont.woff') format('woff');
	unicode-range: U+00??; /* wildcard range */
}
```
This issue was opened before as #54889 but then closed due to lack of information.
