### ISSUE TITLE
yaml highlighting/textmate recognises some integers as strings (or vice versa?)

### ISSUE THREAD

**Issue by pedroterzero** [microsoft/vscode#143368]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-28-generic snap
```
OS is Ubuntu 20.04

Description:
==
Some integers (or strings?) are treated differently even though they look the same to me.

In each comment I've specified what the scope inspector reports the scope as.

This is what it ends up looking like for me:
![image](https://user-images.githubusercontent.com/72469659/154690109-b3894d1b-8c67-45f4-a66f-e8563e8b9a24.png)

I'd expect them all to be the same; so either they should all be integers or they should all be unquoted strings.

Test case:
==
```yaml
test:
  - test: 01 # constant.numeric.integer.yaml
  - test: 02 # constant.numeric.integer.yaml
  - test: 03 # constant.numeric.integer.yaml
  - test: 04 # constant.numeric.integer.yaml
  - test: 05 # constant.numeric.integer.yaml
  - test: 06 # constant.numeric.integer.yaml
  - test: 07 # constant.numeric.integer.yaml
  - test: 08 # string.unquoted.plain.out.yaml
  - test: 09 # string.unquoted.plain.out.yaml
  - test: 10 # constant.numeric.integer.yaml
```

Steps to Reproduce:

1. Create a test file, `test.yml` with the contents from the test case
