### ISSUE TITLE
[less] mixins - empty parameters

### ISSUE THREAD

**Issue by nicolashenry** [Microsoft/vscode#14563]
- VSCode Version: 1.6.1

When editing a .less file unexpected errors show when working with mixins. These errors show when using a mixin with an empty parameter.
- Code :

``` less
.mixin(@color; @padding: 2) {
  color: @color;
  padding: @padding;
}

.some .selector div {
  .mixin(#008000;);
}
```
- Errors :

![image](https://cloud.githubusercontent.com/assets/139160/19749205/70b96fd2-9be7-11e6-864d-aa3ec02099ba.png)
