### ISSUE TITLE
Contrast isn't great in find results

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#145744]
Testing #145629

We draw the find match selection on top of the text which reduces contrast pretty badly

Terminal:

![image](https://user-images.githubusercontent.com/2193314/159533026-354a2af8-b961-4016-9601-182f59938c2a.png)
![image](https://user-images.githubusercontent.com/2193314/159533041-4f9cf0ed-cc51-47f3-8511-20c1d4aa67ab.png)

Editor:

![image](https://user-images.githubusercontent.com/2193314/159533082-4cf58ffa-ac4d-40e0-b3d9-7b7d494eaf51.png)

Should we use a border instead of a solid rectangle to workaround this? It would look different from the editor but at least it wouldn't introduce contrast problems

This is what it looks like with these style overrides:

```css
.xterm-decoration.xterm-find-result-decoration {
    border: 1px solid rgba(234, 92, 0, 1) !important;
    box-sizing: border-box;
    background: transparent !important;
}
```

![image](https://user-images.githubusercontent.com/2193314/159533109-e920614b-f38d-4e84-aa92-e4caee543caf.png)

The white background on selection is due to `"terminal.selectionBackground": "#ffffff"`

We should support border styles anyway to cover the high contrast case:

![image](https://user-images.githubusercontent.com/2193314/159533135-d02db94f-591d-4493-94d3-c0d210ac14bf.png)
