### ISSUE TITLE
LESS mixin unexpected code formatting

### ISSUE THREAD

**Issue by richmilns** [microsoft/vscode#146693]
Using VSCode 1.66.0 and the new built-in LESS code formatting feature `less.format.enable` implemented by the [JS Beautify library](https://github.com/beautify-web/js-beautify).

When using a LESS mixin that accepts CSS code rules as a parameter (this is used for media query mixins), the formatting when saved is a little unexpected. The formatting is consistent, but it is unusal.

**Example code (expected formatting)**
```less
.example(@rules) {
    @rules();
}

.test {
    .example({
        color:red;
    });
}
```

**Result after saving**
```less
.example(@rules) {
    @rules();
}

.test {
    .example( {
            color:red;
        }

    );
}
```

Similar issue reported a while back [js-beautify issue 722](https://github.com/beautify-web/js-beautify/issues/722)

I've noticed that if you add the following to your `settings.json` file, the results are slightly better:

```
"less.format.newlineBetweenRules": false
```

This gives you formatting like:
```less
.example(@rules) {
    @rules();
}

.test {
    .example( {
            color:red;
        }
    );
}
```

Apologies if this isn't the right place to report this, but as it was a new feature of VSCode I figured I'd start here.
