### ISSUE TITLE
SCSS interpolation validation issues

### ISSUE THREAD

**Issue by NotSpaulding** [microsoft/vscode#146671]
Issue Type: <b>Bug</b>

VSCode misinterprets certain code snippets when [interpolation](https://sass-lang.com/documentation/interpolation) is used, giving errors and warning when the code snippets actually work fine.

Example:
```scss
$function: 'translateY';

.class {
  @if ($function) {
    transform: #{$function}(0); // scss(css-semicolonexpected) after '#{$function}'
  } @else { // scss(unknownAtRules)
    transform: translateY(0);
  }
} // scss(css-ruleorselectorexpected)

@keyframes #{$keyframe-name} { // breaks syntax highlighting on the keyframe selectors (from, to, 100%...)
  from {
    transform: #{$function}(0) translateX(0); // scss(css-semicolonexpected) after '#{$function}'
  }
  100% { // scss(css-ruleorselectorexpected) on '100%'
    transform: #{$function}(100%); // 'transform' is thought to be a selector, scss(css-lcurlyexpected) after 'transform'
  } // scss(css-ruleorselectorexpected)
}
```

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>
