### ISSUE TITLE
[css] Unexpected validation errors

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#147059]
Issue Type: <b>Bug</b>

The following CSS gives 2 validation errors on the penultimate ("semi-colon expected") and last ("at-rule or selector expected") lines.
Adding a space between `(` and `counter(foo)` makes the errors go away.
Note that https://jigsaw.w3.org/css-validator/ says this CSS is correct as-is, so I'd expect VS Code to accept it as well (unless the W3C CSS validator has a bug, of course).

```css
body {
    counter-reset: foo;
}

bar::before {
    counter-increment: foo;
    content: "("counter(foo) ")";
}
```

VS Code version: Code - Insiders 1.67.0-insider (a3d53f76790d8c88f835afe85225ff6442703409, 2022-04-07T05:15:43.863Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

Extensions: none
