### ISSUE TITLE
Allow user to customize VSCode UI by loading specific CSS style file.

### ISSUE THREAD

**Issue by x-strong** [microsoft/vscode#147065]
**Allow user to customize VSCode UI by overriding the CSS, namely that allow we specifiy a CSS file to load on VSCode startup.**
Now what I can do is to modify the workbench.desktop.main.css file under the folder "xxx\Microsoft VS Code\resources\app\out\vs\workbench", but I get a warning every time when VSCode  loaded. 
```css
.tab.active {
    text-shadow: 1px 1px 10px white;
    background-color: #ffffff26 !important;
    font-weight: bold;
    filter: brightness(2.5);
}
```
![image](https://user-images.githubusercontent.com/3232261/162390073-a5f8c3c8-de7f-4697-88d7-e1edbe2a21f7.png)

![image](https://user-images.githubusercontent.com/3232261/162387854-6155bfd7-ec01-4635-bbb0-ca570ad7479d.png)

So if we can specify a customized CSS file in Settings for VSCode to load on starting up, the problem is solved. 
That would be a great feature, big convenience and flexibility.
