### ISSUE TITLE
[css] Formatting removes useful space

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#147060]
Issue Type: <b>Bug</b>

When formatting the following CSS, the space between `"("` and `counter(foo)` on the penultimate line is removed. This results in less readable code & an ugly asymmetry, since the space between `counter(foo)` and `")"` isn't removed. Moreover, it currently triggers  #147059

```css
body {
    counter-reset: foo;
}

bar::before {
    counter-increment: foo;
    content: "(" counter(foo) ")";
}
```

VS Code version: Code - Insiders 1.67.0-insider (a3d53f76790d8c88f835afe85225ff6442703409, 2022-04-07T05:15:43.863Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

Extensions: none
