### ISSUE TITLE
Enable drop into document to insert url into css files

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#147483]
Follow up on #142990

## Feature request
I should be able to drag an image file from the explorer into a css file to insert a url. For example, with the workspace structure:

```
images/
    cat.gif
styles/
    main.css
```

If I drag `cat.gif` from the VS Code explorer into `main.css`, I should get a url such as:

```css
body {
    background-image: url(/images/cat.gif);
}
```

Users — especially beginners — may find drag and drop more natural than writing out the image path
