### ISSUE TITLE
CSS multiline string literal breaks syntax highlighter

### ISSUE THREAD

**Issue by gurutech-thomasr** [microsoft/vscode#147712]
See title.  Multiline string literal causes syntax highlighter to break:
![vscode-css-multiline](https://user-images.githubusercontent.com/6250871/164064577-f5a9ddcb-e098-4add-bd67-29270b94fa60.png)
![vscode-css-multiline-2](https://user-images.githubusercontent.com/6250871/164064871-f9c6424f-2772-4dc3-b6aa-8eda6d8a9075.png)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Windows_NT x64 10.0.19044 (Windows 10)

Steps to Reproduce:
1. Copy snippet below into new CSS file
```css
/* comment 1 */
body {
  font-family: 'Open Sans';
}

.foobar:after {
  content: '\
  ';
}

/* comment 2 */
h1 {
  font-family: 'Verdana';
}
```
