### ISSUE TITLE
`Unknown property` warnings on some css properties.

### ISSUE THREAD

**Issue by go-commit-code** [microsoft/vscode#147804]
Issue Type: <b>Bug</b>

These css properties give `Unknown Property` warnings:
- [`animation-timeline`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline)
- [`print-color-adjust`](https://developer.mozilla.org/en-US/docs/Web/CSS/print-color-adjust)
- [`vector-effect`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/vector-effect)
- [`alignment-baseline`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline)
- [`baseline-shift`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/baseline-shift)
- [`color-interpolation`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-interpolation)
- [`color-profile`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-profile)
- [`color-rendering`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-rendering)
- [`dominant-baseline`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline)

Steps to reproduce:
1. Open a css file
2. Copy and paste this snippet:

```css
div {
	animation-timeline: initial; /* In firefox 97 behind experimental flag: */
	print-color-adjust: initial; /* In firefox 97, safari 15.4 */

	/*
		Svg presentation attributes
		They don't have compatibility tables on MDN,
		but most of them are recognized in chrome devtools style panel:
	*/
	vector-effect: initial;
	alignment-baseline: initial;
	baseline-shift: initial;
	color-interpolation: initial;
	color-profile: initial; /* Is deprecated, and Chrome devtools gives a 'Unknown property name' warning */
	color-rendering: initial; /* Is deprecated and non-standard */
	dominant-baseline: initial;

	/*
		css reference on MDN also mentions this property, but there is no docs on MDN for it.
		I think it was renamed to `overflow-block`, so maybe it should remain as is.
	*/
	block-overflow: initial;
}
```
Does this issue occur when all extensions are disabled?: Yes
This is also reproducible on vscode.dev and github.dev

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:51:26.173Z)
OS version: Linux x64 5.10.101-14960-gb2e5df468a73
Restricted Mode: No
