### ISSUE TITLE
Hopefully, the scrollbar will be beautified

### ISSUE THREAD

**Issue by joesdu** [microsoft/vscode#148513]
First of all, thank you very much to the developers who contributed code to vscode for providing such excellent development tools, but I hope to beautify the scrollbar, add rounded corners and reduce the width. New scrollbar similar to Edge browser. Since I won't do electron development, This should fit into the Windows 11 UI,here's an example I've provided:

```css
::-webkit-scrollbar {
  width: 6px;
  background-color: transparent;
}

::-webkit-scrollbar-thumb {
  background-color: @primary-color;
  border-radius: 6px;
  box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.1);
}

::-webkit-scrollbar-track {
  box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.1);
}
```
