### ISSUE TITLE
[less] The each function has incorrect linting inside a keyframes at-rule

### ISSUE THREAD

**Issue by binaryfunt** [microsoft/vscode#149193]
Issue Type: <b>Bug</b>

The LESS linter raises false positive errors regarding the `each` function when used inside an `@keyframes` at-rule. Example:
```less
@keyframes foo {
  each(@steps, {
//    ^ "{ expected"
    @{value} {
//           ^ "} expected"
      width: @value;
    }
//  ^ "at-rule or selector expected"
  });
} // <- "at-rule or selector expected"
```
There is nothing wrong with the example above - it transpiles into
```css
@keyframes foo {
  0% {
    width: 0%;
  }
  50% {
    width: 50%;
  }
  100% {
    width: 100%;
  }
}
```

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (2.50GB free)|
|Process Argv|C:\\Users\\REDACTED --crash-reporter-id b1616fa4-2d33-455f-9b3a-0973b302cc16|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-cylc|cyl|1.0.3
gitlens|eam|12.0.6
git-graph|mhu|1.30.0
easy-less|mrc|1.7.3
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-wsl|ms-|0.64.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vsclangdf:30486550

```

</details>
