### ISSUE TITLE
CSS background property showing under invalid.deprecated scope despite not being invalid/deprecated.

### ISSUE THREAD

**Issue by Monstarrrr** [microsoft/vscode#150057]
The ``background`` property under ``transition`` is showing up under the ``invalid.deprecated.color.system.css`` scope, which makes it show up as an error.  
However the ``background`` property **is** animatable and not deprecated: [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties) | [W3C docs](https://www.w3schools.com/cssref/css_animatable.asp#:~:text=Definition%20and%20Usage,%2C%20numbers%2C%20percentage%20and%20color).

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: Windows 11 Home

Steps to Reproduce:

1. Create a new `css` file
2. Add the following code
```css
.test {
  transition: background;
}
```
Alternatively :
```css
.test {
  background: white;
}
.test:hover {
  background: red;
  transition: background 2s;
}
```
3. Inspect editor tokens and scopes
4. Hover on ``background``
