### ISSUE TITLE
Font bad quality

### ISSUE THREAD

**Issue by justnonamenoname** [Microsoft/vscode#15181]
- VSCode Version:1.5-1.71 (didn't tested on <1.5)
- OS Version:Windows 7

Oh - Same as #11252

Steps to Reproduce:

1. 
"editor.fontSize": 13,
"editor.fontWeight": "normal",
"editor.fontFamily": "Courier New"

Courier New - In every editor

For check - open png in new window

VSCode (bugged)
![fontex2](https://cloud.githubusercontent.com/assets/23149612/20104477/f18f5d58-a5ef-11e6-8e44-55ea0a734928.png)

Visual Studio
![fontex1](https://cloud.githubusercontent.com/assets/23149612/20104478/f191856a-a5ef-11e6-9c7e-0f1d458a1b7e.png)

Notepad
![fontex3](https://cloud.githubusercontent.com/assets/23149612/20104650/9bb544c8-a5f0-11e6-9b0a-f3bf8af35cf7.png)

Notepad++
![fontex4](https://cloud.githubusercontent.com/assets/23149612/20104593/64431f42-a5f0-11e6-8b2d-4c7821c300b1.png)

Google Chrome (bugged)
![fontex5](https://cloud.githubusercontent.com/assets/23149612/20105023/ecd83ef4-a5f1-11e6-8dba-be691a09aaf2.png)

Opera (bugged)
![fontex6](https://cloud.githubusercontent.com/assets/23149612/20105024/ecd83210-a5f1-11e6-9c5b-537e4b2281ff.png)

Mozilla
![fontex7](https://cloud.githubusercontent.com/assets/23149612/20105025/ecda2b9c-a5f1-11e6-85dc-e1d1f2d8eb2d.png)

2. Webkit problem?
In editor.fontWeight only "normal" & "bold" works
"bold" - is too bold

**Comment by alexandrudima** [comment]
@justnonamenoname  indeed, all our font rendering is done by Chromium, and they have their own implementation (doesn't use the OS font APIs AFAIK). Please search for an existing / create an issue against Chromium at https://bugs.chromium.org/p/chromium/issues/list and link to it here.

**Comment by justnonamenoname** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=663706

**Comment by justnonamenoname** [comment]
In chrome & opera this fix problem, but in vs 400 don't work
font-weight: 400;

**Comment by alexandrudima** [comment]
@justnonamenoname Thank you. VS Code is currently on Chromium 52. It is possible that the Chrome or Opera versions you are trying on are using a newer Chromium version. Once we update to a newer Electron version, we will get a newer Chromium version thus bringing the same behaviour

**Comment by balupton** [comment]
In atom I found these styles help a lot, trying to figure out a way to apply it to VS Code as in comparison to Atom (that has these styles applied) the font rendering for `Monoid Retina` is blurry:

``` css
// make text look better
.platform-darwin .workspace  {
	-webkit-font-smoothing: none;
	-webkit-font-smoothing: antialiased;
	-webkit-font-smoothing: subpixel-antialiased;
	// -webkit-text-stroke: 0.015em;
	text-rendering: auto;
	text-rendering: optimizeSpeed;
	text-rendering: optimizeLegibility;
	text-rendering: geometricPrecision;
}
```
