### ISSUE TITLE
Bug in parsing embedded language

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#15289]
- VSCode Version: 1.8 Insider

I'm working on a Vue extension: https://github.com/octref/vetur

For this code:

```vue
<div v-test="(a == b) ? x : y"></div>
```

I'm using this rule:

```yaml
  vue-directives:
    name: meta.directive.vue
    begin: (?:\b(v-)|(:|@))([a-zA-Z\-]+)(?:\:([a-zA-Z\-]+))?(?:\.([a-zA-Z\-]+))*\s*(=)
    end: (?<='|")
    captures:
      '1': {name: entity.other.attribute-name.html}
      '2': {name: punctuation.separator.key-value.html}
      '3': {name: entity.other.attribute-name.html}
      '4': {name: entity.other.attribute-name.html}
      '5': {name: entity.other.attribute-name.html}
      '6': {name: punctuation.separator.key-value.html}
    patterns:
    - name: source.directive.vue
      begin: '"'
      beginCaptures:
        '0': {name: punctuation.definition.string.begin.html}
      end: '"'
      endCaptures:
        '0': {name: punctuation.definition.string.end.html}
      patterns:
      - include: source.js
    - name: source.directive.vue
      begin: ''''
      beginCaptures:
        '0': {name: punctuation.definition.string.begin.html}
      end: ''''
      endCaptures:
        '0': {name: punctuation.definition.string.end.html}
      patterns:
      - include: source.js
```

I'd expect only `(a == b) ? x : y` get tokenized by the embedded js rule.
However, VSCode marked the last double quote as double quotes in js and continued to parse the rest as string.

![image](https://cloud.githubusercontent.com/assets/4033249/20171271/beeba0e6-a6e4-11e6-9e1a-8d43a7342a2d.png)

Sublime:

![image](https://cloud.githubusercontent.com/assets/4033249/20171722/d9d9fdce-a6e6-11e6-8016-31257d879c1a.png)
