### ISSUE TITLE
[scss]  support @at-root in @media

### ISSUE THREAD

**Issue by rehberbey** [microsoft/vscode#153202]
Issue Type: <b>Bug</b>

I was learning to write SCSS from SCSS's original site. I came across an example and wanted to try it. Oddly enough, VSCode was throwing an error, although there was no problem compiling to CSS.

```scss
@media print {
    .page {
        width: 8in;

        // BUG: There is an error in the open parenthesis.
        @at-root (without: media) {
        //       ^? { expectedscss(css-lcurlyexpected)
            color: #111;
        }
    }
}
```

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
