### ISSUE TITLE
Add official support for UI customizations and overrides with user provided CSS

### ISSUE THREAD

**Issue by suspectinside** [microsoft/vscode#154308]
i'd like to propose new simple feature that will give ability to add user customizations to the vscode UI in a simple and quick way.

new option in settings.json named smth like "userStyles":

```css
{
   "userStyles": "my-local-styles.css"
}
```

vscode will read this setting, resolve and load this css-file (relative to **~/.config/Code/User** for example or using full path) with user overrides and apply it after the main stylesheet (workbench.desktop.main.css)

for now, just for a simple modification, smth like:

```css
.monaco-hover-content {
    font-size: 0.95rem !important;
    font-family: "Open Sans";
    line-height: 1.8 !important;
    max-width: 36vw !important;
    max-height: 50vh !important;
    overflow-y: auto;
}
.monaco-hover-content h2 {
    font-size: 1.2rem !important;
    font-family: "JetBrains Mono";
}

.suggest-details-container p, .suggest-details-container code {
    font-size: .8rem !important;
    font-family: "Open Sans" !important;
}
```

i have to install new plugins (like Monkey Patch & Customize UI) that require special security changes or patch main stylesheet... this is very dirty and heavy changes just for such simple thin like to add a bit of user defined CSS to customize vscode UI for a little. Much better and simpler it would be done just to allow to add custom css to a user providing path to his own custom stylesheet in a way above mentioned.
