### ISSUE TITLE
[Themes] When my OS is dark mode, but when I switch VSCode to light mode for testing the CSS, Markdown Preview still is dark

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/vscode#154400]
Does this issue occur when all extensions are disabled?

Yes

- Version: 1.69.0
- OS Version: Windows_NT x64 10.0.19044

1. Keep your OS with dark mode.
2. Keep your VSCode with light theme.
3. Write small CSS:

   ```css
   body
   {
     color: black;
     background-color: white;
   }

   @media (prefers-color-scheme: dark)
   {
     body
     {
       color: white;
       background-color: black;
     }
   }
   ```

4. Write a simple Markdown file.
5. Add `"markdown.styles": [ "style.css" ]`.
6. Run Markdown Preview.
7. See how the preview is still dark, because VSCode understands that OS is dark, but doesn't understand that it itself is light, then set `(prefers-color-scheme: dark)` from that `style.css` file. 

I also tried to apply the settings. Observe the first two lines. 

```json
{
    "window.autoDetectColorScheme": false,
    "window.autoDetectHighContrast": false,
    "workbench.colorTheme": "Prismatic Light",
    "workbench.preferredDarkColorTheme": "Prismatic Dark",
    "workbench.preferredHighContrastColorTheme": "Prismatic Dark",
    "workbench.preferredLightColorTheme": "Prismatic Light",
}
```

But the Markdown preview mode is still dark. 

## Update

I upgraded to 1.69, but the issue remains the same.
