### ISSUE TITLE
Allow to mount workspace to sidecar containers in docker-compose ( using volumes )

### ISSUE THREAD

**Issue by ThePlenkov** [microsoft/vscode#156979]
Hi! 

I have a very simple example which doesn't work:

```
version: '3'

services:
  nginx:
    image: nginx:latest            
    volumes:
      - ..:/workspace:cached      
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached      
    
    command: sleep infinity 
```
 and devcontiner is like this:
```
	"name": "Node.js & TypeScript",	
	"dockerComposeFile": "./docker-compose.yml",
	"service": "devcontainer",	
	"workspaceFolder": "/workspace",
	"shutdownAction": "stopCompose",
```

So in case if I clone such a project into a docker volume - I have /workspace files only in a main devcontainer and not in the side car.

Well - it may be limitations of docker compose itself - but there is a solution for this. In v2 it was possible to use volumes_from.  But in v3 the solution is different: https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference

So if we define workspace as a new external volume in the compose - we can reference to it in all services.

However as I understand VS Code doesn't know yet how to create such compose installations with an external volume.

As a proposal. VS code can generate a new compose file with an external volume declared ( because the name is dynamic and only VS-code knows it )  and then to resolve relative paths in the original compose with this new workspace volume.

What do you think about this proposal? Thanks!
