### ISSUE TITLE
[scss] Range syntax support

### ISSUE THREAD

**Issue by rehberbey** [microsoft/vscode#160026]
https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#syntax_improvements_in_level_4

```scss
body {
    background-color: yellow;

    @media (400px <= width <= 800px) {
        //        ^? operator expectedscss(css-operatorexpected)
        background-color: red;
    }
}
```
