### ISSUE TITLE
.css flie property's not showing currectly.

### ISSUE THREAD

**Issue by akashrh9900** [microsoft/vscode#160598]
![image](https://user-images.githubusercontent.com/73683751/189472890-50302839-6949-4b53-bdfe-78fe3fa2f901.png)
.maindiv
{
expexting:-  text-align : center;
showing:-    text-align : after
                                      before
                                    : hover ext........
}

**Comment by rehberbey** [comment]
@akashrh9900 Dude, there's a red line where there are mistakes. If you saw the text **div** above the `#text_div1` selector, there is a missing expression there.

```css
.foo {
    align-items: center;
    justify-content: space-between;
    fit /* here it is */
}

#text_div1 {
    text-align: center;
}
```
