### ISSUE TITLE
Typing should do the same for all cursors

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#16060]
- VSCode Version: 1.8insider
- OS Version: Windows 10

Steps to Reproduce:

1. Write this file:
```css
.a {
  background: linear-gradient(red, blue 10%, green 50%)
}
```
2. Select the three colors using multiple cursors:
```css
.a {
  background: linear-gradient(|red, |blue 10%, |green 50%)
}
```
3. Now press <kbd>Backspace</kbd> to delete the three colors, and then type <kbd>(</kbd>. The first parenthesis doesn't have a closing pair.
```css
.a {
  background: linear-gradient((, () 10%, () 50%)
}
```
