### ISSUE TITLE
Expose parts DidClose/DidOpen events (No "Stackoverflow" answer found)

### ISSUE THREAD

**Issue by nicolasmol** [microsoft/vscode#161318]
Hi

Trying to implement improve an existing extension*: auto-closing of panel/sidebar when the cursor moves into the editor. The existing one did not have toggle buttons in the status bar to pin/unpin the panel/sidebar and I improved the auto-closing by using a generic Hover provider. 

But a problem remains. 

As you can see in this demo, there is no way to know when the user closes Sidebar/Panel by another way than clicking on the buttons added  in the sidebar by the extension (e.g. clicking in X in the panel), which can't update consequently the look and command attached to them. Can't you add or is there somewhere a way to get notified by those closing/opening events ?

![Peek 20-09-2022 13-49](https://user-images.githubusercontent.com/61077647/191278232-d064e722-e00a-4405-a2a4-f3fc7cf5e37d.gif)

Note: in this demo some cool and simple CSS updates that could be options by default:
```css
.sidebar, .panel {
    opacity: 0.5;
    transition: opacity 4s ease;
    transition-delay: 1s;
}
.sidebar:hover, .panel:hover {
    opacity: 1;
    transition: opacity 0.25s ease;
    transition-delay: 0s;
} 
```

*https://marketplace.visualstudio.com/items?itemName=sirmspencer.vscode-autohide
