### ISSUE TITLE
Extension Disable button does not have border radius on the right side

### ISSUE THREAD

**Issue by KunalTanwar** [microsoft/vscode#163864]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.72.2
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Open VS Code
2. Open any Installed Extension Page
3. See the `Disable Button`
4. You will notice `border-top-right-radius` and `border-bottom-right-radius` is set to `0` (problem was not present in the previous version)

<img width="1920" alt="P1" src="https://user-images.githubusercontent.com/77537933/196233685-5617c437-75bc-4bbc-a660-0f1c71029ae7.png">

Didn't happening with any other button

<img width="1920" alt="P2" src="https://user-images.githubusercontent.com/77537933/196234310-59221392-6d57-47e7-8080-4a9db20f4730.png">

if you open developer tools you will see

```css
.extension-editor>
.header>.details>
.actions-status-container>
.monaco-action-bar>
.actions-container>
.action-item.action-dropdown-item>
.extension-action.label {
  border-radius: 2px 0 0 2px;
}
```
I don't know why is it necessary!?

Also see the **Uninstall** Button looking weird after recent update.
