### ISSUE TITLE
VSCode becomes laggy after using it for some time (macOS Ventura)

### ISSUE THREAD

**Issue by franktzheng** [microsoft/vscode#165016]
Type: <b>Performance Issue</b>

Hi! I upgraded to the macOS Ventura beta a few months ago (which was probably a mistake), and I've had problems with VSCode being laggy ever since. I primarily use VSCode to compile LaTeX, but I've run into this issue while using it with TypeScript before (so it doesn't seem to be related to a particular extension). The problem I'm experiencing is similar to what might happen if there is a memory leak. When I first open the app, everything is fine, and I experience no lag whatsoever. However, after writing code for maybe 15-30 minutes, I typing and highlighting code becomes pretty laggy. If I restart the application (quit and reopen), things return to normal. I'm sorry I can't provide much more information, and I doubt I'd be able to reproduce this problem on someone else's computer.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:30.254Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.50GB free)|
|Process Argv|--crash-reporter-id 919a54c2-c935-41b4-956b-39224562195e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
  102	   164	 21312	code main
    2	    66	 21316	   gpu-process
    0	    16	 21318	   utility-network-service
    0	   295	 21319	   window (hw2.tex — math-215a)
    0	    98	 21326	   extensionHost
    0	    82	 21337	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/frankzheng/.vscode/extensions/james-yu.latex-workshop-8.29.0/out/src/components/parser/syntax_worker.js
    0	    33	 21338	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/frankzheng/.vscode/extensions/james-yu.latex-workshop-8.29.0/out/src/providers/preview/mathjaxpool_worker.js
    0	   115	 21328	   shared-process
    0	    33	 21329	     ptyHost
    0	     0	 21349	       /bin/zsh -il
    0	    33	 21339	     fileWatcher
    0	     0	 29166	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    49	 21342	   window (undefined)
    0	   213	 21345	   window (undefined)
   10	    66	 29163	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (hw2.tex — math-215a)
|    Folder (math-215a): 20 files
|      File types: aux(2) fdb_latexmk(2) fls(2) log(2) out(2) pdf(2) gz(2)
|                  tex(2) sty(2) DS_Store(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.4.0
prettier-vscode|esb|9.9.0
reasonml|fre|1.0.38
latex-workshop|Jam|8.29.0
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.40
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
cpptools|ms-|1.12.4
material-icon-theme|PKi|4.21.0
intellicode-api-usage-examples|Vis|0.2.6
material-theme|zhu|3.15.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by LukeForeverYoung** [comment]
I met the similar problem. I notice there several processes called "Code Helper" cost up to 99% CPU. Does this phenomenon happen in your machine? btw, i'm using mac Monterey and the version of vscode is 1.72.

**Comment by p-iknow** [comment]
I met the similar problem. Too. 
version: Version: 1.72.2

**Comment by xavierdonnellon** [comment]
Me too. It’s ridiculously slow, almost unusable suddenly. I can’t even type a line of code in real time, it falls below.

 I see loads of Code Helper processes (see attachment), I don’t know if this is normal.

![image](https://user-images.githubusercontent.com/74732530/199825168-79553580-7286-42d8-941e-abd641019e7d.jpg)

**Comment by jonny-harte** [comment]
Similar issue for me. VS Code (1.73.0) is noticeably slower and has crashed several times since upgrading to MacOS Ventura (not beta).

**Comment by rzhao271** [comment]
Does disabling the `extensions.experimental.useUtilityProcess` setting help?

**Comment by xavierdonnellon** [comment]
It is already disabled.

**Comment by NeitoFR** [comment]
Same behaviour 1.73 on Ventura 13.0. Terminal really laggy

**Comment by NeitoFR** [comment]
Same behaviour here on 1.73 (Ventura 13.0). Example : pwd output instantly but it takes more than 10 second to get control back on terminal

**Comment by naivefun** [comment]
Same here. Updated to Ventura and suddenly everything becomes slow. The prettier format is particularly painful.

**Comment by moffatman** [comment]
I have a profile example here, what's interesting is that during profiling it becomes a lot more responsive.
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/789275/202017111-00983f54-868b-402e-869d-6382221de5b4.png">

**Comment by LukeForeverYoung** [comment]
By updating the extension Pylance to preview version, the laggy issue seems to have disappeared. But I am not so sure that the extension causes the issue.

**Comment by xavierdonnellon** [comment]
This definitely needs to be addressed. I have to restart VS Code every few minutes.

**Comment by deepak1556** [comment]
For those still facing the issue, can you provide the following profiles when the lag happens.

1) Take a sample of the `Code` process from the OS activity monitor `Sample process` menu action.
2) Open developer tools inside VSCode using `Developer: Toggle Developer Tools` command and from the `performance` tab record a profile for few seconds and perform actions that would demonstrate the lag.

**Comment by moffatman** [comment]
I see this in Chrome itself as well recently. So it may not be VSCode's problem.
[Sample of Code.txt](https://github.com/microsoft/vscode/files/10063389/Sample.of.Code.txt)
https://files.catbox.moe/gfld8x.json

**Comment by adrihle** [comment]
The same happen to me for a v1.73.1 and Ventura 13.0.1

**Comment by xavierdonnellon** [comment]
This is still a big problem!

Here is the Activity Monitor Sample Process: 
[Code sample.txt](https://github.com/microsoft/vscode/files/10144785/Code.sample.txt)

Here is my Developer tools profile: 
[https://drive.google.com/file/d/1U1i985B2EDgb_20OPzYAh8dR-IWDPIws/view?usp=sharing](url)

CPU usage of Code jumps to 100% during autocomplete making text input ridiculously laggy (after using application for about 30 minutes).

**Comment by tony-brookes** [comment]
I also have massive issues since upgrading to Ventura.  I waiting until the official release but VSCode is basically unusable since the upgrade.  What seems to be happening is that after a while (not that long, a few minutes usually) the extension hosts simply stop responding, completely.  So no matter what you are doing, they just don't respond.  Restart a Jupyter kernel... nope, the next thing you try to do will sit there with an icon on it that looks like the Time Machine icon on the Mac, but it will do nothing, at all, even if you leave it for hours.  Want to open a file using the palette.  Nope, that will sit there searching and will never ever find the file you know is there.  Want to use a linter?  Not a prayer...

I'm not sure what is going on but there seems to be little to no consideration for Mac users on VSCode in recent releases.  Ventura betas have been out for months and bugs have been filed about performance on Ventura since that happened but no one has done anything as far as I can tell.  Trying to debug myself is a non starter because if I google for "debug vscode" I get a ton of articles on how to debug WITH vscode but now how to debug the program itself.  It's a shame because I've always really liked VS Code, but I have work to do and I can't wait for them to "get around" to looking at this, so I guess I will have to look for more a more reliable editor... Like Eclipse. :)

**Comment by moffatman** [comment]
I have this issue in Google Chrome as well. So something wrong in chromium I suppose. Restarting every 3-4 days is a reliable solution though.

**Comment by xavierdonnellon** [comment]
Yes, makes VS code truly unusable, and doesn’t seem to be getting the right attention!

**Comment by tony-brookes** [comment]
Is anyone looking at this from the VSCode team?

**Comment by TimHuynh0905** [comment]
Hi guys, I face the same issue using Vscode (the latest version) and macOS Ventura 13.0.1. vscode has become super laggy.
One thing I noticed though is when I use vscode with an external monitor, the issue disappears. Not sure if anyone noticed/ had the same problem.

**Comment by cgervais** [comment]
+1 on the issue of Code Helper (GPU) using a lot of CPU (ironic!). I've also noticed that process remains after VSCode quits running around 99% CPU utilization, so I've been manually going into Activity Monitor to kill the process. Which is fun.

I'm on Ventura 13.1 and VSCode 1.74.3 on a 14-inch MacBook Pro M1 Max 32GB RAM

**Comment by ReDrUm** [comment]
+1 I just went from MacOS `12` to `13.1` today and sadly VSCode is unexpectedly destroying my CPU and making it usable while it remains open.

```
Apple M1 Pro 32GB
Version: 1.74.3 (Universal)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
```

**Comment by lucianomasuero** [comment]
Just in case...
I fixed (or think that fixed) by disabling Plugins.
Using [Bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect#_welcome-extension-bisect)

**Comment by xavierdonnellon** [comment]
macOS Software Update fixed it for me a few days ago. Miracle

**Comment by Geokureli** [comment]
I'm having lag issues after upgrading to ventura as well, however my issue is solely typing, even moving the cursor with arrow keys is instant, so I'll get weird things where if I hit space,right,space, it will move the cursor right, and add 2 spaces.

I'm not seeing anything crazy in my activity monitor, so perhaps this is a different issue?

**Comment by tamuratak** [comment]
@Geokureli 

You should try to find extensions causing issues with [bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) at first.

**Comment by Geokureli** [comment]
> @Geokureli
> 
> You should try to find extensions causing issues with [bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) at first.

Thanks, this was the issue

**Comment by chanakya-svt** [comment]
> > You should try to find extensions causing issues with [bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) at first.
> 
> Thanks, this was the issue

@Geokureli What is the extension(s) that's causing the issue on your side?

**Comment by Geokureli** [comment]
@chanakya-svt https://marketplace.visualstudio.com/items?itemName=vshaxe.haxe-checkstyle

**Comment by chanakya-svt** [comment]
I used the bisect for the extensions and found that https://marketplace.visualstudio.com/items?itemName=MS-SarifVSCode.sarif-viewer extension is causing the issue. Once disabled VSC is good but still a bit laggy after long usage. I had to restart the VSC once a day to make it usable.

**Comment by mtrin** [comment]
My case, bisect wasn't showing any issue with extensions, vscode itself was loading really slow before extensions were loaded. I then removed the app and installed again but using brew cask and it loaded fast again.

**Comment by mariomeissner** [comment]
Started experiencing lag today. Last thing I did was adding plugins to prettier (tailwindcc sort and trivago import sort), while using the prettier extension. Typing becomes laggy.

Disabling the prettier extension removes the lag.

**Comment by ddobrinskiy** [comment]
@deepak1556 I'm also experiencing this issue, mostly when working on python repos.

Attaching the 2 files that you requested:

[Sample of Code.txt](https://github.com/microsoft/vscode/files/11499248/Sample.of.Code.txt)

[Performance Profile from developer tools](https://drive.google.com/file/d/1iiohaoHbS0wI9DQ4VCFSRjzRb4ry3SdY/view?usp=share_link)

**Comment by nneverlander** [comment]
> 

this was my issue too

**Comment by Roseidon** [comment]
Our issue was a dependency that had some performance issues, even leading to VSCode bevoming laggy.

So don't forget to upgrade your dependencies 😁

**Comment by hitzhangjie** [comment]
I'm also experiencing this issue. I'm working on a monorepo which have many protocolbuffer files and *.pb.go, and other RPC stub. After several hours, vscode becomes slow. Goland has no this problem.

**Comment by Polyhistor** [comment]
Even after bisect, still things are really slow for me.

**Comment by RhetTbull** [comment]
VSCode had been working fine on Ventura for me but recently, multiple `Code Helper (Plug In)` processes have started using 100% CPU intermittently slowing VSCode to a crawl. I assume these are related to plugins I have installed (none have changed since before the problem manifested) but it's impossible to tell if the processes are associated with a specific plugin. 

macOS: 13.5.1 (Intel)
VSCode: 
Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.6.0

<details>
<summary>Plugins installed:</summary>
<pre><code>
adpyke.vscode-sql-formatter
alefragnani.Bookmarks
amazonwebservices.aws-toolkit-vscode
ara225.regex-copy-or-cut
DavidAnson.vscode-markdownlint
donjayamanne.python-environment-manager
eamodio.gitlens
foxundermoon.shell-format
GitHub.copilot
GitHub.copilot-chat
github.vscode-github-actions
idleberg.applescript
jmviz.quote-list
MAKinteract.micro-bit-python
mechatroner.rainbow-csv
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.hexeditor
ms-vscode.live-server
ms-vscode.remote-explorer
ms-vscode.remote-server
njpwerner.autodocstring
redhat.vscode-yaml
ryanluker.vscode-coverage-gutters
sdras.night-owl
softwaredotcom.swdc-vscode
sourcery.sourcery
streetsidesoftware.code-spell-checker
tamasfe.even-better-toml
twxs.cmake
Tyriar.sort-lines
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
vscodevim.vim
</code></pre>
</details>

**Comment by dereknovak** [comment]
I've been having this issue for several days now. A couple things that I have noticed:

1. The lag seems to involve a user input. When the lag starts, I can either press a key or click mouse and it will resume.
2. When I record my VSCode session (via Start Extensions Host Profile), the problem magically disappears. Once I stop the recording, it resumes.

I am running MacOS Ventura 13.5.2 and have no VSCode extensions enabled

**Comment by jlandrum** [comment]
I'm curious if this is something within WebKit and Blink that are causing a common issue - partially due to Blink being a fork of WebKit.

I am having this issue within a Storybook instance in Safari and Edge that prior to updating, was not causing issues. Firefox doesn't have these issues. Both feel like they slow down about the same time, and terminating Safari temporarily fixes Storybook while terminating VSCode temporarily fixes the sluggishness there.

Both also get EXTREMELY slow when navigating the DOM tree, sometimes causing the window to blank and flicker.

I can't possibly think what it would be other than maybe some memory integrity features in the OS. Apple also has added quite a bit of privacy and security into Ventura but I don't expect those things to impact Blink or WebKit directly.

I also have had no luck trying to profile VSCode - doing so will cause it to lock up, and interestingly enough, the same occurs trying to do the same with Storybook. 

Could be a red herring and just a coincidence but maybe not - it's the only problem at all I've had with Ventura to date.

**Comment by clayheaton** [comment]
I never had this issue before upgrading to Sonoma. I'm on an M1 MBA with 8Gb of RAM. 

Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:57:32.750Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

![Screenshot 2023-10-14 at 5 35 58 PM](https://github.com/microsoft/vscode/assets/205364/f5727242-52c6-43b7-b664-a1c6a716d431)

[Sample of Code Helper (Renderer).txt](https://github.com/microsoft/vscode/files/12908072/Sample.of.Code.Helper.Renderer.txt)

**Comment by NRubin613** [comment]
Any updates on this issue? I'm still experiencing extreme lag after extended use.

**Comment by kirilsvoloshins** [comment]
same issue with occasional couple seconds long stutters + slow response on typing
32 GB M1 Macbook Pro
macOS: Ventura 13.5.1

![image](https://github.com/microsoft/vscode/assets/53969821/3f3a07f2-eec9-44a2-843f-c27f77e7228d)

**Comment by JBarboss** [comment]
Anyone found a solution for this?

**Comment by RhetTbull** [comment]
> Anyone found a solution for this?

@JBarboss I've been trying to switch to zed editor. It is so much faster. There are many features I miss from VSCode and I still switch back and forth a bit but I'm trying to find a way to move off VSCode as it just becomes unusably slow in macOS.

**Comment by JBarboss** [comment]
You're right. Thank you for the recommendation tho! I will give it a try. How are you managing your workflow switching between the two?

**Comment by RhetTbull** [comment]
@JBarboss I don't have much of a process other than "try to use Zed as much as possible". When I get stuck or frustrated, I open the same repo in VS Code but first try to find a solution in Zed. It's still a bit rough (especially with Python workflow which I use) but it is **so** fast and is continually improving.

**Comment by kirilsvoloshins** [comment]
> Anyone found a solution for this?

zed or neovim, I guess

**Comment by danLeBrown** [comment]
> > Anyone found a solution for this?
> 
> @JBarboss I've been trying to switch to zed editor. It is so much faster. There are many features I miss from VSCode and I still switch back and forth a bit but I'm trying to find a way to move off VSCode as it just becomes unusably slow in macOS.
> 
> 

Oh my, @JBarboss! That makes two of us. I've been switching between Zed and Vs code since last week as well.

Also looking into Neovim, since Zed lacks a lot of features that make Vs Code enjoyable/intuitive to use.

**Comment by bramiozo** [comment]
Back to Jetbrains for me personally. In the mean time, I hope VSCode can get a "streamline" option to turn off EVERYTHING except the most basic code suggestions and syntax highlighting.

**Comment by rzhao271** [comment]
Hi all, to help us have a better understanding of the issue,

1. Run the `workbench.action.openProcessExplorer` command to show the process explorer. Are there any processes that take up a lot of CPU or Memory?
2. Does [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) identify any slow extensions?

**Comment by enginocal** [comment]
Thanks @danLeBrown, bisect solved my performance problem.

**Comment by phamvant** [comment]
I'm using Brave Browser and every time VSCode feel laggy then my localhost page also frozen. I wonder if it's also browser problem

**Comment by blagoySimandov** [comment]
Been having this exact problem now for a few weeks. VSCode becomes laggy and the CPU usage jumps up to 90/95 % after a few hours of work.

**Comment by szagi3891** [comment]
I, on the other hand, have a problem switching tabs. If I switch tabs with the mouse, the response time is more than a second. if I use the keyboard to switch the active tab, the tab switches instantly. Very strangely in my case VSC behaves

**Comment by szagi3891** [comment]
I just upgraded my macos system to version 13.6.7 and VSC started working like gold.

**Comment by AzizOzenir** [comment]
Increasing VS Code's Memory Limit fixed for me   "typescript.tsserver.maxTsServerMemory": 5120,  
  "typescript.tsserver.nodePath": "/path/to/your/node"

**Comment by wuguishifu** [comment]
This is still happening to me even after trying all the solutions in this thread. In fact, VS Code becomes so slow that it's actually slower than just using Webstorm or IntelliJ. I've checked all my plugins, and I have nothing that should be causing VS Code to be slower than an actual IDE.

**Comment by jessicagohh** [comment]
VS Code gets so slow for me that I can barely scroll on files. I don't have the same issue on other open windows and tabs, just VS Code and Chrome-with-video-call. Some details that I think may have an impact?

1. The Battery menu always describes VS Code as "Using Significant Energy".
2. I'm on M3 Pro Sonoma.
3. The lag disappears when I'm not connected to my Dell D6000 DisplayLink dock.
4. The lag is still there even when only 1 external monitor is connected to the D6000.
5. I have the Snowflake official extension on VS Code on this laptop.
6. I never had this lag issue with my M2 Pro Sonoma Mac, even when connected to the D6000 + 3 external monitors, but without the Snowflake extension.

**Comment by PrajwalCRao** [comment]
@jessicagohh I had the same symptoms as you. Setting my 144 Hz capable external monitor to 60Hz resolved the issue for me.

**Comment by Artin-GH** [comment]
Opening using the command `code --disable-gpu` solves for me.
Running in M1 Macbook Air 2019.
Macos Sonoma.
`code --version`:
```
1.92.2
fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
arm64
```

Secondly, in my case the problem is there since I open it and not after minutes of working as some of you said.
VSCode is so laggy when I'm scrolling anywhere in the app and a process named `Code Helper` is using about 50 percent cpu and 400MB memory

**Comment by Jervx** [comment]
Damn, I disabled almost every extension I have, but still even writing classes in className in tsx react lags too much 😞, I even disable the suggestions but still no effect. the lightweight IDE we loved before was gone. Gonna go back with nvim or zed. I'll be back if this problem is fixed

**Comment by Jervx** [comment]
Damn, I disabled almost every extension I have, but still even writing classes in className in tsx react lags too much 😞, I even disable the suggestions but still no effect. the lightweight IDE we loved before was gone. Gonna go back with nvim or zed. I'll be back if this problem is fixed.

**Comment by ExLineP** [comment]
Same issue, after stopping every CodeHelper (with 40% CPU utilization) from the system and running VSCode again fixes the issue but don't know how long will it last,

**Comment by ZohaibAfridi565** [comment]
I just switched off all the auto updates options in system settings, now everything’s working smoothly... That’s  hilarious 😂

**Comment by maxpatiiuk** [comment]
Same issue. Detailed analysis:

VS Code is very fast after closing all instances but gradually gets slower and slower.
VS Code CPU usage is 0.3% when it's in the background but gets too 99% when I am doing something as simple as scrolling or typing.
VS Code process explorer shows 99% CPU usage is coming from `code main`
RAM usage is at 370mb with peak at 490mb.

What doesn't help:
- "Developer: Restart Extension Host"
- "Developer: Reload WIndow"
- Disconnecting external monitor
- VS Code Extension Host profile shows that this is not caused by any extension.

Possible culprits:
- I have multiple VS Code instances open at the same time most of the time. Closing all but one doesn't fix the performance issue. Closing every one of them fixes the issue only to have it gradually get slower again.
- I use one or two external monitors. Color Profile: "DELL P2222H".
- This is on a enterprise-owned laptop. It has com.crowdstrike.falcon.Agent and other spyware.

Using integrated devtools to run a performance profiler:
- While performing an action that is very slow (scrolling/typing) - sometimes character would take several seconds to appear on the screen. I don't see any task on the main threat that took more than 3ms to complete. Worker processed had even less activity than the main thread: TextMateWorker, TextEditorWorke, LanguageDetectionWorker, WorkerExtensionHost.
  - [Sample of Code.txt](https://github.com/user-attachments/files/17177157/Sample.of.Code.txt)
  - [Trace-20240928T182334.json](https://github.com/user-attachments/files/17177168/Trace-20240928T182334.json)

Issue has been happening for a while.

<details>

<summary>`code --status` while actively scrolling (98% CPU on `code main`)</summary>

```yaml
Version:          Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS Version:       Darwin arm64 23.6.0
CPUs:             Apple M1 Pro (10 x 2400)
Memory (System):  32.00GB (9.55GB free)
Load (avg):       3, 3, 3
VM:               0%
Screen Reader:    no
Process Argv:     /Users/mak13180/site/esri/arcgis-web-components --crash-reporter-id eb79c588-0746-4857-a17b-b971547fd81f
GPU Status:       2d_canvas:                              enabled
                  canvas_oop_rasterization:               enabled_on
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        enabled
                  multiple_raster_threads:                enabled_on
                  opengl:                                 enabled_on
                  rasterization:                          enabled
                  raw_draw:                               disabled_off_ok
                  skia_graphite:                          disabled_off
                  video_decode:                           enabled
                  video_encode:                           enabled
                  webgl:                                  enabled
                  webgl2:                                 enabled
                  webgpu:                                 enabled
                  webnn:                                  disabled_off

CPU %	Mem MB	   PID	Process
   98	   360	 77595	code main
    0	   131	 77598	   gpu-process
    0	    33	 77599	   utility-network-service
    0	   164	 77602	shared-process
    0	    66	 77620	ptyHost
    0	     0	  7937	     /bin/zsh -l
    0	     0	  8547	     /bin/zsh -l

Workspace Stats:
|  Window (includes.scss — calcite-design-system)
|    Folder (calcite-design-system): more than 22039 files
|      File types: json(8704) svg(3606) ts(3520) js(2959) md(162) tsx(131)
|                  scss(130) html(113) yml(26) css(22)
|      Conf files: package.json(18) github-actions(17) tsconfig.json(9)
|                  settings.json(8) launch.json(2) tasks.json(1)
|                  webpack.config.js(1)
|      Launch Configs: node(4) chrome
```

Right after restarting VS Code, the CPU usage while scrolling doesn't get above 10%.

</details>

<details>

<summary>`code --status` right after I stop scrolling (1% CPU on `code main`)</summary>

```yaml
Version:          Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS Version:       Darwin arm64 23.6.0
CPUs:             Apple M1 Pro (10 x 2400)
Memory (System):  32.00GB (9.50GB free)
Load (avg):       4, 3, 3
VM:               0%
Screen Reader:    no
Process Argv:     /Users/mak13180/site/esri/arcgis-web-components --crash-reporter-id eb79c588-0746-4857-a17b-b971547fd81f
GPU Status:       2d_canvas:                              enabled
                  canvas_oop_rasterization:               enabled_on
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        enabled
                  multiple_raster_threads:                enabled_on
                  opengl:                                 enabled_on
                  rasterization:                          enabled
                  raw_draw:                               disabled_off_ok
                  skia_graphite:                          disabled_off
                  video_decode:                           enabled
                  video_encode:                           enabled
                  webgl:                                  enabled
                  webgl2:                                 enabled
                  webgpu:                                 enabled
                  webnn:                                  disabled_off

CPU %	Mem MB	   PID	Process
    1	   360	 77595	code main
    0	   131	 77598	   gpu-process
    0	    33	 77599	   utility-network-service
    0	   164	 77602	shared-process
    0	    66	 77620	ptyHost
    0	     0	  7937	     /bin/zsh -l
    0	     0	  8547	     /bin/zsh -l

Workspace Stats:
|  Window (includes.scss — calcite-design-system)
|    Folder (calcite-design-system): more than 22039 files
|      File types: json(8704) svg(3606) ts(3520) js(2959) md(162) tsx(131)
|                  scss(130) html(113) yml(26) css(22)
|      Conf files: package.json(18) github-actions(17) tsconfig.json(9)
|                  settings.json(8) launch.json(2) tasks.json(1)
|                  webpack.config.js(1)
|      Launch Configs: node(4) chrome
```

</details>
