### ISSUE TITLE
Investigate moving away from the styler pattern

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#165478]
Having more styling be done via CSS would reduce the amount of JS code we need to ship and run. We should investigate if it is possible to achieve the same composition as we do today in JS, by using CSS variables. We should also check that this doesn't cause any performance problems and that it is idiomatic CSS
```css
/* in base widget CSS */
.monaco-inputbox {
    --monaco-inputbox-foreground: #CCCCCC;
}
.monaco-inputbox {
    position: relative;
    display: block;
    padding: 0;
    box-sizing: border-box;
    border-radius: 2px;
    /* Customizable */
    font-size: inherit;
    color: var(--monaco-inputbox-foreground)
}

/* in widget user CSS */
.findWidget .monaco-inputbox {
    --monaco-inputbox-foreground: var(--vscode-find-widget-input);
}
```
