### ISSUE TITLE
css syntax highlight is broken for @supports

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#16813]
- VSCode Version: 1.8
- OS Version: Windows 10

Steps to Reproduce:

1. Write this code:
```css
.wrapper {
  background-color: black;
}

.content {
  padding: 1rem 2rem;
  font-size: 1.2rem;
  color: darkred;
  text-align: center;
}

@supports (filter: grayscale(100%)) {
  .wrapper {
    background-color: blanchedalmond;
  }

  .content {
    filter: grayscale(100%);
  }
}
```

2. Expected: the `.wrapper` inside @supports should have the same color as other selectors.

3. 
![image](https://cloud.githubusercontent.com/assets/760112/20966520/b90e339c-bca0-11e6-9f2e-699853538d91.png)
