### ISSUE TITLE
Multi Cursor and cursorWordLeftSelect results in cursors out of sync

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#169904]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.75.0-insider (user setup)
- Commit: 6ed4d436a9b6ae131732f4e2a723868231f4473a
- Date: 2022-12-23T05:21:57.802Z
- OS Version: Windows 8.1

Steps to Reproduce:

1. Create the following CSS file
```css
.grid1 {
  display: grid;
  grid-template-columns:
    [full-start] minmax(1em, 1fr)
    [main-start] minmax(0, 40em) [main-end]
    minmax(1em, 1fr) [full-end];
}
.grid2 {
  display: grid;
  grid-template-columns:
    [full-start] minmax(1em, 1fr)
    [main-start] minmax(0, 40em) [main-end] minmax(1em, 1fr) [full-end];
}
```
2. Place Multi Cursor after all `-end]`
3. Execute command `cursorWordLeftSelect` (`Ctrl+Shift+ArrowLeft`)
4. Cursors are now out of sync
5. If you first select `]` or `d]` with `cursorLeftSelect`  (`Shift+ArrowLeft`)
6. Then execute command `cursorWordLeftSelect` (`Ctrl+Shift+ArrowLeft`)
7. Cursors are in sync

If I perform a `cursorWordLeftSelect` why is the content **right** of the `cursor.active` important?
