### ISSUE TITLE
git commit: using SCM panel makes pre-commit hook fail

### ISSUE THREAD

**Issue by senhalil** [microsoft/vscode#171721]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.3
- OS Version: Darwin arm64 22.2.0

Steps to Reproduce:

1. pre-commit hook with the following hook:
```
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: coverage run -m pytest
        language: system
        pass_filenames: false
        always_run: true
```
2. commit using SCM panel raises the following error:
```
pytest...................................................................Failed
- hook id: pytest
- exit code: 1

Executable `coverage` not found
```

The hook above passes correctly if git commit is called from the terminal (as `coverage` do exists in the active python environment). I expected this to work via SCM as well since selected Python interpreter is the correct one but it seems that git connection is not running the commands under the same environment.
