### ISSUE TITLE
Relative context path in .devcontainer/docker-compose.yml no longer working

### ISSUE THREAD

**Issue by nielsvanoosterom-varias** [microsoft/vscode#173676]
Does this issue occur when all extensions are disabled?: I require the remote extensions enabled in order to reproduce.

- VS Code Version: 1.75.0
- OS Version: macOS Ventura 13.0 (22A380) / Ubuntu 22.04 (Remote-SSH)

Steps to Reproduce:
With the following .devcontainer/docker-compose.yml file:
```
version: '3.8'

services:
  workspace:
    image: obfuscated/obfuscated-workspace:${TAG:-latest}
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      CLIENT_ENABLE_RESPONSE_GZIP: ${CLIENT_ENABLE_RESPONSE_GZIP:-1}
    extra_hosts:
      - db:127.0.0.1
      - redis:127.0.0.1
      - auth:127.0.0.1
      - server:127.0.0.1
      - client:127.0.0.1
      - portal:127.0.0.1
      - clamav:127.0.0.1
      - warehouse:127.0.0.1
      - libreoffice:127.0.0.1
      - nifi:127.0.0.1
      - rabbitmq:127.0.0.1
      - fusion-export:127.0.0.1
      - camunda:127.0.0.1
      - templates:127.0.0.1
    volumes:
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh/$SSH_KEY:/home/obfuscated/.ssh/$SSH_KEY:ro
      - ~/.ssh/$SSH_KEY.pub:/home/obfuscated/.ssh/$SSH_KEY.pub:ro
      - ../.workspace/home/obfuscated/.docker:/home/obfuscated/.docker:delegated
      - ../.workspace/mnt/.gitconfig:/mnt/.gitconfig:delegated
      - ../.workspace/usr/local/share/.config/yarn/link:/usr/local/share/.config/yarn/link:delegated
      - $WORKSPACE_SHARE:$WORKSPACE_SHARE:delegated
```

1. Remote-SSH into Ubuntu 22.04 machine.
2. Open the project folder, and click the 'reopen in dev container' button when prompted.
3. Recieve error ENOENT: no such file or directory, open '/home/obfuscated/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/Dockerfile'.

Changing build context from `.` to an absolute path fixes the issue. Relative paths in the volumes section still work as expected.
