### ISSUE TITLE
Bind IntelliSense of CSS to PostCSS 

### ISSUE THREAD

**Issue by crabicode** [Microsoft/vscode#17419]
How can I enforce the default IntelliSense of CSS to be firing for *.postcss file extensions?

I could make the syntax highlighting work but it seems that I can't longer use CSS IntelliSense.

Any suggestions?

PS: using [https://github.com/rcsole/postcss-syntax](postcss-syntax) syntax highlighting

**Comment by mrmlnc** [comment]
You can use the following settings in `Preferences -> User Settings`:

```json
{
    "files.associations": {
        "*.postcss": "css"
    }
}
```

**Comment by crabicode** [comment]
@mrmlnc nope, `*.postcss` uses nesting and other syntax-specific expressions which are not highlighted by the default css. #17344 suggests the feature so that one could include CSS Intellisense for other file extensions

**Comment by crabicode** [comment]
The highlighting will break after `$var`, $composes` and etc

```css
$var: #000;
:local(.class) {
   > .nested {
      composes: shared-class from '../file.postcss';
      color: $var;
   }
}
```
