### ISSUE TITLE
Markdown Preview text color not controlled by styles.css

### ISSUE THREAD

**Issue by cvax** [Microsoft/vscode#17567]
VS Code: 1.8.1

Why is it that the color for non-blocked text in the Markdown Preview can't be controlled by the styles.css?

This doesn't work.
```css
body {
	color: #333;
}
```
The only way I can get the color to change is through changing my VS Code color theme from dark to light. Either VS Code's color theme or UI theme is preventing the Markdown Previewer from controlling that font color via styles.css.

**Comment by mjbvz** [comment]
You need to use a more specific css rule. The default text colors come from:

```css
.vscode-light {
	color: rgb(30, 30, 30);
}

.vscode-dark {
	color: #DDD;
}

.vscode-high-contrast {
	color: white;
}
```

This allows customizing the style based on the current theme.

To use a custom color, you can either override one of these rules directly, or use a more specific rule that takes precedence over these rules. To inspect the dom and styling of the markdown preview, add the following keybinding

	{"key": "cmd+alt+i", "command": "_webview.openDevTools"}

This will allow you to see where the style is coming from and how your rules are being applied.
