### ISSUE TITLE
[icon-themes] explore using attribute selectors to allow name patterns and simplify implementation

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#177650]
We currently use css classes to match file icons to file names. 
Using [attribute selectors](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors) could simplify this and allow to support name patterns

![image](https://user-images.githubusercontent.com/6461412/226318856-3c62202e-66ff-4ec0-93bc-1e4a50902c47.png)

```css
[basename^="hello-"][ext="ts"] {
    background-color: red;
}

[basename$="Bar"][ext="ts"] {
    background-color: yellow;
}
[basename="unique-Bar"][ext="ts"] {
    background-color: green;
}
```

```html
<div basename="hello-world" ext="ts">hello-world.ts</div>
<div basename="hello-world" ext="js">hello-world.js</div>
<div basename="fooBar" ext="ts">fooBar.ts</div>
<div basename="barBar" ext="ts">barBar.ts</div>
<div basename="hello-Bar" ext="ts">hello-Bar.ts</div>
<div basename="unique-Bar" ext="ts">unique-Bar.ts</div>
```
