### ISSUE TITLE
Directory tree indent guides in File Explorer

### ISSUE THREAD

**Issue by Avol-V** [microsoft/vscode#17777]
It's hard to navigate through project with complex directory structure.

Much better to look at something like this:

```
├─ app
|  └─ main.js
├─ src
|  ├─ main.ts
|  └─ tsconfig.json
└─ package.json
```

Instead of this:

```
  app
    main.js
  src
    main.ts
    tsconfig.json
  package.json
```

**Comment by cosmoKenney** [comment]
I agree with this. I especially find that the indenting is hard to interpret. And is even worse when file icons are enabled in explorer.

**Comment by misantronic** [comment]
I also agree! +1

**Comment by Aides359** [comment]
Another thing that would be nice in that regard is customizing the indent distance of the next level of hierarchy.
While I would also love some guidelines, I think having i.e. twice the distance and thus having clearer separation would already help a lot.

**Comment by cosmoKenney** [comment]
@Aides359  I agree. Everyone's eyes are different. Just look at tabs. Some people like 2 space tabs in their code. Some like 8. Other 4. 

I'm a little dyslexic, so I really have a hard time with the indention in VS Code, 

Though it does seem to have gotten a little better. But it's still bad on my laptop screen, for instance, whereas on my large monitors at work, it's more noticeably indented.

**Comment by chentel** [comment]
Yes! Please tree lines as an option. It'd be especially helpful when editor is open at a far corner on a large monitor.

Tying the toggle to mouse-over in Explorer Pane would help in keeping the clean look.

**Comment by edmundo096** [comment]
Really useful on big projects.
Any update on this? Or where I could start looking in the source?

**Comment by cosmoKenney** [comment]
@edmundo096 this was closed as a dup of #21295, which is also closed. So I guess this is going nowhere.

**Comment by roblourens** [comment]
@cosmoKenney This issue isn't closed...

**Comment by edmundo096** [comment]
@cosmoKenney, no, this is the original post and it isn't resolved. #21295 was the duplicate.
I couldn't find a configuration to enable this indentation guides on the Sidebar Explorer yet.

**Comment by pietrasiak** [comment]
![image](https://user-images.githubusercontent.com/7311462/27506535-e5bc7042-58b9-11e7-942c-a592295c143b.png)

So yup... my eyes are bleeding. I'm like `what is index.js of Expression folder... I know you're there!`. 

I think it should have quite high priority. Modern web apps quite often have deep nested files structure. see [this example](https://medium.com/@alexmngn/how-to-better-organize-your-react-applications-2fd3ea1920f1)

**Comment by chentel** [comment]
![27506535-e5bc7042-58b9-11e7-942c-a592295c143b](https://user-images.githubusercontent.com/382595/27973690-cbd00f4e-630f-11e7-8be2-cc7759817e18.png)

and here's the approximate look without Magnifier. not so bad... if you've got the vision of a fighter pilot

**Comment by goudcode** [comment]
I would like this as well, it's quite easy to get lost in larger projects.

**Comment by jens1o** [comment]
I also agree this should be considered...

**Comment by Winston-Guess** [comment]
I agree! I've been trying to look for a setting or extension that does this over the last two days but nothing T_T. I really struggle to navigate using the explorer (which is necessary when you're navigating a new project..).

**Comment by purefan** [comment]
DO we have any indication if this is in the roadmap?

**Comment by exectails** [comment]
+1

**Comment by bclarkbasly** [comment]
+1 this is an enormous pain for me on my large monitor.

**Comment by Livshitz** [comment]
++1

**Comment by kylehorn** [comment]
+1

**Comment by phamduong** [comment]
+1

**Comment by petyrek** [comment]
+1 Microsoft please!

**Comment by jakewtaylor** [comment]
+1 for this.

In the meantime, I've found a bit of a hack to solve it for now:

Find your VSCode install (mine was `C:/Program Files/Microsoft VS Code`) and go to `resources/app/out/vs/workbench` and open `workbench.main.css`.

Add these lines to the end of the file:
```CSS
.monaco-tree-row[aria-level="1"]  { padding-left:   0px !important; }
.monaco-tree-row[aria-level="2"]  { padding-left:  20px !important; }
.monaco-tree-row[aria-level="3"]  { padding-left:  40px !important; }
.monaco-tree-row[aria-level="4"]  { padding-left:  60px !important; }
.monaco-tree-row[aria-level="5"]  { padding-left:  80px !important; }
.monaco-tree-row[aria-level="6"]  { padding-left: 100px !important; }
.monaco-tree-row[aria-level="7"]  { padding-left: 120px !important; }
.monaco-tree-row[aria-level="8"]  { padding-left: 140px !important; }
.monaco-tree-row[aria-level="9"]  { padding-left: 160px !important; }
.monaco-tree-row[aria-level="10"] { padding-left: 180px !important; }
.monaco-tree-row[aria-level="11"] { padding-left: 200px !important; }
.monaco-tree-row[aria-level="12"] { padding-left: 220px !important; }
.monaco-tree-row[aria-level="13"] { padding-left: 240px !important; }
.monaco-tree-row[aria-level="14"] { padding-left: 260px !important; }
.monaco-tree-row[aria-level="15"] { padding-left: 280px !important; }
```

Done!

That code sets the padding to 20px extra per indent-level, but of course you can bump that up as much as you want, just change the values. I've also only gone 15 levels deep, which you can expand too, but if your project is deeper than 15 levels, I'd suggest you re-evaluate your directory structure. ;)
