### ISSUE TITLE
[less] mixins ") expected" errors

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#1778]
When editing a **.less** file unexpected errors show when working with mixins. These errors show when using a mixin with a named parameter.

**VS Code version:**
0.10.6

**Code:**
```less
.mixin(@a, @b) {
  content: @a + @b;
}

.test {
  .mixin(@b: 1);
}
```

![image](https://cloud.githubusercontent.com/assets/7034281/12102589/efe3c584-b34c-11e5-96b4-1da25c640284.png)
