### ISSUE TITLE
Code blocks in Markdown preview don't use textCodeBlock.background

### ISSUE THREAD

**Issue by starball5** [microsoft/vscode#179219]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0
- OS Version: Ubuntu 22.04.1

Steps to Reproduce:

1. Put the following in settings.json:
   ```jsonc
   "workbench.colorCustomizations": {
       "textCodeBlock.background": "#ff0000" // red
   },
   ```
2. Open an extension that has a code block in its readme and observe that the code block is not rendered with a red background.
3. Create a Markdown file and write a code block and open the Markdown preview. Observe that the code block is not rendered with a red background.

It sounds like this was part of a feature-request in #26298, which was closed as completed by https://github.com/microsoft/vscode/commit/c9f10706eff2d9ceb73ba0f7e5f18cb4f8a63d80. Possible regression? (I'm not sure. I never used this colour customization point before)

Related question on Stack Overflow: https://stackoverflow.com/q/75934711/11107541

I see in my VS Code that `<pre>` elements have

```css
.vscode-dark pre {
    background-color: rgba(10, 10, 10, 0.4);
}
```

I assume this should be changed to something like

```css
.vscode-dark pre {
    background-color: var(--vscode-textCodeBlock-background, rgba(10, 10, 10, 0.4));
}
```

(using [`var()`'s fallback syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/var#syntax))
