### ISSUE TITLE
Fonts are too thin on Ubuntu 16.10

### ISSUE THREAD

**Issue by sryze** [Microsoft/vscode#17963]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.10 amd64

I use VS Code on Windows, Mac and since recently Linux, and text looks much thinner on Linux making it harder to read. Here is a screenshot:

![vscode-fonts](https://cloud.githubusercontent.com/assets/4525736/21577973/542305f2-cfa1-11e6-8e73-821909abeb4b.png)

Font settings:
```
    "editor.fontSize": 14,
    "editor.fontFamily": "Source Code Pro",
    "window.zoomLevel": 0
```

System font settings:
- Antialiasing: RGBA
- Hinting: Slight
- Text scaling factor: 1.00

I've tried various combinations of antialiasing and hinting settings but they all look as bad or worse.

**Comment by sryze** [comment]
For what it's worth, Atom has the same problem but I was able to overcome it by adding the following to my stylesheet (found somewhere on the internet):

```css
body, .editor {
  -webkit-text-stroke: .03em;
}
```

This makes text a little bit thicker.

**Comment by FabianLauer** [comment]
Agreed, specifically in dark color themes fonts can be hard to read on Ubuntu. I'm using this as a remedy:

```css
body {
    -webkit-text-stroke: 0.2px;
    text-shadow: 0 0 0.05px;
}
```

How about a new user setting to make text appear "bolder"?
