### ISSUE TITLE
Ghost text background is not covering the whole line highlight height

### ISSUE THREAD

**Issue by pouyakary** [microsoft/vscode#179639]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.1
- OS Version: 13.1 (22C65)

Steps to Reproduce:

The ghost text can have a background color. However when you apply this background color it does not match the current line height. this is an example:

<img width="563" alt="Screenshot 1402-01-21 at 10 53 54 PM" src="https://user-images.githubusercontent.com/2157285/231002160-9cd77fbd-a19d-4c82-ac09-722ce00bc57e.png">

As you can see there are red lines above and below the ghost text. this is very annoying in real use cases. 

<img width="500" alt="Screenshot 1402-01-21 at 10 54 33 PM" src="https://user-images.githubusercontent.com/2157285/231002297-7ad7ab5d-9210-42f0-b3a1-2bdc259effbd.png">

If you look closely it is also rendered above the indentation lines which is even more annoying.

---

I actually want to fix the problem. And so I tried to fix the problem and so I looked for the source code. in `src/vs/editor/contrib/inlineCompletions/browser/ghostText.css` there is a definition that has the rendering properties:

```css
.monaco-editor .ghost-text-decoration,
.monaco-editor .ghost-text-decoration-preview,
.monaco-editor .suggest-preview-text .ghost-text {
	color: var(--vscode-editorGhostText-foreground) !important;
	background-color: var(--vscode-editorGhostText-background);
	border: 1px solid var(--vscode-editorGhostText-border);
}
```

And I think adding a height property here could have fixed the problem. However I have no idea how to parametrically pass the height to the class. I have read the `src/vs/editor/contrib/inlineCompletions/browser/ghostTextWidget.ts` and it seems `IModelDeltaDecoration` only works with class names.

If you can give me a clue how to pass the line height to the class (if there exists a variable or if there is a way for me to create one) that could be cool.
