### ISSUE TITLE
Webview context menu doesn't look like the other context menus

### ISSUE THREAD

**Issue by r3m0t** [microsoft/vscode#181432]
Does this issue occur when all extensions are disabled?: N/a

- VS Code Version: Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.77.3 Chrome/102.0.5005.196 Electron/19.1.11 Safari/537.36
- OS Version: 

Steps to Reproduce:

1. Right click a file in the Explorer. The background color of the row changes from blue to grey. 
2. Press Esc to close the context menu. The background color changes back.
3. This is not possible to emulate with an extension using a webview context menu.

Fixed by my PR

**Comment by VSCodeTriageBot** [comment]
This bug has been fixed in the latest release of [VS Code Insiders](https://code.visualstudio.com/insiders/)!

@r3m0t, you can help us out by commenting `/verified` if things are now working as expected.

If things still don't seem right, please ensure you're on version 45b31e9a872da8cc3cc8fff41c1eeb2063be04b7 of Insiders (today's or later - you can use `Help: About` in the command palette to check), and leave a comment letting us know what isn't working as expected.

Happy Coding!

**Comment by hbons** [comment]
I'll verify this.

**Comment by hbons** [comment]
<img width="320" alt="image" src="https://github.com/microsoft/vscode/assets/103326/c6c08923-c87e-4d7d-a78d-ae63f06bceac">

<img width="334" alt="image" src="https://github.com/microsoft/vscode/assets/103326/95f163ca-4692-487a-82f8-11579372cea8">

I can confirm that on insiders.vscode.dev that there is a style change when right-clicking a file in the Explorer. But it's not the one described, the text colour changes slightly (this may be a theme difference).

What's an extension that uses a file list in a web view that I can verify?

**Comment by alexr00** [comment]
I think any webview context menu should work for this, not necessarily a file list.

**Comment by r3m0t** [comment]
They would need to add a CSS rule with the new class name to make an actual change in visual appearance. You can verify the class is applied on the body element using the Webview Developer Tools.

**Comment by r3m0t** [comment]
https://github.com/gitkraken/vscode-gitlens/blob/075c58b29f2c0296dc1a38f9125f04ce831b76b0/src/webviews/apps/shared/components/list/list-item.ts#L93 this could probably be edited

**Comment by r3m0t** [comment]
Here's a snippet from my project, the `:focus` selector doesn't work while the context menu is up, so I repeat the same rules with `.vscode-context-menu`

```css

/* https://github.com/microsoft/vscode/blob/1.77.0/src/vs/base/browser/ui/list/listWidget.ts#L871 */
.list-rows:focus .list-row.focused.selected {
    outline: 1px solid
        var(--vscode-list-focusAndSelectionOutline, var(--vscode-contrastActiveBorder, var(--vscode-list-focusOutline)));
    outline-offset: -1px;
}

.list-rows:focus .list-row.focused {
    outline: 1px solid var(--vscode-list-focusOutline);
    outline-offset: -1px;
}

/** https://github.com/microsoft/vscode/blob/1.77.0/src/vs/base/browser/ui/list/listWidget.ts#L880 */
.vscode-context-menu-visible .list-rows .list-row.focused,
.vscode-context-menu-visible .list-rows .list-row.focused.selected {
    outline: 1px solid var(--vscode-list-focusOutline);
    outline-offset: -1px;
}

.list-rows.context-menu-visible .list-row.focused,
.list-rows.context-menu-visible .list-row.focused.selected {
    outline: 1px solid var(--vscode-list-focusOutline);
    outline-offset: -1px;
}

```
