### ISSUE TITLE
[scss] using round brackets cause highlight errors in next values.

### ISSUE THREAD

**Issue by VitorLuizC** [Microsoft/vscode#18319]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.2|
|EditorConfig|EditorConfig|0.3.4|
|vscode-todo|MattiasPernhult|0.8.0|
|typescript-javascript-grammar|ms-vscode|0.0.14|
|vscode-icons|robertohuertasm|6.0.0|
|vscode-open|sandcastle|0.0.2|
|vscode-spotify|shyykoserhiy|1.0.0|

---

![image](https://cloud.githubusercontent.com/assets/9027363/21769809/ae392022-d667-11e6-9343-7a47c9e37277.png)

Steps to Reproduce:

1. Type some property with a round brackets and other values

**Comment by aeschli** [comment]
@VitorLuizC Can you paste the scss snippet to reproduce?

**Comment by VitorLuizC** [comment]
@aeschli 
```scss
$bar: 12px;

.foo {
  margin: ($bar * .8) 0 ($bar * .8) ($bar * 2);
  padding: (10px * 1.2) (10px * 1.2) 0;
  border: ($bar * 3) solid black;
  box-shadow: 0 0 (10px) #000;
}
```
