### ISSUE TITLE
The edit-file-right-before-you-save feature is too magical

### ISSUE THREAD

**Issue by fulldecent** [microsoft/vscode#185959]
Type: <b>Bug</b>

1. Create an HTML file with this content:

```
---
layout: header-footer
description: ACLS Training Center. Recertification and Certification Courses.
title: ACLS Training Center | acls.net
required_reviews: none
last_updated: 2023-04-19
google_optimize: GTM-W52TLB3
alternate_langs:
  - lang: fr-CA
    href: https://aclscertification.ca/fr/inscrivezvous
  - lang: en-US
    href: https://www.acls.net/signup
  - lang: en-US
    href: https://www.acls.net/signup-home
---
```

2. Install the 30+ extensions I installed as documented above.

3. Press save

4. The YAML is broken by removing the spaces (breaks the subordination of `lang` entries inside `alternate_langs` // THIS STEP IS &&&EXPECTED&&& AND IS NOT A PROBLEM IN THIS ISSUE

5. Curse at computer because it is impossible to save this file without errors unless you leave VS Code and use vim.  // THIS STEP IS &&&EXPECTED&&& AND IS NOT A PROBLEM IN THIS ISSUE

6. Look on the screen for some visual indication of WHICH extension or feature is responsible for editing your file when you save it.

EXPECTED OUTCOME:

Some part of the status bar or some toast visually tells you (yes, on every save) something like "Extension XYZ applied edits during your save."

ACTUAL 

There is no visual indication and it is impossible to diagnose this problem.

VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.116
unique-lines|bib|1.0.0
vscode-intelephense-client|bme|1.9.5
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.4.2
gitlens|eam|14.0.1
vscode-html-css|ecm|1.13.1
codespaces|Git|1.14.8
copilot|Git|1.92.177
vscode-github-actions|git|0.25.8
vscode-test-explorer|hbe|2.21.1
vscode-docker|ms-|1.25.1
remote-containers|ms-|0.295.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.0
sublime-keybindings|ms-|4.0.10
test-adapter-converter|ms-|0.1.8
sqltools|mtx|0.28.0
sqltools-driver-mysql|mtx|0.6.0
vscode-taskexplorer|spm|2.13.2
code-spell-checker|str|2.20.5
unique-window-colors|stu|1.0.51
html-css-class-completion|Zig|1.20.0

</details>
