### ISSUE TITLE
Pull new CSS grammar for colors, lengths, etc.

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#187012]
This issue will describe the changes pulled in by PRs on `vscode-css` (https://github.com/microsoft/vscode-css/pull/4, https://github.com/microsoft/vscode-css/pull/5, https://github.com/microsoft/vscode-css/pull/6, https://github.com/microsoft/vscode-css/pull/12). This updates highlighting for colors (gradients and `color-mix` function), length units, math functions, and adding the `text-decoration-thickness` property.

To verify that this is working, paste this string into a css file. 
```css
body {
    background-image: 
      linear-gradient(
        to right in oklch longer hue, 
        red 0% 100%
      )
    ;
  }

h1 {
    font-size: 10vb;
    text-decoration-line: underline;
    text-decoration-thickness: 30px;
}

.shape {
    width: calc(10px * pow(5, 2));
    height: 100px;
    background-color:#fff;
}
```

If you're using the default dark theme, then it should look like this. 
<img width="236" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/803e2d51-7f36-4536-8b65-6526766b0f46">

In particular make sure that that:
- `hue` is the same color as `longer` and `oklch`. 
- `10vb` is all one color, like how you would see `10px`.
- `text-decoration-thickness` is the same color as the other properties
- `pow()` is formatted as a css function like `calc()` is
