### ISSUE TITLE
Class names in .scss files does not show on hover when @container query has a variable

### ISSUE THREAD

**Issue by youurt** [microsoft/vscode#187254]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.80.0
- OS Version: macOS 13.1 (22C65)

Steps to Reproduce:

1.  Create a .scss file with.
```scss
$some-variable: 100px;

.some-class {

  &__container {
    container: some-name / inline-size;
  }

  &__foo {

    @container some-name (max-width:  #{$some-variable}) {
      padding-top: 1rem;
    }
  }

  &__bar {
    display: block;
  }
}
```
2.  Hover on the "bar" class. Now you will not see the concatenated class name `some-class__bar`.
3. Now replace  the `$some-variable` from the code above with `100px`.
4. Hover over the "bar" class. Now you will see the expected behaviour.

<img width="555" alt="Screenshot 2023-07-07 at 12 00 00" src="https://github.com/microsoft/vscode/assets/39196535/14e917fd-c927-4d6e-87ea-9429f453b05f">

<img width="389" alt="Screenshot 2023-07-07 at 12 00 17" src="https://github.com/microsoft/vscode/assets/39196535/24b174f5-ce8b-4961-b988-5d08eb8d4f97">
