### ISSUE TITLE
Status bar background color

### ISSUE THREAD

**Issue by joe-watkins** [Microsoft/vscode#1884]
The blue color is very distracting.. a way to change the color of that would be great!

<img src="http://content.screencast.com/users/joe-watkins-emerge/folders/Snagit/media/412cd601-ba5d-4ccf-a0b5-25bc36237ff0/2016-01-08_10-14-31.png">

**Comment by Witcher42** [comment]
+1!
I hate that color and that mysterious smiley face. Hoping there's a way to change the style of status bar.

**Comment by collinksmith** [comment]
+1

**Comment by 4781121** [comment]
+1

**Comment by RiCoTeRoX** [comment]
+1

**Comment by wcharczuk** [comment]
+1

**Comment by artemeff** [comment]
+1

**Comment by Nimzozo** [comment]
:-1: -1 I like it lol.

**Comment by bgashler1** [comment]
Sorry for the delayed response on this issue.  We use blue within the status bar because it's consistent within the family of Visual Studio.  We may in the future open this and other things to customization via user style sheets.  Hopefully that will address any concerns you have with the color.

**Comment by ypyf** [comment]
+1

**Comment by bjz** [comment]
@bgashler1 I understand your desire to default to aligning with the VS branding, but the color is extremely distracting for some people. It would be great if you could at least have a user style sheet that would allow us to dim it down, or just set it to always be black. This is about the only thing that is preventing me from committing to your fantastic editor.

**Comment by ccknot** [comment]
+1

**Comment by jmcooper** [comment]
+1

**Comment by Tyriar** [comment]
Reopening. This will likely be part of https://github.com/Microsoft/vscode/issues/1231

**Comment by Kenny-Wang** [comment]
+1

**Comment by shubhamsizzles** [comment]
If you look at the editor from a metre away, the only thing you will see is the deeply saturated status bar, which is actually pretty distracting while editing.

 Since  #1231 is now closed, it would be nice to have a option to tone it down a bit.

**Comment by Tyriar** [comment]
@shubhamsizzles there were multiple levels of duplicates, follow the UI theme issue here https://github.com/Microsoft/vscode/issues/3112

**Comment by natdm** [comment]
If the status bar distracts you from developing, maybe you have other issues?

I'm cool with the color. Blue in 'normal' conditions, orange-red in debug mode. Works for me.

**Comment by wcharczuk** [comment]
> If the status bar is what distracts you from developing, maybe you have other issues? 

I'll take passive aggressive responses for 100, Alex.

**Comment by natdm** [comment]
Not passive aggressive. 

Out of all the things to complain about in an IDE, the status bar at the bottom? Not bugs, lack of features to assist in more efficient development, language support, better debugging or GIT integration, lack of community, etc... (not saying VSC has these issues) but.. the color of the status bar at the bottom?

**Comment by shubhamsizzles** [comment]
@natdm Well, guess what, UI does matter in an IDE/editor. If it were only for the features you mentioned not, we'd all be using vim/emacs

**Comment by glen-84** [comment]
If #459 was implemented, this would be easy to change.

**Comment by dnaroid** [comment]
`echo ".monaco-workbench>.part.statusbar{background-color:#000;}" | sudo tee -a /usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.css`

**Comment by be5invis** [comment]
My current CSS patch for Code:

```css
/***** PATCHES *****/
.monaco-workbench.hc-black { color: #FFF; background-color: #000; }
.monaco-workbench.hc-black .sidebar .separator 	{ background-color: #000; border: 1px solid #6FC3DF; }
.monaco-workbench.hc-black input,
.monaco-workbench.hc-black textarea {
	background-color: #000;
}
.monaco-workbench.hc-black .monaco-action-bar .action-item.disabled .action-label.disabled,
.monaco-workbench.hc-black .monaco-action-bar .action-item.disabled .action-label.disabled:hover {
	opacity: 1;
}
.monaco-workbench.hc-black .monaco-action-bar .action-item.disabled .action-label.disabled:before {
	opacity: .4;
}

.monaco-shell { font-family: "Iosevka", "Helvecita", "Inziu Iosevka SC", sans-serif}
.monaco-shell:lang(zh-Hans) { font-family: "Iosevka", "Helvecita", "Inziu Iosevka SC", sans-serif}
.monaco-shell:lang(zh-Hant) { font-family: "Iosevka", "Helvecita", "Inziu Iosevka CL", sans-serif}
.monaco-shell:lang(ja) { font-family: "Iosevka", "Helvecita", "Inziu Iosevka J", sans-serif}
.monaco-workbench > .part > .content {font-size:11px}
.decorationsOverviewRuler{
	clip:rect(2px,13px,1000px,2px);
	margin-top: -2px;
	height:calc(100% + 4px);
}
.monaco-workbench.vs-dark .editor > .content > .editor-center,.monaco-workbench.vs-dark .editor > .content > .editor-right { border-left-color:#0a0a0a}
.monaco-workbench.vs-dark { background: #252525 }
.monaco-editor.vs-dark .git-dirty-modified-diff-glyph {	background-color: rgba(250,190,28,0.6) }
.explorer-viewlet .explorer-item-label, .explorer-viewlet .working-files-item-label { color: rgb(190, 190, 190) }
.vs-dark .monaco-tree .monaco-tree-row.selected { color: rgb(210, 210, 210) }
.vs-dark .monaco-tree .monaco-tree-row.focused, .vs-dark .monaco-tree .monaco-tree-row.selected { background: rgb(57,57,56)!important }
.vs-dark .monaco-tree .primary-action-bar,.vs-dark .monaco-tree.focused .monaco-tree-row.focused:not(.highlighted)>.content.actions>.primary-action-bar { background: none!important }
.monaco-workbench.no-workspace>.part.statusbar,.monaco-workbench > .part.statusbar {background: rgb(21,21,21)}
.monaco-workbench > .part.statusbar>.statusbar-item{opacity: 0.6}
.monaco-workbench>.part.panel>.title { border-top-color: rgba(255,255,255,0.1) }
.monaco-editor.vs-dark .git-dirty-modified-diff-glyph { background: none }
.monaco-editor.vs-dark .current-line {border: none}
.monaco-editor.vs-dark .selectionHighlight { background: rgba(173,214,255,0.1)}

.token.haskell { font-feature-settings: "XHS_" 1; }
.token.patel { font-feature-settings: "XPTL" 1; }

.explorer-open-editors .editor-group { visibility: hidden }
.explorer-open-editors .monaco-tree-row.expanded { margin-bottom: -22px }
.explorer-open-editors .monaco-tree-row + .monaco-tree-row.expanded { border-top: 1px solid rgba(255,255,255,0.05); margin-top: -1px }
```
I have to do this every update. Please support user CSS or UI themeing.

**Comment by rossHell** [comment]
Really ? Distractive ? Are you not able to drive your eyes ? Never seen an issue for an IDE so stupid

**Comment by smlombardi** [comment]
@be5invis Where is this file located?

**Comment by dracan** [comment]
+1 Whilst I personally don't find it a distraction as such - I dislike that when making the editor fullscreen (F11) it's the only thing that stops the editor feeling completely seamless (for lack of a better word). Try loading the Atom editor in dark theme and make that fullscreen. It looks completely seamless. VSCode would look just as good (if not better) if it wasn't for this out of place blue bar at the bottom.

**Comment by smlombardi** [comment]
I think it's really hideous in an otherwise attractive UI. It's not that it's blue (although grey would be better), it's too bright.  I have seen it looks better on Win 10 than on Mac (I am on Mac). But it's just a status bar, why should it command so much attention? 

For those commenting that we should "get a life" instead of complaining about something so "trivial", remember that the UI of an application is something you stare at all day.  It should please you as well as assist you. Even a simple way to color it in a theme or other editor pref would be appreciated.

**Comment by be5invis** [comment]
Made an extension to patch your custom CSS into Code:

https://github.com/be5invis/vscode-custom-css
https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css

Set the `vscode_custom_css.file` option to the CSS you’d like to apply and enable it.

**Comment by dominique-mueller** [comment]
`vscode-custom-css` works like a charm! I patches my CSS with this one here: https://gist.github.com/dominique-mueller/0d9f5aec202804caca4881838685cfc4, in combination with the Oceanic dimmed theme.

**Comment by heidricha** [comment]
I don't mind the default blue, my problem is, that it is blue for all VScode windows.

It would be fine to set the color quickly (right click on status bar??). when working with more than one window of VS code, I could be able to spot the window I need on the gnome task selection

anyway, sometimes the status bar is purple, or orange, which seems have specific meanings

**Comment by felippem** [comment]
+1

**Comment by nfantone** [comment]
@be5invis Tried your extension and working fantastic. A bit tedious if you are using Insiders, but great nonetheless. Cheers.

Incidentally, is there anyway to set icons on the sidebar using font faces, instead of `png` files?

**Comment by sysrpl** [comment]
Help -> Toggle Developer Tools -> Console

> document.getElementById("workbench.parts.statusbar").style.color = "black"

**Comment by tylercubell** [comment]
1. Install and enable https://github.com/be5invis/vscode-custom-css
2. Restart Visual Studio Code as Administrator
3. Create `style.css`:

    ```css
    .monaco-workbench.no-workspace>.part.statusbar {
      background-color: #333333 !important;
    }
    ```

4. File > Preferences > User Settings

    ```json
    {
        "vscode_custom_css.imports": [
            "file://path_to_css_file/style.css"
        ]
    }
    ```
5. F1 > Enable Custom CSS and JS
6. Restart Visual Studio Code
