### ISSUE TITLE
Webviews don't respect accessibility.unfocusedViewOpacity

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#189650]
This setting works by injecting some CSS here:

https://github.com/microsoft/vscode/blob/040c5df8702d64125a719ec9cfca9adadc620d7b/src/vs/workbench/contrib/accessibility/browser/unfocusedViewDimmingContribution.ts#L37-L50

Webviews aren't part of the regular DOM structure though so I'm not sure the best way to do this. I tried this but it didn't work:

```css
[data-parent-flow-to-element-id^=webview-editor-element] .webview:not(:focus-within) {
    filter: opacity(0.5);
}
```

I think we need a `focused` class on the iframe to be able to style this from the main document.
