### ISSUE TITLE
error - Could not create tunnel

### ISSUE THREAD

**Issue by ilteoood** [microsoft/vscode#189830]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.81.0
- OS Version: Docker image

Steps to Reproduce:

I've built [this Docker image](https://github.com/ilteoood/vscode-remote-tunnels) in order to deploy a remote vscode server instance on my Raspberry PI.

 The operations I do are:
- Create the container using the following compose file
```
version: "2"
configs:
services:
  vscode:
    image: ilteoood/vscode-remote-tunnels
    container_name: vscode-remote-tunnels
    environment:
      - MACHINE_NAME=raspberry
    restart: unless-stopped
    dns:
      - 1.1.1.1
```
- Complete the authorization process.

When I re-create the container with the same `MACHINE_NAME`, the container dies and displays the following logs:
```
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
To grant access to the server, please log into https://github.com/login/device and use code 35E5-9E6B
[2023-08-07 15:45:02] info Creating tunnel with the name: raspberry
[2023-08-07 15:45:05] error Could not create tunnel with name: raspberry
```

Expected behavior: when a tunnel is closed, its name should be free to use for other instances.
