### ISSUE TITLE
Add scss support for container-*

### ISSUE THREAD

**Issue by Trinovantes** [microsoft/vscode#191356]
Add scss highlight support for `container-*` properties and `@container` query. These are now supported on most modern browsers. 

https://developer.mozilla.org/en-US/docs/Web/CSS/container#browser_compatibility

This currently gives `scss(unknownProperties)` warning:
```scss
article{
    container-type: inline-size;

    .grid{
        @container (min-width: 400px) {
            grid-template-columns: 1fr 1fr;
        }

        @container (min-width: 600px) {
            grid-template-columns: 1fr 1fr 1fr;
        }
    }
}
```
