### ISSUE TITLE
Add more cursor styles

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#1929]
Extracted from #1586.
Related: #200.
#### block/block-thin/block-hollow/block-outline:

![block-outline](https://cloud.githubusercontent.com/assets/261509/12010563/7443fbae-acb4-11e5-96d3-d29e3a26991c.png)

``` css
? {
    background: transparent;
    border: 1px solid;
    box-sizing: border-box;
    position: absolute;
    width: 1ch;
    cursor: text;
}
```
#### block/block-filled:

![block-filled](https://cloud.githubusercontent.com/assets/261509/12010567/88c493fe-acb4-11e5-8c34-3b606b3ffed9.png)

``` css
? {
    position: absolute;
    width: 1ch;
    cursor: text;
}
```
#### line/line-thin/line-narrow:

![line-thin](https://cloud.githubusercontent.com/assets/261509/12010569/93a71e68-acb4-11e5-88ae-46d6bace2c3a.png)

``` css
? {
    position: absolute;
    width: 1px;
    cursor: text;
}
```
#### line/line-thick/line-accessible:

![line-thick](https://cloud.githubusercontent.com/assets/261509/12010570/9fdc7c46-acb4-11e5-926a-063993dee59d.png)

``` css
? {
    position: absolute;
    width: 2px;
    cursor: text;
}
```
#### underline/underline-thin:

![underline-thin](https://cloud.githubusercontent.com/assets/261509/12010571/aefe6d88-acb4-11e5-8db1-27cf3c1b311a.png)

``` css
? {
    background: transparent;
    border-bottom: 1px solid;
    box-sizing: border-box;
    position: absolute;
    width: 1ch;
    cursor: text;
}
```
#### underline/underline-thick/underline-accessible:

![underline-thick](https://cloud.githubusercontent.com/assets/261509/12010572/b713d1b6-acb4-11e5-951a-0444b99f0e4d.png)

``` css
? {
    background: transparent;
    border-bottom: 2px solid;
    box-sizing: border-box;
    position: absolute;
    width: 1ch;
    cursor: text;
}
```

I'm not too sure about the names, maybe:

block-filled
block-outline
line-thin
line-thick
underline-thin
underline-thick

... I'll leave this to the developers. =)

cc @glen-84 @markrendle
