### ISSUE TITLE
My CSS is too powerful for the current syntax highlighter

### ISSUE THREAD

**Issue by madprops** [microsoft/vscode#193639]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.81.1
- OS Version:  Linux

Steps to Reproduce:

1. Write this in a css file

![css2345](https://github.com/microsoft/vscode/assets/206498/2ade6a84-9a36-4c60-9d52-06876143c172)

**Comment by madprops** [comment]
```css
.item > div:nth-child(1 of :not(.hidden))  {
  padding-left: var(--item_margin);
}

.item > div:nth-last-child(1 of :not(.hidden)) {
  padding-right: var(--item_margin);
}
```
