### ISSUE TITLE
VSCode `1.83.0-1695954371` major graphical glitch (on Linux with AMD GPU)

### ISSUE THREAD

**Issue by NatoBoram** [microsoft/vscode#194486]
Does this issue occur when all extensions are disabled?: Yes

```yaml
Package: code-insiders
Version: 1.83.0-1695954371
Priority: optional
Section: devel
Maintainer: Microsoft Corporation <vscode-linux@microsoft.com>
Installed-Size: 382 MB
Provides: visual-studio-code-insiders
```

```yaml
OS: Pop!_OS 22.04 LTS x86_64 
Host: MS-7D53 1.0 
Kernel: 6.4.6-76060406-generic 
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
GPU: AMD ATI Radeon RX 6700/6700 XT / 6800M 
Memory: 32007MiB 
```

Steps to Reproduce:

1. Open VSCode Insiders

Side-by-side comparison:

![image](https://github.com/microsoft/vscode/assets/10495562/fc770f0d-fa04-48b0-8f9e-0ff1e9cc5872)

With `code-insiders --disable-gpu`:

![image](https://github.com/microsoft/vscode/assets/10495562/8b95f61f-c571-4c04-80b2-666ed1e29334)
