### ISSUE TITLE
scss syntax highlighting problem

### ISSUE THREAD

**Issue by issam-seghir** [microsoft/vscode#196511]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.83.1
- OS Version: 22H2 19045.3570 windows 10 pro

The syntax highlighting feature is not working for `@inculde`, `@use`, and `@container`, and neither is the new CSS features like custom selectors.
![image](https://github.com/microsoft/vscode/assets/74573675/a8c0d6da-7997-471f-b5df-2db390c3d14d)

![image](https://github.com/microsoft/vscode/assets/74573675/71204ed4-c719-4be4-bd12-5a73d06299e0)

**Comment by alexr00** [comment]
@issam-seghir can you share a copy/pastable code snippet I can use to repro the issue?

**Comment by issam-seghir** [comment]
```scss
p {
	font-size: $text-lg;
	font-weight: $font-normal;
	line-height: 1.75rem;
	color: $text-primary-200;

	&.tag {
		@include pseudo("", 0.5em, 0, -1.5rem) {
			@include circle(13px);
			background-color: currentcolor;
		}
		width: fit-content;
		margin: 0 auto 3rem;
		font-weight: $font-bold;
		color: $text-secondary-100;
	}
       @include pseudo("", -20%, 0, -20%, 0, "after") {
			@include sizer(calc(100% + 5rem));
					z-index: 1;
					background-image: linear-gradient(rgb(5 3 8 / 0%) 74%, #050308 91%);
	}

	@include sizer(11.375rem);
	
       @container (width < 400px) {
					top: -12.3rem;
				}
}
```
