### ISSUE TITLE
Using .clang-format for alignment causes problems

### ISSUE THREAD

**Issue by 961730455** [microsoft/vscode#197330]
Type: <b>Bug</b>

The Options with issues are:
```
AlignConsecutiveAssignments:
  Enabled: True
AlignConsecutiveDeclarations:
  Enabled: True
```
If the variable type includes an underscore, such as "size_t", an extra space will be added during alignment.

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.17763
Modes:
