### ISSUE TITLE
Unessecary horizontal scrolling when a file is decompressed

### ISSUE THREAD

**Issue by Noxlobin** [microsoft/vscode#197437]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.0
- OS Version: Windows_NT x64 11

Steps to Reproduce:

- Open a compressed file. Example in a css file: (put all in one line)

```css
body{font-family:"Karla",sans-serif}.container{display:flex;align-items:center;justify-content:center;height:96vh}.box{box-shadow:0px 0.27rem 1.875rem #98a6bd;border-radius:0.625rem}.info{padding:1.18875rem 2.4725rem;padding-bottom:2.174125rem}.header{font-size:1.500315rem;font-weight:700;color:#2ab2af;margin-block:20px;margin-block-end:25px}.sub-header{font-size:1.15000625rem;color:#c0df34;font-weight:700;margin-block-end:0.625rem}.body{color:#98a6bd;width:34.375rem;line-height:1.5}.flex-items{display:flex}.sign-up{background-color:#2ab2af;padding:2.12625rem 2.535rem}.sign-up__header{color:#fff;font-weight:700;margin:0}.sign-up .price-tag{display:flex}.sign-up .price-tag p:first-child{color:#fff;font-weight:700;font-size:1.875rem;margin-right:0.75rem}.sign-up .price-tag p:nth-child(2){margin-top:2.33375rem;color:#2ab2af;font-weight:700}
``` 

- Put the code in vscode and drag the horizontal scroll bar till the end
- Decompress the code given (my favourite way is using Prettier, but don't use it if you prefer) while the scroll bar is in the end.
- At this point, the scroll bar stays the same, but you cannot see the code.
Reproducing video: 

https://github.com/microsoft/vscode/assets/138752348/d5c32e2b-6c48-47cc-96c3-ab3988786343
