### ISSUE TITLE
Winget configuration "PSDscResources/Script" error when running "code --install-extension"

### ISSUE THREAD

**Issue by PShipstone** [microsoft/vscode#198627]
Does this issue occur when all extensions are disabled?: YES

- VS Code Version: 
![image](https://github.com/microsoft/vscode/assets/44038179/2e5900db-8f8a-4c1a-8191-71b87d99670b)

- OS Version: 
```shell
Windows Package Manager (Preview) v1.7.2782-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2506
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.2782.0
```

### Brief description of your issue
Ref closed winget issue: https://github.com/microsoft/winget-cli/issues/3887

When using `Winget configuration`,  a `PSDscResources/Script` resource generates an error when running `code --install-extension` when the extension is not installed.   Even though the warning is generated, the vscode extensions do get installed.

### Steps to reproduce

1. Ensure the required VSCode extensions are uninstalled.

2. Create a YAML DSC file, for example:

```
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:      
    - resource: PSDscResources/Script
      id: myAppConfig
      directives:
        description: Configure My App
        allowPrerelease: true
      settings:
        GetScript: |
          # Your custom PowerShell code to check app configuration
        TestScript: |
          return $false
        SetScript: |
          # PowerShell script commands to install VSCode extensions
          code --install-extension jebbs.plantuml 
          code --install-extension yzhang.markdown-all-in-one      
  configurationVersion: 0.2.0 
```
3. Execute WinGet, for example:  

```
winget configuration C:\tmp\dev-machine.dsc.yaml
```

### Expected behavior

The VSCode extentions get installed with no warnings

### Actual behavior

The following warning is generated, but the extensions are still installed

![image](https://github.com/microsoft/winget-cli/assets/44038179/54d213aa-61fc-4d78-b982-5a33012bc5d6)

**Comment by PShipstone** [comment]
update: I have resolved my problem by using start-process as shown below, but would be nice if the above worked:

```
    - resource: PSDscResources/Script
      id: VSCode-Extensions
      directives:
        description: Install VSCode extensions
        allowPrerelease: false
      settings:
        GetScript: |
          # Your custom PowerShell code to check app configuration
        TestScript: |
          return $false
        SetScript: |
          # PowerShell script commands to install VSCode extensions
          Start-Process -WindowStyle Hidden code "--install-extension jebbs.plantuml" -Wait
          Start-Process -WindowStyle Hidden code "--install-extension yzhang.markdown-all-in-one" -Wait 
```
