### ISSUE TITLE
The CSS property "hyphens" is not recognised.

### ISSUE THREAD

**Issue by BobbyBabes** [Microsoft/vscode#19866]
- VSCode Version:
```
Version 1.9.0
Commit 27240e71ef390bf2d66307e677c2a333cebf75af
Date 2017-02-02T08:21:13.228Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```
- OS Version:
```Linux  4.9.6-1-ARCH #1 SMP PREEMPT Thu Jan 26 09:22:26 CET 2017 x86_64 GNU/Linux
```
Steps to Reproduce:

1. Define a CSS rule which contains the `hyphens` property.
Example :
```CSS
.text-break {
  -webkit-hyphens: auto;
  -ms-hyphens: auto;
  -moz-hyphens: auto;
  hyphens: auto;
}
```
2. The W3 standards property `hyphens` will receive an `Unknown property.` warning.

![vscode-hyphens-unknown-css-property](https://cloud.githubusercontent.com/assets/22870070/22603399/7ff6adee-ea47-11e6-8488-13e3af5b1853.png)
