### ISSUE TITLE
Disable formatter for some part of CSS

### ISSUE THREAD

**Issue by ngdangtu-vn** [microsoft/vscode#198896]
If you have a `clip-path` in your code, you will wish to disable only that part so you can save time in future. Maybe we can do it like these:

1. Pair comment: `/* !ignore-format */` and `/* !ignore-format-end */`
2. Scope comment on Selector/Declaration: `/* !ignore-format-this */`

**Examples**

```CSS
div {
    /* !ignore-format */
    clip-path: polygon(
        0 .5rem, .5rem 0,
        calc(100% - .5rem) 0, 100% .5rem,
        100% calc(100% - .5rem), 100% .5rem,
        100% calc(100% - .5rem)
    );
    /* !ignore-format-end */
}

body { margin: 0 } /* !ignore-format-this */

a { 
    text-decoration: none; /* !ignore-format-this */
}
```
