### ISSUE TITLE
CSS/SCSS format.spaceAroundSelectorSeparator not working correctly

### ISSUE THREAD

**Issue by webdevnerdstuff** [microsoft/vscode#199462]
Does this issue occur when all extensions are disabled?: **Yes**

Both settings are included:
```json
{
  "css.format.spaceAroundSelectorSeparator": true,
  "scss.format.spaceAroundSelectorSeparator": true,
  "[css]": {
    "editor.defaultFormatter": "vscode.css-language-features",
    "editor.formatOnSave": true
  },
  "[scss]": {
    "editor.defaultFormatter": "vscode.css-language-features",
    "editor.formatOnSave": true,
  },
}
```

I'm not 100% positive that `spaceAroundSelectorSeparator` should add this space, but that was the only setting I could find that deals with spacing and these characters. Either way the formatter should not be removing this space. I have also tried with using Prettier as the formatter to see if it did it there as well, and it does not remove the space.

- VS Code Version: 1.84.2 (Universal)
- OS Version: Mac 13.5.2 (22G91)

Steps to Reproduce:

1. Use an operator in an @if statement
2. Format the code
3. Notice the right side of the operator space is removed

Ex. 
```scss
@for $i from 1 through $positions {
  &.pos#{$i} {
    left: $i * if($i !=$positions, 10%, 15%);
  }
}

@if $positions ==10 {
  &.pos11 {
    left: 100%;
  }
}
```
