### ISSUE TITLE
Option to remove __proto__ from object info in the varables and mouseover popup views

### ISSUE THREAD

**Issue by icetbr** [Microsoft/vscode#19950]
VERY minor thing, but it would be nice. A list of excluded properties might be even better.

```
person:
     name "John"
     age: 32
     __proto__: Object
```
