### ISSUE TITLE
The indicator on the markdown preview is not visible when the dark theme and the background is white

### ISSUE THREAD

**Issue by satokaz** [Microsoft/vscode#19962]
- VSCode Version: Code 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:23:30.856Z)
- OS Version: Darwin x64 16.4.0

Under the following conditions, the Markdown Preview side indicator can not be seen.

Steps to Reproduce:

- Dark theme is applied
- Applied a custom CSS (e.g. body {background-color: white;} in`markdown.styles` file) with Markdown preview 

The dark theme realizes gray with transparency. Therefore, it becomes invisible if white is set as the background.
	
https://github.com/Microsoft/vscode/blob/master/extensions/markdown/media/markdown.css#L45-L51

```css
.vscode-dark.showEditorSelection .code-active-line:before {
	border-left: 3px solid rgba(255, 255, 255, 0.4);
}

.vscode-dark.showEditorSelection .code-line:hover:before {
	border-left: 3px solid rgba(255, 255, 255, 0.60);
}
```
![2017-02-05 15 45 30](https://cloud.githubusercontent.com/assets/13635244/22624280/47148e6e-ebba-11e6-9407-745fa30c60da.png)

## My work around

The following CSS was added to the custom CSS file.

```css
.vscode-dark.showEditorSelection .code-active-line:before {
    border-left: 3px solid rgba(128, 128, 128, 1);
}

.vscode-dark.showEditorSelection .code-line:hover:before {
    border-left: 3px solid rgba(192, 192, 192, 1);
}
```

![2017-02-05 15 47 34](https://cloud.githubusercontent.com/assets/13635244/22624287/7a48077a-ebba-11e6-8d8a-2dd9141d452e.png)

**Comment by mjbvz** [comment]
@satokaz Thanks for the report.

I'm glad you found a workaround. Please let me know if you have any ideas on how best to fix this in code. The idea behind using opacity instead of solid colors was to look better on different color backgrounds, but I assumed that the background would always be dark when using dark themes and light when using light themes.

**Comment by satokaz** [comment]
@mjbvz Thank you for checking the report.

I do not have a good idea about the implementation.
It seems to be deciding colors based on three basic themes.(light, dark, high-contrast)
Better yet, I think that it is sufficient if the user can designate the color that the user likes in user- setting or workspace-setting. (For example, like  "markdown.indicatorcolor": rgba(128, 128, 128, 1);")

**Comment by mjbvz** [comment]
Since you're already using custom CSS to get into this state, as you originally noted, I think the solution here is really to add custom styling for the indicators. 

Closing this as-designed since the indicators work when using standard preview stylings. For custom preview styles, how the indicators are displayed can be controlled with a bit of extra css

**Comment by satokaz** [comment]
Thank you for responding
Ok, I will summarize.

**Q: Can I change the preview indicator to my favorite color?**

**A:**

Please add custom CSS with `markdown.style` setting of `settings.json`.
Please refer to the document 
[Using your own CSS](https://code.visualstudio.com/docs/languages/markdown#_using-your-own-css) for details.

Examples based on gray:
```css
[class*="vscode-"].showEditorSelection .code-active-line:before {
    border-left: 3px solid rgba(128, 128, 128, 1);
}

[class*="vscode-"].showEditorSelection .code-line:hover:before {
    border-left: 3px solid rgba(192, 192, 192, 1);
}
```

>**Note:** When CSS is set to make the background white as the dark theme, the indicator disappears. Please change the color with this setting.

Thanks
