### ISSUE TITLE
Nested elements in CSS

### ISSUE THREAD

**Issue by sabbah-altaj** [microsoft/vscode#200314]
Type: <b>Adding Feature</b>

In the CSS3 features released in 2023, the inclusion of nested elements is noteworthy. However, it is observed that Visual Studio Code does not currently comprehend nesting. I anticipate the incorporation of colorization for nested elements, akin to the functionality present in the SASS CSS preprocessor.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by VSCodeTriageBot** [comment]
Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.85.0. Please try upgrading to the latest version and checking whether this issue remains.

Happy Coding!

**Comment by aeschli** [comment]
Nesting support has been added a while back.
Can you give more information about what doesn't work? Please add a sample code.

**Comment by craxal** [comment]
Syntax highlighting seems a bit spotty. For example, here's a sample of CSS with no nesting:

![image](https://github.com/microsoft/vscode/assets/3473026/51425a12-7230-4488-ae20-987624310248)

And here's a sample with nesting. Notice certain nested selectors aren't highlighted. Notice also nothing is highlighted more than 2 levels deep. Often the presence of the `&` selector doesn't matter.

![image](https://github.com/microsoft/vscode/assets/3473026/b651b2a9-b6a8-437a-b96a-c0a41d711152)

**Comment by shenef** [comment]
Same here, the highlighting seems spotty. 
VSCode 1.85.1
![image](https://github.com/microsoft/vscode/assets/20268890/fc02523f-b23b-446c-9a29-81feabf586eb)
<details>
<summary>code from image</summary>
  ```css
  textarea,
  input[type="text"],
  input[type="number"] {
      background: var(--bg-color);
      color: var(--font-color);
      border: 1px solid var(--font-color);
      border-radius: 0.25em;
      outline: none;
      padding: 2px 4px 1px 4px;
      &:hover,
      &:focus {
          border-color: var(--accent-color);
      }
      &:hover {
          box-shadow: 0 0 0.4em var(--accent-color);
      }
  }
  
  input[type="checkbox"] {
      padding: 48px;
      &:checked,
      &:hover {
          accent-color: var(--accent-color);
          box-shadow: 0 0 0.4em var(--accent-color);
      }
  }
  ```
</details>
