### ISSUE TITLE
DevContainer some calls all previous postCreateCommands

### ISSUE THREAD

**Issue by distante** [microsoft/vscode#203066]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.85.2 (Universal)
- OS Version: MACOS 14.2.1 (23C71)

## Steps to Reproduce:

1. Create a container
3. Add a `postCreateCommand`
4. Recreate the container
5. Change the `postCreateCommand`
6. Recreate the container again

## Expectation
After creation, the container runs the last `postCreateCommand` command.

## Reality
all the previous `postCreateCommand` are run one after the other.

I can always reproduce it using:

devcontainer.json
```json
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/alpine
{
  "name": "Nextcloud DevContainer",
  "dockerComposeFile": ["./docker-compose.yml"],
  "service": "nextcloud",
  "workspaceFolder": "/var/www/html/custom_apps/memories",
  // Features to add to the dev container. More info: https://containers.dev/features.
  "features": {},

  // Use 'forwardPorts' to make a list of ports inside the container available locally.
  // "forwardPorts": [],
 "postCreateCommand": "echo 'created'",
  // Configure tool-specific properties.
  "customizations": {
    "vscode": {
      "extensions": [
        "bmewburn.vscode-intelephense-client",
        "muuvmuuv.vscode-just-php-cs-fixer",
        "getpsalm.psalm-vscode-plugin",
        "esbenp.prettier-vscode",
        "Vue.volar",
        "Vue.vscode-typescript-vue-plugin"
      ],
      "settings": {
        "terminal.integrated.shell.linux": "/bin/bash"
        // Add any other VS Code settings you need for your project
      }
    }
  },

  // Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
  "remoteUser": "root"
}
```

docker-compose.ymal
```
name: 'nextcloud-with-memories'
services:
  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./custom_apps:/var/www/html/custom_apps
      - ./../:/var/www/html/custom_apps/memories
      - ./config:/var/www/html/config
    ports:
      - 9080:80
    image: nextcloud
```

Dockerfile
```yml
# Use the official Nextcloud image as the base image
FROM nextcloud

RUN echo "alias ll='ls -alF'" >> /etc/bash.bashrc
# Install Node.js 18 and npm
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
  apt-get install -y nodejs && \
  rm -rf /var/lib/apt/lists/*

# Install Needed libs
# Install Git, wget, and PHP Composer
RUN apt-get update && \
  apt-get install -y git wget make unzip

# Install PHP Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
  php composer-setup.php --install-dir=/usr/local/bin --filename=composer  && \
  php -r "unlink('composer-setup.php');"

RUN composer global require "vimeo/psalm"
```
