### ISSUE TITLE
FontLigatures: Syntax highlighting issue with `<${` in string templates

### ISSUE THREAD

**Issue by NatoBoram** [microsoft/vscode#203541]
Does this issue occur when all extensions are disabled?: Yes

```yaml
Version: 1.86.0-insider
Commit: 3dea5cbbcb88d7f6dad71148f3d3f98b853ab836
Date: 2024-01-25T07:30:44.607Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.86.0-insider Chrome/118.0.5993.159 Electron/27.2.3 Safari/537.36

OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 6.6.10-76060610-generic 
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
GPU: AMD ATI Radeon RX 6700 XT
Memory: 32016MiB 
```

Steps to Reproduce:

![image](https://github.com/microsoft/vscode/assets/10495562/086d0c28-1a29-481c-9e41-2b775dac8052)

The `<` should be string-coloured
