### ISSUE TITLE
SCSS syntax highlighting fails around :global keyword

### ISSUE THREAD

**Issue by ADTC** [microsoft/vscode#204528]
Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.0
- OS Version: macOS Sonoma 14.2.1 (23C71)

Steps to Reproduce:

1. Create an SCSS module which has `:global` in some form. Example below.
2. Observe the syntax highlighting anomalies.

```scss
.wrapper {
  :global {
    .rdt_TableCol {
      color: $gray600;
      @include textSmSemibold;
    }

    .rdt_TableCell {
      color: $gray700;
      @include textSmRegular;
    }
  }
}
```

Observe that `:global` and the first class name are not highlighted properly, and the second class has `color` not highlighted:

<img width="281" alt="image" src="https://github.com/microsoft/vscode/assets/6047296/1df1f7b6-048e-4a15-a70d-44fa1f178f9f">

If you change the order of declarations:

```scss
.wrapper {
  :global {
    .rdt_TableCol {
      @include textSmSemibold;
      color: $gray600;
    }

    .rdt_TableCell {
      @include textSmRegular;
      color: $gray700;
    }
  }
}
```

This time the first `@include` line lost highlighting completely, and both instances of `color` are not highlighted.

<img width="273" alt="image" src="https://github.com/microsoft/vscode/assets/6047296/d9e89da5-f576-4c1d-b84c-bb07ec8887f6">

(Oddly, it appears GitHub's own SCSS syntax highlighter has similar issues.)

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:11.933Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id e73e6092-1f35-49fb-b56c-f958b97e2539|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>
