### ISSUE TITLE
Activity bar position top: can't click on top of icon in fullscreen

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#204688]
1.

```js
"workbench.activityBar.location": "top",
"window.customTitleBarVisibility": "windowed",
```

2. Enable fullscreen
3. Top/bottom of icon is not clickable.

![demo_position_top](https://github.com/microsoft/vscode/assets/9638156/0cd31f44-25db-4198-bdb3-5689e46f12d5)

Workaround with custom CSS extension:

```css
.monaco-workbench .pane-composite-part>.title>.composite-bar-container>.composite-bar>.monaco-action-bar .action-item.icon {
    height: 100%;
}
```
