### ISSUE TITLE
Simplify sticky-scroll box-shadow styling wherever sticky-scrolling is disabled.

### ISSUE THREAD

**Issue by sushidub** [microsoft/vscode#206283]
Type: <b>Feature Request</b>
Location: <b>Editor Pane(s)</b>

When sticky-scrolling is disabled, the 6px tall graduated box-shadow that's left behind renders itself mostly unnecessary _(Ref. 1)_. Not to mention feels slightly disorienting due to its elevation inconsistency relative to the horizontal scroll-decoration and other floating containers found within the editor pane ui.

Looking at the devtools styles, its class and corresponding css appear to be as follows:
```css
.monaco-editor .scroll-decoration {
    position: absolute;
    top: 0;
    left: 0;
    height: 6px;
    box-shadow: var(--vscode-scrollbar-shadow) 0 6px 6px -6px inset;
}
```

I suggest one or both of the following options wherever sticky-scrolling is an option and can be toggled on or off:

1. Provide a simple `disable|enable` **Scroll decoration** toggle.
2. Provide user with tip or notice of specific json prop/value allowing for slight customization or built-in replacement of the box-shadow. Replacement styling options:
  - `height: var(--user-scroll-decoration-width)` _(Ref. 2)_
  - `background-color: var(--vscode-editorIndentGuide-background1)` _(Ref. 2)_
  - `border-bottom: 1px solid var(--user-scroll-decoration--color)`

_Ref. 1, current_
<img width="1076" alt="image" src="https://github.com/microsoft/vscode/assets/482622/c54ed317-0b86-4f43-a456-db758fa8940a">

_Ref. 2, custom_
<img width="1076" alt="image" src="https://github.com/microsoft/vscode/assets/482622/062e909d-4e4c-4061-806a-923d07333182">

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:13.651Z)
OS version: Darwin x64 19.6.0
Modes:
