### ISSUE TITLE
Bash syntax highlighting in yml files in VSCode

### ISSUE THREAD

**Issue by martyzee** [microsoft/vscode#207338]
Type: <b>Bug</b>

When using a bash step in a pipeline job, the syntax highlighting is unpredictable and sometimes just doesn’t work.

![image](https://github.com/microsoft/vscode/assets/85994286/7bc1ea87-f21f-438a-b13a-df004a4248a8)
![image](https://github.com/microsoft/vscode/assets/85994286/a28601aa-e218-4a1a-b9c6-fa345a239cba)
![image](https://github.com/microsoft/vscode/assets/85994286/82cb11b2-e40f-4270-83f5-1aa78dcc5ec5)

VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 6c111b17-ec67-4a51-9adb-d3dc8085e9f3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
jsoncrack-vscode|Ayk|2.0.2
restore-terminals|Eth|1.1.8
vscode-docker|ms-|1.29.0
remote-containers|ms-|0.327.0
stannum-shellscript-syntax|sta|0.0.3
json2yaml|tux|0.2.0
errorlens|use|3.16.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
cppperfcontrol:30979541
d34g3935:30971562
bg6jg535:30979843
78248357:30976999
ccp2r6:30958158
dsvsc020:30976470

```

</details>

**Comment by VSCodeTriageBot** [comment]
Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.87.1. Please try upgrading to the latest version and checking whether this issue remains.

Happy Coding!

**Comment by alexr00** [comment]
@martyzee can you share a copy+pastable cope snippet that I can use to reproduce the issue?

**Comment by martyzee** [comment]
> @martyzee can you share a copy+pastable cope snippet that I can use to reproduce the issue?

``` yaml
stages:
  - stage: CheckPolicies
    pool:
      name: Default
    jobs:
      - job: CheckPolicies
        steps:
          - bash: |
              set -euo pipefail
              var=14 # this is an inline comment
              echo "echo statement"
              echo

              # this is a big comment
              # this is a big comment
              # this is a big comment
              for file in myfilename
              do
                echo do stuff
              done
```

```yaml
stages:
  - stage: CheckPolicies
    pool:
      name: Default
    jobs:
      - job: CheckPolicies
      "
        steps:
          - bash: |
              set -euo pipefail
              var=14 # this is an inline comment
              echo "echo statement"
              echo

              # this is a big comment
              # this is a big comment
              # this is a big comment
              for file in myfilename
              do
                echo do stuff
              done
```

```yaml
stages:
  - stage: CheckPolicies
    pool:
      name: Default
    jobs:
      - job: CheckPolicies
      {
        steps:
          - bash: |
              set -euo pipefail
              var=14 # this is an inline comment
              echo "echo statement"
              echo

              # this is a big comment
              # this is a big comment
              # this is a big comment
              for file in myfilename
              do
                echo do stuff
              done
```

**Comment by RedCMD** [comment]
`{` is the start of `flow-mapping`
which does allow comments
![image](https://github.com/microsoft/vscode/assets/33529441/b6170914-ab7b-4977-9be1-0d2faba455ef)

and `"` just breaks strings in a weird way

**Comment by martyzee** [comment]
> `{` is the start of `flow-mapping` which does allow comments (under `prototype`) ![image](https://private-user-images.githubusercontent.com/33529441/312048744-b6170914-ab7b-4977-9be1-0d2faba455ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDE5OTAsIm5iZiI6MTcxMDI0MTY5MCwicGF0aCI6Ii8zMzUyOTQ0MS8zMTIwNDg3NDQtYjYxNzA5MTQtYWI3Yi00OTc3LTliZTEtMGQyZmFiYTQ1NWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDExMDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNmNhODFhMTliNWFlZmIzZmJiNmMwOTZhZjE2MjM1ODVlNjJiNTlhZWU5M2ExMTNjZTkyOTY5NmZlNGFkZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AqB6bW8lUviDEfdERiv1OFIp6ovubDJ9z9H9bd_D4CY)
> 
> and `"` just breaks strings in a weird way

I purely used those characters as an example of what the comments should look like, not in any way functional.

**Comment by RedCMD** [comment]
currently there's no special support for `bash`

you would like `bash` added as an embedded language?

**Comment by alexr00** [comment]
Thanks for samples @martyzee and thanks for the analysis @RedCMD!

**Comment by VSCodeTriageBot** [comment]
This feature request is now a candidate for our backlog. The community has 60 days to [upvote](https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request) the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it. To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!

**Comment by martyzee** [comment]
> This feature request is now a candidate for our backlog. The community has 60 days to [upvote](https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request) the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it. To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).
> 
> Happy Coding!

Is this technically not a bug?

**Comment by martyzee** [comment]
> currently there's no special support for `bash`
> 
> you would like `bash` added as an embedded language?

@RedCMD can you upvote please?

**Comment by VSCodeTriageBot** [comment]
This feature request has not yet received the 20 community [upvotes](https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request) it takes to make to our backlog. 10 days to go. To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!

**Comment by VSCodeTriageBot** [comment]
:slightly_frowning_face: In the last 60 days, this feature request has received less than 20 community upvotes and we closed it. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!

**Comment by anderer455** [comment]
Can we reopen this please?

The yaml highlighting makes it almost impossible to develop in the editor. The worst part is that there is no alternative nor some extension that solves this problem.

It would be really nice to have it as:
![Image](https://github.com/user-attachments/assets/9caf7bdc-beff-473a-a55b-c7eee3f4c497)

**Comment by RedCMD** [comment]
you could install either of these extensions
[ruschaaf.extended-embedded-languages](https://marketplace.visualstudio.com/items?itemName=ruschaaf.extended-embedded-languages)
[harrydowning.yaml-embedded-languages](https://marketplace.visualstudio.com/items?itemName=harrydowning.yaml-embedded-languages)
and add a comment with the languageId

or send a feature request if it's not enough for you
[extended-embedded-languages](https://github.com/ruschaaf/extended-embedded-languages)
[vscode-yaml-embedded-languages](https://github.com/harrydowning/vscode-yaml-embedded-languages)

**Comment by KevinRohn** [comment]
Oh wow - thanks @RedCMD ! I didn't know these extensions.

**Comment by RedCMD** [comment]
works for me
![Image](https://github.com/user-attachments/assets/65356a87-18a0-4b5d-910e-fcdb585d2a2f)


<details><summary>code</summary>

```yaml
stages:
  - stage: CheckPolicies
    pool:
      name: Default
    jobs:
      - job: CheckPolicies
        steps:
          - bash: | #shell
              set -euo pipefail
              var=14 # this is an inline comment
              echo "echo statement"
              echo

              # this is a big comment
              # this is a big comment
              # this is a big comment
              for file in myfilename
              do
                echo do stuff
              done
          - bash: | #shell
              set -euo pipefail
              var=14 # this is an inline comment
              echo "echo statement"
              echo

              # this is a big comment
              # this is a big comment
              # this is a big comment
              for file in myfilename
              do
                echo do stuff
              done
stages:
  - stage: CheckPolicies
    pool:
      name: Default
    jobs:
      - job: CheckPolicies
        steps:
          - bash: | #shell
              set -euo pipefail
              var=14 # this is an inline comment
              echo "echo statement"
              echo

              # this is a big comment
              # this is a big comment
              # this is a big comment
              for file in myfilename
              do
                echo do stuff
              done
```
</details>
