### ISSUE TITLE
Text starting with hashtags in a Block-Scalar with leading newlines is treated as comment incorrectly

### ISSUE THREAD

**Issue by k-jiang** [microsoft/vscode#208750]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.87.2
- OS Version: Darwin arm64 23.0.0

Steps to Reproduce:

1. Create a YAML file with contents:
```yaml
blockScalarWithoutLeadingNewlines: |-
  text
  # a
  # b
  c

blockScalarWithLeadingNewlines: |-

  text  
  # a
  # b
  c

```

2. Line 10 and 11 should be treated as block-scalars (text) instead of comment:
<img width="394" alt="image" src="https://github.com/microsoft/vscode/assets/6910542/d0c48294-4d81-431b-a79c-32534ae52edc">
