### ISSUE TITLE
JSON: Sort Document bugs out

### ISSUE THREAD

**Issue by ericmp33** [microsoft/vscode#209655]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```yaml
Version: 1.88.0 (user setup)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:26:18.741Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
```

- OS Version:
```yaml
Windows11 - 23H2 (OS Build 22631.3374)
```

Steps to Reproduce:

1. Create this JSON (or any other JSON that has 2 keys with the same key but one has 1st char in upper & other one in lower):
```json
{
    "Paid": "Pagat",
    "paid": "pagat"
}
```

2. Sort it:
<video controls src="https://github.com/microsoft/vscode/assets/60661635/df1b650a-38d9-4ec7-a34a-a85156db2e44">
