### ISSUE TITLE
SCSS Not Properly Highlighting  font-feature-settings property

### ISSUE THREAD

**Issue by mattbierner** [Microsoft/vscode#21050]
In a scss file:

```scss
body {
    font-feature-settings: "kern" 1;
    font-kerning: normal;
}
```

Both `font-feature-settings` and `font-kerning` are split into two sections instead of being a single property:

![screen shot 2017-02-21 at 11 13 10 pm](https://cloud.githubusercontent.com/assets/212305/23200834/65d5cc4a-f88b-11e6-88cf-ed5374a85ffc.png)

![screen shot 2017-02-21 at 11 15 23 pm](https://cloud.githubusercontent.com/assets/212305/23200893/c146d3e4-f88b-11e6-8e85-f62d2461ce7e.png)
![screen shot 2017-02-21 at 11 15 30 pm](https://cloud.githubusercontent.com/assets/212305/23200894/c16b5d72-f88b-11e6-8c5d-f23a3eab0db6.png)
