### ISSUE TITLE
Nested CSS Syntax highlighting inconsistency

### ISSUE THREAD

**Issue by erosman** [microsoft/vscode#211923]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.89.0
- OS Version: Ubuntu 23.10

Steps to Reproduce:

1. Try the following
```css
a {
  &[href*="/abc"],
  &[href*="/def"] {
    color: #f50;
  }

  &[href*="/ghi"],
  &[href*="/jkl"] {
    color: #00f;
  }
}
```
2. Inconsistency in the resulting syntax highlighting
![image](https://github.com/microsoft/vscode/assets/6458876/49cbdd67-08e7-42a3-8ebd-5e104f37f628)
