### ISSUE TITLE
Shell script highlighting broken using quotes for command substitution

### ISSUE THREAD

**Issue by stephanwehr** [microsoft/vscode#214104]
Combining the following breaks shell script syntax highlighting:
- quotes around command substitution => `var="$(<command>)"`
- for loop with brace expansion => `for i in {1..10}; do ...`

**Steps to reproduce**
1. Open VS Code in WSL
2. Create an empty file called `syntax.sh`
3. Make sure language mode is `Shell Script`
4. Paste the following content into editor window:
```bash
#!/bin/bash

echo "Works 1"
( TEST=$(echo {1..10}); echo "$TEST" )

echo "Works 2"
( TEST="$(echo {1..10})"; echo "$TEST" )

echo "Works 3"
( TEST=$(for i in {1..10}; do echo $i; done); echo "$TEST" )

echo "Works 4"
( TEST="$(for i in $(echo {1..10}); do echo $i; done)"; echo "$TEST" )

echo "Works 5"
( TEST="$(echo {1..10} | while read line; do echo $line; done)"; echo "$TEST" )

echo "Syntax Highlighting Broken"
( TEST="$(for i in {1..10}; do echo $i; done)"; echo "$TEST" )

exit 0
```

To me it seems, as if it also breaks `bash` syntax highlighting inside this comment.
After `( TEST="$(for i in {1..10}; do echo $i; done)"; echo "$TEST" )` syntax highlighting doesn't work anymore.
Also the open bracket `(` for the sub shell is highlighted as red inside VS Code.

**System information**
```yaml
code --version
1.89.1
dc96b837cf6bb4af9cd736aa3af08cf8279f7685
x64

wsl --version
WSL-Version: 2.2.3.0
Kernelversion: 5.15.153.1-2
WSLg-Version: 1.0.61
MSRDC-Version: 1.2.5326
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.26091.1-240325-1447.ge-release
Windows-Version: 10.0.22631.3593

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
```
