### ISSUE TITLE
Build vscode with conda

### ISSUE THREAD

**Issue by pwwang** [Microsoft/vscode#21579]
Well, this is related to #8950. I submitted a new issue because I can't re-open that issue.  
All functions ran OK after I compiled and installed vscode with [conda](https://anaconda.org/), except the error `The mode has failed while tokenizing the input.` popped up every time I opened a file or typed a character. Meanwhile, the syntax can't be highlighted. This can't be fixed by the solutions given by #8950.

- VSCode Version: 1.9.1
- OS Version: CentOS release 6.8 (Final)
- conda: 4.1.12

**Steps to Reproduce:**
1. make a folder, and put
2. following 2 files into the folder
`meta.yaml`:
```yaml
package:
    name: vscode
    version: 1.9.1
source:
    fn: vscode.rpm
    url: https://go.microsoft.com/fwlink/?LinkID=760867
build:
    number: '0'
requirements:
    build:
    run:
test:
    commands:
        - code
about:
    home: https://code.visualstudio.com/
    summary: Visual Studio Code is a lightweight but powerful source code editor which runs on your desktop and is available for Windows, macOS and Linux.
```

`build.sh`:
```bash
#!/usr/bin/env bash

rpm2cpio vscode.rpm | cpio -idv
mv usr $PREFIX
ln -s $PREFIX/usr/share/code/code $PREFIX/bin/code
libffmpegso=$PREFIX/lib/libffmpeg.so
libnodeso=$PREFIX/lib/libnode.so

if [ ! -d $PREFIX/lib ]; then
    mkdir $PREFIX/lib
fi

if [ ! -e $libffmpegso ]; then
    cp $PREFIX/usr/share/code/libffmpeg.so $libffmpegso
fi

if [ ! -e $libnodeso ]; then
    cp $PREFIX/usr/share/code/libnode.so $libnodeso
fi
```
3. run `conda build .` to build vscode
4. install it: `conda install vscode --use-local`

I checked the folder `$PREFIX/usr/share/code/resources/app/node_modules/vscode-textmate/node_modules`, it didn't exist. I also tried to make an empty one, which still didn't work.

Anybody has any ideas?

Thanks.
