### ISSUE TITLE
Light color theme showing white for some elements

### ISSUE THREAD

**Issue by jrajav** [Microsoft/vscode#2158]
I'm not sure if this is an issue with Vscode or with the Tomorrow color theme itself, but there's no repo or issue tracker listed anywhere for the extension, so...

The light version in this color theme: 

https://marketplace.visualstudio.com/items/ms-vscode.Theme-TomorrowKit

Results in some code elements being white on the white background:

<img width="1280" alt="screen shot 2016-01-21 at 14 44 16" src="https://cloud.githubusercontent.com/assets/2074135/12494047/cab2a3f8-c04d-11e5-9c4a-8ccc5342a110.png">

In this case, the commas and colons in this JSON file.

**Comment by Tyriar** [comment]
Looks like an issue with the tomorrow theme. This is the rule that is coloring it, nothing should be colored white on a white background:

```css
.monaco-editor.vs.ms-vscode-Theme-TomorrowKit-themes-Tomorrow-tmTheme .token.meta.separator {
    color: rgba(255, 255, 255, 1);
}
```
