### ISSUE TITLE
[less] Add namespace support

### ISSUE THREAD

**Issue by wjohnsto** [Microsoft/vscode#2164]
Maybe I'm doing something incorrectly (definitely possible!), but I receive errors whenever I try to reference a namespace. For example:

```less
.vertical-center() {
	position: relative;
	top: 50%;
	#mixins > .translate-accelerate(0, -50%);
}
```

For the code above, VSCode will display an error stating `} expected`. Is this a known issue/is there a way around it?
