### ISSUE TITLE
Support for setting a shell command for nix based builders

### ISSUE THREAD

**Issue by qknight** [microsoft/vscode#218361]
# Motivation
Using nix for development one can use `nix develop` for nix-flake based development to get into a development shell. 

The basic idea of a development shell is that it contains software and development packages which the default system shell does not share. In other words, this let's use have multiple projects on one machine with different stripped-down isolated development environments.

## Target audience
This feature request is for local development and for remote development using https://github.com/Microsoft/vscode-remote-release using visual studio code.

## Required changes

@jeanp413 said:
>vscode is the one who does the shell resolution internally [here](https://github.com/microsoft/vscode/blob/4580ba51fe1914ca29916f829adb35930089b013/src/vs/platform/shell/node/shellEnv.ts#L102), by default it will use the shell from $SHELL but if that's unset it will use node's userInfo().shell which will read /etc/passwd [source code](https://github.com/microsoft/vscode/blob/4580ba51fe1914ca29916f829adb35930089b013/src/vs/base/node/shell.ts#L40-L48)

My proposal for **resolving the shell command** would be:

1. vscode checks for a `.vscode-nix.toml` file which could look like this:
  ```toml
# .vscode-nix.toml
# This configuration file helps Visual Studio Code determine the shell to use for different Nix environments.

# Specify the shell to use for Nix Flake's 'nix develop'
[shell]
name = "nix flake"
command = "nix develop"

# Specify the shell to use for Devenv
#[shell]
#name = "devenv"
#command = "devenv shell"

# Specify the shell to use for Direnv
#[shell]
#name = "direnv"
#command = "direnv allow && direnv exec . $SHELL"

# Specify the shell to use for Nix Shell
#[shell]
#name = "nix-shell"
#command = "nix-shell"
```

2. if `.vscode-nix.toml` exists, vscode should use the command from there, to spawn all shells, instead of using the target systems SHELL variable (or the fallback). this should only be done if not in [restricted mode](https://code.visualstudio.com/docs/editor/workspace-trust).

vscode uses these types of shell currently: 

* the project build uses a shell (the user can't input anything into this shell)
* there is the 'terminal' button also, which spanws an interactive shell (this is not used by the project builder but instead only for the interactive changes by the user)

toml is just a proposal markup language, could be any other. I like it over json because it supports comments.

See details about the idea in: https://lastlog.de/blog/vscodium_and_nix_develop.html

# help and testing

If someone is interested in this proposal, I'd be happy to test the PR.
