### ISSUE TITLE
Outline matching selections instead of highlight

### ISSUE THREAD

**Issue by brandonk3nt** [Microsoft/vscode#21898]
- VSCode Version: 1.10.1
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Highlight a selection with multiple instances. 
2. Look how its hard to distinguish which instance is selected.
![screen shot 2017-03-03 at 7 33 55 am](https://cloud.githubusercontent.com/assets/10407384/23554994/7010bf52-ffe4-11e6-93b6-f520ab271150.png)
![screen shot 2017-03-03 at 7 36 55 am](https://cloud.githubusercontent.com/assets/10407384/23554996/7218d56e-ffe4-11e6-93d3-8611698f3665.png)

**Comment by Schw2iizer** [comment]
+1 for the change

**Comment by kenhoward** [comment]
+1

**Comment by csalv5** [comment]
Agree, It would be nice to let us choose the right setting (outline or selection).

**Comment by dpitskobooster** [comment]
+1

**Comment by bddenhartog** [comment]
That seems to be a theme coloring issue. Using the standard syntax theme, my current _selection(s)_ has a solid blue background. 

The issue reported in the OP _does_ occur when my cursor is placed within the bounds of a repeated word -- all instances of the word are highlighted in the same manner and opacity.

**Comment by brandonk3nt** [comment]
There are two fundamental issues with this feature request:

1. When you make a selection and there are multiple instances, it's extremely hard to distinguish which one is actually selected. The theme in the attached image above is a VSCode's standard Monokai theme. This is not a "theme" issue, users should be able to use any theme that is available in the marketplace. 

2. When you make a selection, matching instances shouldn't be highlighted at all. Being highlighted indicates that they are also selected, which is not the case. So when I double click on a single word to select it, all the matching instances get highlighted too, creating the appearance that they are all selected.

(Just providing a little more clarity on this issue)

**Comment by Cloud887** [comment]
Is there currently a way to deal with this now, because I can't seem to disable the highlighting matches in settings...?

**Comment by brunobely** [comment]
+1 for just outlines like in original post

**Comment by Enteleform** [comment]
Copying this here from #30793 (*closed/duplicate*) to provide additional context.

-----

# +1
This would make it much easier to create a high-visibility style for the active selection.

![comparison](https://user-images.githubusercontent.com/10906415/42095798-a6ecc330-7b81-11e8-92ea-a8e6fc72a0f7.png)

On a related note, the lack of `selectionForeground` for non-high-contrast themes is definitely a detriment to achieving the same effect.

-----

Also, I just noticed that the `selection` & `selectionHighlight` properties have kind of an odd behavior in relation to `addSelectionToNextFindMatch`.

When using `addSelectionToNextFindMatch`, the `selection` & `selectionHighlight` properties are both applied to each additionally selected match. I would expect `selection` properties to activate and `selectionHighlight` properties to deactivate in this case. The expected behavior is exhibited in the second half of the GIF, when multiple selections are made simultaneously.

![selection](https://user-images.githubusercontent.com/10906415/42096310-f5e7b6ba-7b82-11e8-9798-0b54f2a26c4c.gif)

&nbsp;  
Here is the same sequence of actions in SublimeText:

![selection2](https://user-images.githubusercontent.com/10906415/42096837-730b9d4a-7b84-11e8-8864-1499bcd2933d.gif)

**Comment by Enteleform** [comment]
On a related note, border `width` & `radius` options would be super nice to have.

**Comment by Enteleform** [comment]
Finally got around to giving this a go in userland and got decent results, although it'd definitely still be preferable for this to land as a fully supported set of features.

https://github.com/microsoft/vscode/assets/10906415/ada8d64f-1980-47b7-bdf3-4a8cbf6d2bb1

Implementation:
- [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css)
- various styles @ [workbench.colorCustomizations](https://code.visualstudio.com/api/references/theme-color)
- CSS:
  ```css
  /*###  Selection.Common  ###*/
  /* prevents border overlap, configured for my particular font settings. */
  .cdr.selectionHighlight,
  .cslr.selected-text{
    height: 17px !important;
  }
  /* hides extraneous leading/trailing selection edges. */
  /* `width` value might need to be changed to suit your font settings. */
  /* potentially could require additional workarounds if additional artifacts show up in specific contexts. */
  :is(
    .cdr.selectionHighlight,
    .cslr.selected-text
  )[style*="width:10px"]{
    display: none !important;
  }

  /*###  Selection.Matches  ###*/
  .cdr.selectionHighlight{
    border:        1px solid hsla(334, 100%, 60%, 45%) !important;
    border-radius: 4px !important;
  }

  /*###  Selection.Active  ###*/
  .cslr.selected-text {
    background-color: hsla(217, 50%, 58%, 20%)           !important;
    border:           1px solid hsla(217, 60%, 70%, 50%) !important;
    border-radius:    4px                                !important;
    pointer-events:   none                               !important;
    z-index:          1;
  }
  /* inactive pane. */
  .monaco-editor.focused .cslr.selected-text {
    background-color: hsla(217, 76%, 63%, 50%)            !important;
    border:           1px solid hsla(217, 100%, 60%, 78%) !important;
    border-radius:    4px                                 !important;
    opacity:          0.65                                !important;
    mix-blend-mode:   plus-lighter                        !important;
  }
  ```
