### ISSUE TITLE
códigos 



### ISSUE THREAD

**Issue by ptzjuh** [microsoft/vscode#218932]
### HTML
```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Heroes para Vilão</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="word">
        <span class="gold">H</span>
        <span class="gold">e</span>
        <span class="gold">r</span>
        <span class="gold">o</span>
        <span class="gold">e</span>
        <span class="gold">s</span>
        <span class="red">V</span>
        <span class="red">i</span>
        <span class="red">l</span>
        <span class="red">ã</span>
        <span class="red">o</span>
    </div>
</body>
</html>
```

### CSS (styles.css)
```css
.word {
    font-size: 2em;
    font-weight: bold;
    font-family: Arial, sans-serif;
}

.gold {
    color: gold;
}

.red {
    color: red;
}
```
