### ISSUE TITLE
Adapt to the .yml standard templates for new Github issues

### ISSUE THREAD

**Issue by timint** [microsoft/vscode#219906]
Hi, I found the Github issue templates less user friendly and would like to propose adapting the .yml standard.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

Example:

```
name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
       Please read our Rules of Conduct: https://opensource.microsoft.com/codeofconduct/
       🕮 Read our guide about submitting issues: https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
      🔎 Search existing issues to avoid creating duplicates.
       🧪 Test using the latest Insiders build to see if your issue has already been fixed: https://code.visualstudio.com/insiders/
      💡 Instead of creating your report here, use 'Report Issue' from the 'Help' menu in VS Code to pre-fill useful information.
      🔧 Launch with `code --disable-extensions` to check.
  - type: textarea
    attributes:
      label: Description
      description: "Please provide a minimal example how to reproduce the problem and describe the expected outcome and what the actual outcome was."
      value: |
        ### What where you trying to do?


        ### What happened?


        ### What did you expect to happen?


    validations:
      required: true
  - type: input
    id: vscode_version
    attributes:
      label: VS Code Version
      description: "What is the version of VS Code that produced this problem?"
      placeholder: "x.x.x"
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: OS Version
      description: "What is the OS version were you running VS Code on when the problem occured?"
      placeholder: ""
    validations:
      required: true
```
