### ISSUE TITLE
Macbook Air Closes Other Applications After Exiting Debug Mode in Node.js Project

### ISSUE THREAD

**Issue by Asbolus** [microsoft/vscode#223217]
Type: <b>Bug</b>

My Mac model is Macbook Air, M3 chip, with 16 GB of memory. While developing a Node.js project using Visual Studio Code, the screen refreshes and closes all applications except VS Code when I end the Debug mode. This is very troublesome. I am using the latest version of VS Code, and I have also reinstalled it, but the issue persists. Currently, I am running the development environment and the project inside Docker. The information provided below may help:

This is the launch.json file in VS Code:
```
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Attach to Node.js",
        "type": "node",
        "request": "attach",
        "port": 9229,
        "restart": false,
        "protocol": "inspector",
        "skipFiles": ["<node_internals>/**"],
        "localRoot": "${workspaceFolder}",
        "remoteRoot": "/usr/src/app"
      }
    ]
}
```

This is my docker-compose.yml file:
```
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ...
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis
    restart: always
    networks:
      - app-network

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /Users/{MyProject}:/usr/src/app
    working_dir: /usr/src/app
    command: node --inspect=0.0.0.0:9229 server.js
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
```

This is my Dockerfile:
```
FROM node:latest

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["node", "server.js"]
```

The debug process is as follows:

1. Start the containers using the command docker-compose up -d
2. Start debugging in VS Code
3. Call the API using Postman
4. Verify that breakpoints are working
5. Stop debugging
6. The screen refreshes, and other applications (Postman, Chrome, Orbstack, Terminal, etc.) are closed, leaving only VS Code running.

You can refer to the video as follows
[https://drive.google.com/file/d/1Sc81pv2i65teXEeOxkA4abFA39JqFzX8/view?usp=sharing](https://drive.google.com/file/d/1Sc81pv2i65teXEeOxkA4abFA39JqFzX8/view?usp=sharing)

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 8, 5|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 70bc82c3-1b72-43a7-bd6d-1f1b7eeac9f3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.29.1
vscode-language-pack-zh-hant|MS-|1.91.2024071009
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
legacy_priority:31094926
pythonrstrctxt:31093869

```

</details>
