### ISSUE TITLE
Feature request: highlight problem indicator with color when problems exist

### ISSUE THREAD

**Issue by poshcodebear** [Microsoft/vscode#22346]
- VSCode Version: 1.10.2
- OS Version: Windows 7 SP 1 & Windows 10

For a better callout (those icons aren't very noticeable normally), it would be nice if when there are errors or warnings detected, it highlighted the respective icon (yellow for warning, red for error).

**Comment by lashchev** [comment]
+1

**Comment by stevencl** [comment]
I don't know if this is possible, perhaps @sandy081 knows?

**Comment by sandy081** [comment]
@poshcodebear Not sure if I understand the request correctly. May I know what icon you would like to highlight?

**Comment by poshcodebear** [comment]
Absolutely.  Rather than trying to describe it, I've made a couple of screenshots (using PowerShell to create the sample).

The icons I'm referring to:
![image](https://user-images.githubusercontent.com/6439773/29586978-55745728-8741-11e7-8f0f-f19049ee7aac.png)

Showing them with some errors and warnings (note: they're easy to miss as only the numbers change):
![image](https://user-images.githubusercontent.com/6439773/29587020-77b77b26-8741-11e7-9296-329c0c4a443a.png)

A really bad, quick mockup of a way to make them stand out better (changing their color when they detect issues and errors):
![image](https://user-images.githubusercontent.com/6439773/29587061-961ccab2-8741-11e7-94c9-d526af66e3e8.png)

I hope that makes more sense.

**Comment by DragWx** [comment]
This would be nice. Instead of changing the color of the icon and number, maybe change the background color behind the indicator instead? It would stand out more and would be easier to read than color-on-color.

**Comment by poshcodebear** [comment]
> This would be nice. Instead of changing the color of the icon and number, maybe change the background color behind the indicator instead? It would stand out more and would be easier to read than color-on-color.

So, something like this?
![sample-1](https://user-images.githubusercontent.com/6439773/49242257-292e3f80-f3bf-11e8-898d-525fe68cde7f.png)

I re-did my original mockup with better colors as well for a more direct comparison:
![sample-2](https://user-images.githubusercontent.com/6439773/49242299-3f3c0000-f3bf-11e8-94f4-8bd2651862aa.png)

The red is still a bit hard to see in the icon color only changes, so probably should have picked a slightly darker red.

**Comment by DragWx** [comment]
Something like that, yeah, but thinking some more on it, being able to customize both would be helpful.

**Comment by usernamehw** [comment]
Not the best option but it's possible to hack it: [Custom CSS](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css)

```css
.task-statusbar-item-label-warning.mask-icon:not([title='0 Warnings']) {
	background-color: orange !important;
}
.task-statusbar-item-label-error.mask-icon:not([title='0 Errors']) {
	background-color: crimson !important;
}
```

**Comment by poshcodebear** [comment]
> 
> 
> Not the best option but it's possible to hack it: [Custom CSS](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css)
> 
> ```css
> .task-statusbar-item-label-warning.mask-icon:not([title='0 Warnings']) {
> 	background-color: orange !important;
> }
> .task-statusbar-item-label-error.mask-icon:not([title='0 Errors']) {
> 	background-color: crimson !important;
> }
> ```

I gave that a try and not only did that not work, it caused me to need to reinstall VSCode to undo and get it to stop warning me about an unsupported install.  For anyone thinking to try this, I don't recommend it.

**Comment by usernamehw** [comment]
Yeah, class names are not stable... Current code is:

```css
.statusbar-item[title*="Warning"] > a > .octicon-warning {
	color: #ff7300;
}
.statusbar-item[title*="Error"] > a > .octicon-error {
	color: #dd4653;
}
```
