### ISSUE TITLE
Unable to create new profile

### ISSUE THREAD

**Issue by hahavenn** [microsoft/vscode#224788]
Type: <b>Bug</b>

1. Click "Manage" button
2. Pick "Profile Default"
3. Pick "New Profile"
4. Remove one of checkboxes
5. Showed up warning-hint "The profile should contain at least one configuration"
6. Enter profile name
7. Choose "Copy from: Default"

Then try to check any of checkboxes, it doesn't checking. Button "Create" also doesn't work. Hint doesn't close

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

---

The workaround as @gregrobson pointed out please set in your settings
"workbench.experimental.enableNewProfilesUI": true

**Comment by hahavenn** [comment]
Also want to mention - i don't have any other profiles, only default

**Comment by hahavenn** [comment]
https://github.com/user-attachments/assets/ea5c7b5a-b2f3-4b0a-aacb-f048a629e641

here is video of this bug

**Comment by iYadavVaibhav** [comment]
Experiencing the same issue after update. I am on Mac M2 with following details:

```yaml
Version: 1.92.0 (Universal)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z (4 days ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0
```

**Comment by silascript** [comment]
same issue.

```yaml
版本: 1.92.0
提交: b1c0a14de1414fcdaa400695b4db1c0799bc3124
日期: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.6.41-1-MANJARO
```
