### ISSUE TITLE
expose `editor.emptySelectionClipboard` as a dedicated keybinding-command

### ISSUE THREAD

**Issue by goyalyashpal** [microsoft/vscode#225717]
### Scenario and Problem

 * i like the feature of being able to copy current line without any selection i.e. `editor.emptySelectionClipboard`
 * but i don't like the fact that it uses the same keybind as copy-selection

**problem:**

* this often results in important data from clipboard getting accidentally overwritten and hence, lost
* this is so grave that i am forced to disable this `editor.emptySelectionClipboard` altogether for the time being

so, having ability to pick a separate dedicated keybind for `editor.emptySelectionClipboard` will help a lot.

### Verbose/Detailed Wording:

* i want `C-c` to work only when there is some selection
* i don't want `C-c` to copy anything on empty selection
* i want to use the feature of "copy current line on empty selection" with some other keybind 
* but that other keybind or its event should NOT be inherently coupled to the normal "copy-selection" feature

### Versions

```yaml
Version: 1.88.1
Release: 24104
Commit: 0d01a72525276e5e3771fe5851b9c83de0de1e2b
Date: 2024-04-13T01:53:59.491Z
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.6.44
```
