### ISSUE TITLE
.winget files being labeled as YAML not being persisted between sessions

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#229877]
- VS Code Version: 1.93.1
- OS Version: Windows 11

Steps to Reproduce:

1. Open VS Code
2. Create x.winget file
3. Add YAML code 
```
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: install-dotnet8-SDK
      directives:
        description: Install .NET 8 SDK
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.SDK.8
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: install-vs-code
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.VSCode.DSC/VSCodeExtension
      id: install-csharp-dev-kit
      dependsOn:
        - install-vs-code
      directives:
        description: Install C# Dev Kit
        allowPrerelease: true
      settings:
        name: ms-dotnettools.csdevkit
        exist: true
  configurationVersion: 0.2.0
```
4. Click "Set Language Mode" in bottom right of Status Bar and switch to YAML
5. Save file 
6. Close VS Code
7. Reopen same file in VS Code
8. File is back to plain text and I have to switch the language back to YAML every time
