### ISSUE TITLE
Pre commit linters not working from integrated terminal

### ISSUE THREAD

**Issue by Juan6420** [microsoft/vscode#230599]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.0 (Universal)
- OS Version: macOS Sonoma 14.7

Steps to Reproduce:

1. Perform a `git commit`
2. In the terminal, it freezes when the `pre-commit-config.yaml` linters start to execute

This is the `pre-commit-config.yaml` content

```
repos:
  # Websec hook is MANDATORY, DO NOT comment it.
  - repo: git@github.com-emu:*****/*****
    rev: v2.0.0
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [post-commit]

  # Datasec hook is MANDATORY, DO NOT comment it.
  - repo: git@github.com-emu:*****/*****
    rev: 1.2.0
    hooks:
      - id: pre_commit_hook
        stages: [commit]
        verbose: true
      - id: post_commit_hook
        stages: [post-commit]

  # Next hooks are Code Quality hooks. 
  # If you want them to run on each commit, uncomment them
  # These are OPTIONAL.

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-golang
        args:
          - --autofix
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.61.0
    hooks:
      - id: golangci-lint
        entry: golangci-lint run
        args:
          - --max-issues-per-linter=0
          - --max-same-issues=0
          - --config=.code_quality/.unused.yaml
          - --new-from-rev=HEAD~1 # comment this arg if you want to run pre-commit run --all-files
      - id: golangci-lint
        entry: golangci-lint run
        args:
          - --max-issues-per-linter=0
          - --max-same-issues=0
          - --config=.code_quality/.custom_golangci.yml
          - --new-from-rev=HEAD~1 # comment this arg if you want to run pre-commit run --all-files
  - repo: https://github.com/*****/****-lint
    rev: v1.1.0
    hooks:
      - id: go-****-lint
        stages: [commit]
```

When I execute a commit this is the result in the integrated terminal:

![image](https://github.com/user-attachments/assets/b8d6666d-c5c0-4fd3-8a29-cbf17bbe6776)

It stays like this, no error or crash message. I tried to uninstall and reinstall all from scratch and didn't work. When I do the same process in other terminal like iTerm2 or other IDEs and the process works with no problem. Also I disabled the "optional hooks" and it works fine; no matter which hook I enable, it freezes the execution. I also tried installing the Apple Silicon version but it suggest me to install the native (Universal) version. Tested just with the Go extension and the problem persists
