### ISSUE TITLE
Error when parsing container queries with style queries

### ISSUE THREAD

**Issue by PupilTong** [microsoft/vscode#231087]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0
- OS Version: OSX 14.5

Steps to Reproduce:

https://developer.mozilla.org/en-US/docs/Web/CSS/@container#container_style_queries

Vscode reports a syntax error for `@container` with parentheses or comma in style queries, which is allowed in web standard.

![Image](https://github.com/user-attachments/assets/0ee37f73-3912-4248-a4e1-d9b44a9ab5e3)

**Comment by PupilTong** [comment]
The same issue reproduced in 1.94.2.

Also, using `or` after `and` could cause the same issue.

```css
@container style(--bg-a:true) and style(--bg-b:true) or style(--bg-c:true) {
  div {
    background-color:blue;
  }
}
```
