### ISSUE TITLE
Support Using  `...` To Terminate Markdown Yaml FrontMatter

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#23178]
From http://stackoverflow.com/questions/42995660/vscode-issues-with-syntax-highlighting-for-yaml-headers-in-markdown

Support Frontmatter that is terminated by `...`:

```yaml
---
title: Best Article Ever
author: Great Writer
...
```
