### ISSUE TITLE
Bring Source Control Repositories back (Split Source Control) or make option to do so

### ISSUE THREAD

**Issue by classicrocker883** [microsoft/vscode#234748]
```yml
Version: 1.95.3 (system setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631
```
I do not know when this change happened, because it seemed to be overnight - sometime during 11/26/2024
I do not recall having VSCode update at all where this change happened out of nowhere.

So how it used to be, **Source Control** had several different panels - One being called `Source Control Repositories`, below that `Source Control`.

The repositories were grouped separately - one for each line/row, from which different branches could be chosen, refreshed, and all other things to be done with the `...` (3-dots).  
But now, there is a drop down for each repository `>` (arrow). Which congests things especially for having more than one.

I miss having being able to select each repository one by one and having their (now drop-down contents) being in a separate pane (window block) - which was called `Source Control`.

With the current version, having multiple repositories can be hard to differentiate which one you want to focus on.

---

Please give the option for us to be able to bring that view type back
