### ISSUE TITLE
Did something change in Uri?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#236122]
I have multiple gutter icons which are generated using Uri + SVG:

```ts
function svgToUri(svg: string): Uri {
	return Uri.parse(`data:image/svg+xml;utf8,${svg}`);
}
```

Some of them work like square shapes, but emojis don't (in **1.96.0** specifically).

```ts
// square icon
function createSquareIcon(color: string, rx = 0): string {
	return `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" height="40" width="40"><g transform="translate(12, 12)"><rect width="16" height="16" rx="${rx}" fill="${escapeColor(color)}"/></g></svg>`;
}
// emoji icon
function createEmojiIcon(emojiSymbol: string): string {
	fontFamily = fontFamily ? fontFamily : workspace.getConfiguration('editor').get('fontFamily') ?? '';
	return `<svg viewBox="-10 -6 20 10" xmlns='http://www.w3.org/2000/svg' width='16' height='16'><text font-family="${fontFamily}" text-anchor="middle" dominant-baseline="middle">${emojiSymbol}</text></svg>`;
}
```
Which generates broken CSS for emoji icon?
```css
body {
/* Square icon */
background: url("data:image/svg+xml;utf8,<svg viewBox=\"0 0 40 40\" xmlns=\"http://www.w3.org/2000/svg\" height=\"40\" width=\"40\"><g transform=\"translate(12, 12)\"><rect width=\"16\" height=\"16\" rx=\"3\" fill=\"%23e45454\"/></g></svg>") center center / 100% no-repeat;
/* Emoji icon */
background: url("data:image/svg+xml;utf8,<svg viewBox=\"-10 -6 20 10\" xmlns='http://www.w3.org/2000/svg'width='16'height='16'><text font-family=\"Liga Consolas, Consolas, Segoe UI Emoji\" text-anchor=\"middle\" dominant-baseline=\"middle\">💀</text></svg>") center center / 100% no-repeat;
}
```

It seems like the problem is with using single quotes `'`: when changed to double quotes `"` - then it works. 

Maybe it's an issue with `Uri` or is this a new requirement to only use double quotes?

- VS Code Version: 1.96.0
- OS Version: Windows 23H2
