### ISSUE TITLE
[less and scss] inner media query can't understand lines which begins with `>`

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode#23862]
VSCode version 1.10.2

This is valid LESS and SCSS:
```scss
.something {
    @media (max-width: 760px) {
        > .test {
            color: blue;
        }
    }
}
```

However VSCode recognizes this as error:

![image](https://cloud.githubusercontent.com/assets/64731/24616265/4938b100-1899-11e7-921c-74a5e735da49.png)
