### ISSUE TITLE
Icons in chat references show repeated background patterns

### ISSUE THREAD

**Issue by jleong-stripe** [microsoft/vscode#239039]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96.2
- OS Version: Sequoia 15.2

**Title:**
Icons in chat references show repeated background patterns 

**Description:**
When using `stream.reference()` with custom SVG icons in Copilot Chat, the icons appear repeated horizontally instead of showing as a single instance.

**Steps to reproduce:**
1. Create a custom SVG icon
2. Use it in a chat reference:
```typescript
stream.reference(vscode.Uri.parse(url), iconSvg)
```

**Current behavior:**
The SVG icon appears multiple times horizontally, creating an unintended repeating pattern.

**Expected behavior:**
The icon should appear only once and be properly centered in its container.

**Suggested fix:**
Add the following CSS properties to the icon container:
```css
{
  background-repeat: no-repeat;
  background-position: center;
  background-size: contain;
}
```
