### ISSUE TITLE
SCM - Binary File Diff does not show in Combined Working Diff, Combined Staged Diff or Commit Diff

### ISSUE THREAD

**Issue by ADTC** [microsoft/vscode#240266]
### Correct observation:

Binary Files show as added, renamed, changed or deleted in the working tree diff and the staged diff if each individual binary file is _**viewed separately.**_

<img width="589" alt="Image" src="https://github.com/user-attachments/assets/b8413b29-9ae4-4bcb-ac23-63d943e62977" />

### Incorrect observation and Problem:

Binary Files do not show **at all** in the combined working tree diff, combined staged changes diff or in the commit diff. If such a diff has **_only_** binary file changes, the diff shows "No Changed Files" which is incorrect and misleading.

<img width="589" alt="Image" src="https://github.com/user-attachments/assets/2d3dcc39-8177-48c9-a0cd-72a795187989" />

<img width="618" alt="Image" src="https://github.com/user-attachments/assets/e301fa8a-6ef7-4628-8607-af5224b2aaad" />

<img width="621" alt="Image" src="https://github.com/user-attachments/assets/3ce233ba-03b5-430b-9c7c-cdfd0d9dadc0" />

### Steps to Reproduce:

1. Add, rename, change or delete a binary file (such as an image).
2. View the working tree changes as a combined diff by clicking "Open Changes" button in "Source Control" pane.
3. Stage the changes.
4. View the staged changes as a combined diff by clicking "Open Staged Changes" button in "Source Control" pane.
5. Commit the changes.
6. View the diff of the commit by clicking on it in the "Source Control Graph" pane.

**Note:** Steps 2, 4 and 6 show the same problem in various states.

### Additional information:

**Sample Repository to test with:** https://github.com/ADTC/vscode-binary-diff-sample-repo/commits/main/ 

```sh
git clone https://github.com/ADTC/vscode-binary-diff-sample-repo.git
cd vscode-binary-diff-sample-repo
code .
```

Tip: [You can grab some sample images here.](https://github.com/yavuzceliker/sample-images/tree/main/images)

**Does this issue occur when all extensions are disabled?:** Yes (I confirm that I tried it with `code --disable-extensions` and the problem persists.)

**System Information:**

```yaml
Version: 1.97.0
Commit: 33fc5a94a3f99ebe7087e8fe79fbe1d37a251016
Date: 2025-02-04T22:41:26.688Z (5 days ago)
Electron: 32.2.7
ElectronBuildId: 10660205
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0
```
