### ISSUE TITLE
Each first nested rule isn't highlighted properly

### ISSUE THREAD

**Issue by Tlepel** [microsoft/vscode#240384]
Type: <b>Bug</b>

1. Create a css file
2. Add a rule
3. Nest a few rules inside

Example:

```css
.useful-class {
    .rule-without-highlight {
        background-color: red;
    }

    .rule-with-highlight {
        background-color: green;
    }
}

useful-selector {
    selector-without-highlight {
        background-color: red;
    }

    selector-with-highlight {
        background-color: green;
    }
}

:first {
    :first-child {
        background-color: red;
    }

    :last-child {
        background-color: green;
    }
}
```

---

VS Code version: Code - Insiders 1.98.0-insider (21525b01bf68bf9250cb856f192628fffc449234, 2025-02-11T05:04:43.535Z)
OS version:   
Modes:

System Info: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
anycode-kotlin|ms-|0.0.5
anycode|ms-|0.0.73
anycode-python|ms-|0.0.5
anycode-java|ms-|0.0.5
anycode-cpp|ms-|0.0.5
anycode-typescript|ms-|0.0.5
anycode-go|ms-|0.0.5
anycode-c-sharp|ms-|0.0.5
anycode-php|ms-|0.0.6
anycode-rust|ms-|0.0.6
remotehub|Git|0.65.2024112101
remote-explorer|ms-|0.5.2025010909
remote-repositories|ms-|0.43.2024112101
codespaces|Git|1.17.3
remote-server|ms-|1.6.2025010809
azure-repos|ms-|0.41.2024112101

</details>
