### ISSUE TITLE
Remove scrollbar arrows in detailed suggestion

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2412]
Testing #2230 

Can you try to remove the arrows?

![image](https://cloud.githubusercontent.com/assets/5047891/12607999/525f58d4-c4d9-11e5-92bb-9ad14c3c9f2f.png)

**Comment by joaomoreno** [comment]
Duplicate of #1928

**Comment by alexandrudima** [comment]
Sorry I wasn't clear. This is what I mean:

```css
your dom node::-webkit-scrollbar-button {
    width: 0;
    height: 0;
    display: none;
}
```
