### ISSUE TITLE
Message: Request textDocument/completion failed with message: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jsoref** [microsoft/vscode#242815]
Type: <b>Bug</b>

I'm slowly typing and cmd-space completing by hand large portions of this workflow:

```yaml
name: CI
on:
  push:
  workflow_dispatch: 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-arch:
    name: Build
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}
    outputs:
      attestation-url: ${{ steps.attestation.outputs.attestation-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        id: attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  combine-images:
    name: Combine images
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
```

Most of the messages appear to be from the GitHub Actions Workflow extension, but the `textDocument/completion` item seems more exciting/problematic.

```
[Error - 10:35:40 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Maximum call stack size exceeded
  Code: -32603 
[Error - 10:36:41 AM] Failed to fetch action metadata for actions/checkout/v: 'No commit found for the ref v'
[Error - 10:37:26 AM] Failed to fetch action metadata for actions/c/undefined: 'Not Found'
[Error - 10:41:10 AM] Failed to fetch action metadata for docker/login-action/65b78e6e13v3.3.0532edd9afa3aa52ac7964289d1a9c1: 'No commit found for the ref 65b78e6e13v3.3.0532edd9afa3aa52ac7964289d1a9c1'
[Error - 10:41:19 AM] Failed to fetch action metadata for docker/login-action/v3.: 'No commit found for the ref v3.'
[Error - 10:43:09 AM] Failed to fetch action metadata for docker/metadata-action/v: 'No commit found for the ref v'
[Error - 10:45:19 AM] Failed to fetch action metadata for docker/build-push-action/v: 'No commit found for the ref v'
```

VS Code version: Code 1.97.2 (Universal) (e54c774e0add60467559eb0d1e229c6452cf8447, 2025-02-12T23:20:35.343Z)
OS version: Darwin arm64 24.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|6, 7, 7|
|Memory (System)|64.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 1fc67ee2-0174-4598-9f98-4537df0dd32c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
quitcontrol-vscode|art|4.0.0
asciidoctor-vscode|asc|3.4.2
yamlfmt|blu|0.1.4
vscode-intelephense-client|bme|1.14.3
open-in-macdown|Cod|1.0.0
intelli-php-vscode|DEV|0.12.15062
dhall-lang|dha|0.0.4
vscode-dhall-lsp-server|dha|0.0.4
EditorConfig|Edi|0.17.1
html-preview-vscode|geo|0.2.5
vscode-github-actions|git|0.27.1
vscode-pull-request-github|Git|0.107.2025030604
go|gol|0.46.1
terraform|has|2.34.3
file-downloader|min|1.0.13
vscode-kubernetes-tools|ms-|1.3.20
sarif-viewer|MS-|3.4.4
vscode-dhall-lsp-server|pan|0.0.4
vscode-xml|red|0.28.0
vscode-yaml|red|1.17.0
rst-vscode|tht|3.0.1
simple-rst|tro|1.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dwnewjupytercf:31046870
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
iacca1:31171482
5fd0e150:31155592
dwcopilot:31170013
6074i472:31201624
dwoutputs:31242946
customenabled:31248079
5a9hg449:31230677
hdaa2157:31222309
copilot_t_ci:31222730
jda6j935:31233686

```

</details>
