### ISSUE TITLE
Feedback: variables render differently in Insiders

### ISSUE THREAD

**Issue by mrleemurray** [microsoft/vscode#244579]
Testing: #244445 

Snippet:

``` css
#app {
		box-sizing: border-box;
		margin: 0 auto;
		display: flex;
		flex-direction: column;
		height: 100%;
		background-color: var(--figma-color-bg);
		color: var(--figma-color-text);
 }
```

Insiders:

<img width="365" alt="Image" src="https://github.com/user-attachments/assets/24c371e7-aaa3-4090-8ed2-87c80630c517" />

Stable:

<img width="344" alt="Image" src="https://github.com/user-attachments/assets/e71df313-f4ae-4b8f-bedf-d674280dcd24" />

Theme: Dark+
