### ISSUE TITLE
Feedback: universal selectors not rendering with syntax highlighting

### ISSUE THREAD

**Issue by mrleemurray** [microsoft/vscode#244574]
Testing #244445 

Universal selectors (*) are not rendering correctly.

Insiders

<img width="251" alt="Image" src="https://github.com/user-attachments/assets/8c58dd7b-81ef-461c-bc0c-06b193864dd0" />

Stable

<img width="243" alt="Image" src="https://github.com/user-attachments/assets/bd85cb7f-d9e0-4be3-a2fc-b46221b5396d" />

Snippet:

``` css
div > * + * {
    margin-top: 4rem;
}

* {
    box-sizing: border-box;
}
```

Theme: Dark+
