### ISSUE TITLE
Feedback: before / after selectors not rendering correctly

### ISSUE THREAD

**Issue by mrleemurray** [microsoft/vscode#244575]
Testing #244445 

Before & After psuedo-element selectors (specifically the double colons) rendering differently in Insiders.

Snippet:

``` css
.border span::after {
	top: -2px;
}
.border span::before {
	bottom: -2px;
}
```

Insiders

<img width="214" alt="Image" src="https://github.com/user-attachments/assets/87876af7-2b7c-4228-884f-70e041b4f921" />

Stable

<img width="221" alt="Image" src="https://github.com/user-attachments/assets/1a026939-2a56-4568-8576-3e78e71a5a51" />

Theme: Dark+
