### ISSUE TITLE
Feedback: custom elements render differently

### ISSUE THREAD

**Issue by mrleemurray** [microsoft/vscode#244583]
Testing: #244445 

Custom elements render differently in Insiders (imho better as it aligns with the other selectors) than Stable

Snippet

``` css
figma-help-bubble {
	position: absolute;
	right: 16px;
	bottom: 16px;
}
```

Insiders

<img width="227" alt="Image" src="https://github.com/user-attachments/assets/e59916de-a90a-4b7f-a343-64f787dc8699" />

Stable

<img width="236" alt="Image" src="https://github.com/user-attachments/assets/56bcd367-989d-4262-a11d-7681df6d00d9" />

Theme: Dark+
