### ISSUE TITLE
Feedback: ID selectors not receiving syntax highlighting

### ISSUE THREAD

**Issue by mrleemurray** [microsoft/vscode#244568]
Testing #244445 

I was expecting the id selector to render in the same way as the class selector (it works in stable).

Snippet:

``` css
#someid { 
    color: green; 
    font-weight: bold;
    text-decoration: underline;
}
```

<img width="297" alt="Image" src="https://github.com/user-attachments/assets/364ebc75-2526-4add-ae4c-330f521ec012" />

Theme: Dark+
