### ISSUE TITLE
Feedback: webkit property rendering differently

### ISSUE THREAD

**Issue by mrleemurray** [microsoft/vscode#244582]
Testing: #244445 

Webkit properties rendering differently (imho better) in Insiders than Stable.

Snippet:

``` css
#layout {
    display: flex;
    flex-direction: row;
    height: 100%;
    overflow: hidden;
    width: -webkit-fill-available;
}
```

Insiders

<img width="284" alt="Image" src="https://github.com/user-attachments/assets/9dcf39b4-5105-4489-a337-b61d0b8ea6cc" />

Stable

<img width="298" alt="Image" src="https://github.com/user-attachments/assets/4b13e228-ae1c-445b-9d1e-427eb4328b20" />

Theme: Dark+
