### ISSUE TITLE
Feedback: Shadow DOM selectors render differently in Insiders

### ISSUE THREAD

**Issue by mrleemurray** [microsoft/vscode#244584]
Testing: #244445 

Shadow DOM selector of elements render differently (imho better) in Insiders than Stable.

Snippet:

``` css
figma-select::part(listbox) {
	max-height: 250px;
}
```

Insiders

<img width="231" alt="Image" src="https://github.com/user-attachments/assets/3f1b024b-6dc8-4b8f-8980-f42033a50d47" />

Stable

<img width="245" alt="Image" src="https://github.com/user-attachments/assets/984d5ff2-977a-4369-a148-d77b3335cfaa" />

Theme: Dark+
