### ISSUE TITLE
@view-transition css selector different color

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/vscode#244678]
Testing https://github.com/microsoft/vscode/issues/244445

Theme: Dark Modern

_This selector is not fully supported yet (thus the warning), but there's still a difference in syntax highlighting._

Stable:

<img width="535" alt="Image" src="https://github.com/user-attachments/assets/978409e0-d6f9-41c0-a541-595c46ecc893" />

Insiders:

<img width="563" alt="Image" src="https://github.com/user-attachments/assets/b7669602-0a8b-42ff-bdbe-84871aad034c" />

```css
@view-transition {
  navigation: auto;
}
```

**Comment by hawkticehurst** [comment]
Related: A few more `@selector` selectors have the same issue.

### `@starting-style`

Stable:

<img width="520" alt="Image" src="https://github.com/user-attachments/assets/a3b55502-8e09-4557-8e63-d29eba770449" />

Insiders:

<img width="286" alt="Image" src="https://github.com/user-attachments/assets/9843902c-41ec-477c-b222-47d3c987aad1" />

```css
@starting-style {
  [popover]:popover-open {
    opacity: 0;
    transform: scaleX(0);
  }
}
```

### `@layer`

Stable:

<img width="298" alt="Image" src="https://github.com/user-attachments/assets/0ea43de5-95ed-4be4-865c-d86eec4f8fdc" />

Insiders:

<img width="285" alt="Image" src="https://github.com/user-attachments/assets/6ed12558-f217-44d5-bce9-aa5cc09b4517" />

```css
@layer reset {
  * {
    box-sizing: border-box;
    margin: 0;
  }
}
```

**Comment by alexr00** [comment]
### `@starting-style`

Stable:

<img width="520" alt="Image" src="https://github.com/user-attachments/assets/a3b55502-8e09-4557-8e63-d29eba770449" />

Insiders:

<img width="286" alt="Image" src="https://github.com/user-attachments/assets/9843902c-41ec-477c-b222-47d3c987aad1" />

```css
@starting-style {
  [popover]:popover-open {
    opacity: 0;
    transform: scaleX(0);
  }
}
```

@hawkticehurst, what do you thing the coloring of `popover-open` should be? Is it a tag or a class?
