### ISSUE TITLE
@media css selector different color

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/vscode#244674]
Testing https://github.com/microsoft/vscode/issues/244445

Theme: Dark Modern

_I actually think Insiders is more correct here, but it's a difference none the less._

Stable:

<img width="478" alt="Image" src="https://github.com/user-attachments/assets/5e8d233a-9b4e-4c6f-8057-de06f2575db6" />

Insiders:

<img width="488" alt="Image" src="https://github.com/user-attachments/assets/ee45c54c-7baf-442e-9d6e-462cf9eb8490" />

```css
@media (prefers-reduced-motion: no-preference) {
  .animation {
    transition: transform 1s ease-in;
  }
}

@media (prefers-color-scheme: light) {
  :root {
    --background-color: white;
    --text-color: black;
  }
}

@media (prefers-color-scheme: dark) {
  :root {
    --background-color: black;
    --text-color: white;
  }
}
```
