### ISSUE TITLE
Mouse cursor changed to 'copy', is not reverting back

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#24602]
- VSCode Version: 1.12-insider
- OS Version: 66546c

I was editing some code, and at some point in time, the cursor became a weird symbol - an arrow with a plus at it's top-right. I inspected, and it's coming from: 

```css
.monaco-editor.hc-black.mac.mouse-copy .view-lines, .monaco-editor.mouse-copy .view-lines, .monaco-editor.vs-dark.mac.mouse-copy .view-lines {
  cursor: copy
}
```
with the `.monaco-editor.mouse-copy .view-lines` being the active class.

I don't understand how the editor went into that state. When I open a new file, the normal `text` cursor shows up.
