### ISSUE TITLE
Allow disabling italics for ghost text (e.g. Copilot suggestions)

### ISSUE THREAD

**Issue by talovski** [microsoft/vscode#246248]
Please, allow disabling italics for ghost text (e.g. Copilot predictions / suggestions). 

Reasoning for this is two-fold:
- Accessibility. It's hard for me to read italics, 
- not all fonts provide italics. Since VS Code is based on Chromium, it can emulate faux italics, but usually it doesn't look great.

Currently, it's not possible to define it via settings, since it's hardcoded here:

`src/vs/editor/contrib/inlineCompletions/browser/view/ghostText/ghostTextView.css`:

```css
.monaco-editor .ghost-text-decoration,
.monaco-editor .suggest-preview-text .ghost-text {
  font-style: italic;
}
```

As VS Code adds support for multiple font sizes and allows users to select different font family for inline suggestions and inlay hints, it seems logical to also allow users to select font style.

Another solution is to allow disabling all italics and / or bold globally via settings, e.g. `editor.fontStyles` or something.
