### ISSUE TITLE
Powershell Terminal Shell Integration Removes whole line when completing

### ISSUE THREAD

**Issue by Nova38** [microsoft/vscode#246533]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.99.2 / insiders 1.100.0
- OS Version: Windows 11

I use OhMyPosh as my prompt in powershell. When I enable the new terminal suggestions with OhMyPosh, when i go to tab complete it removes the whole line before the suggestion. I think the shell integration is getting confused and maybe escaping charters that are used to mark where the prompt starts or something. It doesn't erase any of the prompt parts though. It just replaces the commands text and leaves just the completions. If i disable ohmyposh it works fine. I have even tried moving the call to the shell intigration into my profile like the docs said might have to be done for a more complex prompt, but it didn't end up affecting this issue.

Steps to Reproduce:

1. Install and add OhMyPosh to the powershell profile
2. Enable terminal Shell Integration and Integrated>Suggest:enabled
3. Open the integrated powershell terminal.
4. Start typing command, then use a suggested auto complete. Ideally one that is a flag completion
5. After tab completing it the line should end up being cleared except for the completion. (The stuff before it get's removed.)    

The error seems to be in the Shell integration script.

[https://github.com/microsoft/vscode/blob/cf08d5b215b7c2f27331c32846149d90bdd97442/src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1#L152C1-L182C2](https://github.com/microsoft/vscode/blob/cf08d5b215b7c2f27331c32846149d90bdd97442/src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1#L152C1-L182C2)

**Comment by Nova38** [comment]
Ah I am sorry if I was not clear, the issue is with the terminal suggest portion of the pwsh shell integration. The issue went away when I used the generic prompt and a very simple custom prompt.

**Comment by anthonykim1** [comment]
@meganrogge Do you know if oh-my-posh is officially supported for terminal suggest?

**Comment by meganrogge** [comment]
Yes, it is. @anthonykim1 Certain prompts can still cause issues. @Nova38, can you share yours?

**Comment by Nova38** [comment]
Sure thing. It is pretty close to one of the defaults. I have also tide disabling the tooltip part. 

It is a little weird that it is happening as it doesn't erase any part of the prompt. Using tab complete just eats the whole line that was currently being typed. I have tried toggling the iterm_features and the ohmyposh shell integration.

```toml
console_title_template = '{{ .Folder }}'
version                = 3
auto_upgrade           = true
final_space            = true
patch_pwsh_bleed       = true
# iterm_features    = ["prompt_mark", "current_dir", "remote_host"]
# shell_integration         = true
enable_cursor_positioning = true


[palette]
git-foreground = "#193549"
git            = "#FFFB38"
git-modified   = "#FF9248"
git-diverged   = "#FF4500"
git-ahead      = "#B388FF"
git-behind     = "#B388FF"
fg-light       = "#011627"
red            = "#FF0000"
green          = "#21c7a8"
blue           = "#0000FF"
white          = "#FFFFFF"
black          = "#111111"
light-blue     = "#CAF0F8"
dark-blue      = "#023E8A"
# foreground     = "p:light-blue"
# background     = "p:dark-blue"

[[blocks]]
type      = 'prompt'
alignment = 'left'

  [[blocks.segments]]
  leading_diamond  = '╭─'
  trailing_diamond = ''
  template         = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '
  foreground       = 'p:fg-light'
  background       = "p:green"                                 #'#21c7a8'
  type             = 'os'
  style            = 'diamond'

    [blocks.segments.properties]
    windows = ''

  [[blocks.segments]]
  leading_diamond  = ''
  trailing_diamond = ''
  template         = ' {{ .Name }} '
  foreground       = 'p:fg-light'
  background       = '#d6deeb'
  type             = 'shell'
  style            = 'diamond'


  [[blocks.segments]]
  template         = '  '
  foreground       = '#ffeb95'
  powerline_symbol = ''
  background       = '#ef5350'
  type             = 'root'
  style            = 'powerline'

  [[blocks.segments]]
  template         = '{{ path .Path .Location }}'
  foreground       = '#011627'
  powerline_symbol = ''
  background       = '#82AAFF'
  type             = 'path'
  style            = 'powerline'

    [blocks.segments.properties]
    folder_icon           = ' '
    folder_separator_icon = '<#011627></> '
    home_icon             = '  '
    style                 = 'agnoster'

  [[blocks.segments]]
  # template = ' {{ url .UpstreamIcon .UpstreamURL }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
  type = 'git'
  powerline_symbol = ''
  style = 'powerline'
  foreground = "p:git-foreground"
  background = "p:git"
  background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}p:git-modified{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:git-diverged{{ end }}",
    "{{ if gt .Ahead 0 }}p:git-ahead{{ end }}",
    "{{ if gt .Behind 0 }}p:git-behind{{ end }}",
  ]

    [blocks.segments.properties]
    branch_icon          = ' '
    fetch_stash_count    = true
    fetch_status         = true
    fetch_upstream_icon  = true
    fetch_worktree_count = true

  [[blocks.segments]]
  leading_diamond  = '<transparent,#575656></>'
  trailing_diamond = ''
  template         = ' {{ .FormattedMs }}'
  foreground       = '#d6deeb'
  background       = '#575656'
  type             = 'executiontime'
  style            = 'diamond'

    [blocks.segments.properties]
    style     = 'roundrock'
    threshold = 0.0

[[blocks]]
type      = 'prompt'
alignment = 'right'
overflow  = 'hide'


  [[blocks.segments]]
  leading_diamond  = ''
  trailing_diamond = '<transparent,#0e0e0e></>'
  template         = '  {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }} '
  foreground       = '#0d6da8'
  background       = '#0e0e0e'
  type             = 'dotnet'
  style            = 'diamond'

  [[blocks.segments]]
  leading_diamond  = ''
  trailing_diamond = '<transparent,#ffffff></>'
  template         = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
  foreground       = '#06aad5'
  background       = '#ffffff'
  type             = 'go'
  style            = 'diamond'

  [[blocks.segments]]
  leading_diamond  = ''
  trailing_diamond = '<transparent,#316ce4></>'
  template         = ' {{.Context}} :: {{if .Namespace}}{{.Namespace}}{{else}}default{{end}} '
  foreground       = '#ffffff'
  background       = '#316ce4'
  type             = 'kubectl'
  style            = 'diamond'

  [[blocks.segments]]
  leading_diamond  = ''
  trailing_diamond = '<transparent,#303030></>'
  template         = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
  foreground       = '#3C873A'
  background       = '#303030'
  type             = 'node'
  style            = 'diamond'

    [blocks.segments.properties]
    fetch_package_manager = true
    npm_icon              = '<#cc3a3a></> '
    yarn_icon             = '<#348cba></> '

  [[blocks.segments]]
  type             = 'python'
  template         = '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
  style            = 'diamond'
  leading_diamond  = ''
  trailing_diamond = '<transparent,#306998></>'
  foreground       = '#FFE873'
  background       = '#306998'

  [[blocks.segments]]
  leading_diamond  = ''
  trailing_diamond = '<transparent,#ffffff></>'
  template         = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
  foreground       = '#000000'
  background       = '#ffffff'
  type             = 'rust'
  style            = 'diamond'

  # [[blocks.segments]]
  #   leading_diamond  = ''
  #   trailing_diamond = ''
  #   template         = ' {{ .CurrentDate | date .Format }}'
  #   foreground       = '#d6deeb'
  #   background       = '#234d70'
  #   type             = 'time'
  #   style            = 'diamond'

  #   [blocks.segments.properties]
  #     time_format = '15:04:05'

[[blocks]]
type      = 'prompt'
alignment = 'left'
newline   = true

  [[blocks.segments]]
  template   = '╰─'
  foreground = '#21c7a8'
  type       = 'text'
  style      = 'plain'

  [[blocks.segments]]
  template             = ''
  foreground           = '#22da6e'
  background           = 'transparent'
  type                 = 'status'
  style                = 'plain'
  foreground_templates = ['{{ if gt .Code 0 }}#ef5350{{ end }}']

    [blocks.segments.properties]
    always_enabled = true


[[tooltips]]
type             = "git"
tips             = ["git", "g"]
style            = "diamond"
foreground       = "#193549"
background       = "#fffb38"
leading_diamond  = ""
trailing_diamond = ""

templates = [
  "{{ .HEAD }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}",
  "{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}",
  "{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}",
]

  [tooltips.properties]
  fetch_status        = true
  fetch_upstream_icon = true
```
