### ISSUE TITLE
code.cmd --list-extensions --show-versions' failed

### ISSUE THREAD

**Issue by stvpwrs** [microsoft/vscode#247315]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
Name                                Id                         Version Source
------------------------------------------------------------------------------
Microsoft Visual Studio Code (User) Microsoft.VisualStudioCode 1.99.3  winget
```
- OS Version:
```
Edition	Windows 11 Home
Version	24H2
Installed on	‎2/‎13/‎2025
OS build	26100.3476
Experience	Windows Feature Experience Pack 1000.26100.54.0
```
Description:

When attempting to use a winget configuration file to install Visual Studio Code extensions the following error is produced:
```
The configuration unit failed while attempting to test the current system state.
Executing 'C:\Users\<user name>\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd --list-extensions --show-versions' failed. Command Output: '(node:21512) [DEP0168] DeprecationWarning: Uncaught N-API callback exception detected, please run node with option --force-node-api-uncaught-exceptions-policy=true to handle those exceptions properly.\n (Use `Code --tra…
<See the log file for additional details>
Some of the configuration was not applied successfully.
```

Steps to Reproduce:

1. Create a winget configuration file:
```
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Visual Studio Code
      directives:
        description: Install Visual Studio Code
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.VSCode.Dsc/VSCodeExtension
      id: ms-python.python
      dependsOn:
        - Visual Studio Code
      directives:
        description: Install Python Visual Studio Code extension
        allowPrerelease: true
      settings:
        name: ms-python.python
        exist: true
  configurationVersion: 0.2.0
```
2. Run the following winget command:
```
winget configure --file <path to winget configuration file>
```
