### ISSUE TITLE
Buggy CSS Syntax Highlighting With GitHub Theme

### ISSUE THREAD

**Issue by fweth** [microsoft/vscode#248492]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.101.0-insider
- OS Version: 24.04

Steps to Reproduce:

1. Install GitHub Theme extension
2. Write some nested CSS code, like this:

```css
.recent-posts {
  grid-column: 3;
  grid-row: 2;
  padding-top: 6.2rem;
  padding-right: 2rem;
  h2 {
    margin: 0 0 1rem;
  }
  ul {
    padding: 0;
  }
  li {
    list-style: none;
  }
}
```

3. Syntax highlighting appears buggy, see e.g. the h2:

![Image](https://github.com/user-attachments/assets/f88c0a6c-a2b3-49a7-9359-ba0c5fd74b4c)
