### ISSUE TITLE
Sticky Scroll scope line does not work well is scope is defined in multiple lines

### ISSUE THREAD

**Issue by AdamKlob** [microsoft/vscode#252138]
When scope definition has multiple lines, Sticky scroll shows the last line from the scope definition. Consider following code (and it's formatting):

class A
{
somePrefixes
VeryImportantFunctionWith(a, lot,
of, arguments, in,
multiple, lines)
{
//... function code ... //
}
}

If cursor is in function code, Sticky lines will show following:

class A
multiple, lines)

Which is not very helpfull. Much better solution would be showing information based on context, in this case function name this:

class A
VeryImportantFunctionWith(a, lot,

(and maybe show whole function definiution in tool tip on hoover)

**Comment by urobasa** [comment]
Yes
```
- name: qqqq
  display_name: wwww
  type: service
  required: true
  description: "werwer sdfsdf"
  version: 10
  actions:
    Install: run
      allow_terminate: true
      type: task
      scripts:
```

After scroll i see only first and last line in upper stiky block - 


```
- name: qqqq
  actions:
    Install: run
      allow_terminate: true
      type: task
      scripts:
```

i need configuration parameter how many line show in upper sticky for block.
