### ISSUE TITLE
Error running rename in CSS

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#25623]
* have the CSS file below
* select `.bar` selector
* trigger rename, enter new name
* 💥 an error shows

```
item.changes.forEach is not a function: TypeError: item.changes.forEach is not a function
    at asWorkspaceEdit (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\css\node_modules\vscode-languageclient\lib\protocolConverter.js:287:22)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

```css
.foo .bar {
    color: blue;
}

.far .bar {
    color: red;
}
```
