### ISSUE TITLE
[SCSS] Reporting errors when code is correct

### ISSUE THREAD

**Issue by hinok** [Microsoft/vscode#25620]
- VSCode Version: 1.11.2
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Create a new `scss` file
2. Paste code below

```css
$map: (
  a: (63px, 70px),
  b: (100px, 69px),
  c: (70px, 70px),
  d: (79px, 70px),
);

@each $prop, $sizes in $map {
  .c--#{$prop} {
    width: nth($sizes, 1);
    height: nth($sizes, 2);
    background-image: url('./media/' + $prop + '.png');
    background-image: url('./media/' + $prop + '@2x.png');
    background-image: url('./media/' + $prop + '@3x.png');
  }
}
```

Expected behaviour
```
No errors reported
```

Current behaviour

![zrzut ekranu 2017-04-28 o 12 54 51](https://cloud.githubusercontent.com/assets/1313605/25526000/ea18d4ca-2c11-11e7-85a4-c04ff245767c.png)

Code is valid

![zrzut ekranu 2017-04-28 o 12 58 23](https://cloud.githubusercontent.com/assets/1313605/25526118/6cb66c4e-2c12-11e7-8ce1-3facd4599ce2.png)
