### ISSUE TITLE
Allow Theme Specific CSS in the Markdown Preview

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#26078]
Part of #22916

Allow users to write CSS for the markdown preview that only applies when a given theme is active. This would leverage normal css selectors, similar to how the light and dark styling works today:

```css
.vscode-light a { color: #f0f; }
.vscode-dark a { color: #0ff; }
```

The target syntax for theme specific css would be something like:

```css
[data-theme="Red"] a {
   color: #fff;
}
```
