### ISSUE TITLE
More theme options — Typography

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#26128]
Including

- Family
- Weight
- Style/Variant/Features
- Include typeface files in theme pack
- Per-language settings (to support fallbacks, cf. #5260)

**Comment by pahen** [comment]
I would love this! This is how the Ayu theme could look like if we had this feature.

![screen shot 2017-05-25 at 23 12 24](https://cloud.githubusercontent.com/assets/353888/26470943/d7f6be76-419f-11e7-96cd-0f8d742c7567.png)

**Comment by guidobouman** [comment]
Also see this similar issue about allowing the setting of a custom font on non-editor parts of the app: https://github.com/Microsoft/vscode/issues/519

**Comment by leonbreedt** [comment]
This is probably my biggest annoyance switching from Atom, that I have to live with the standard font.

**Comment by johnpapa** [comment]
Adding these as per @aeschli 


## Font settings for the VS Code Shell

The font-family for the shell itself, so we can change the title bar, sidebar, status bar, file tabs, and more. This would be the default for the shell and help match the code.

```css
.monaco-shell {
  font-family: 'Operator Mono', 'Fira code', 'Inconsolata', monospace;
  letter-spacing: 0.5px;
}
```



## Panel headers

Expose the color, font settings and letter spacing for the panel header titles. Letter spacing is sometimes needed as the titles' letters are very close and more difficult to read in some fonts.

```css
.vs-dark .monaco-panel-view .panel > .panel-header > .title {
  font-weight: normal;
  letter-spacing: 1px;
}
```


## Window titles

Expose color, font settings, and letter spacing for window titles

```css
.vs-dark .monaco-workbench > .part.titlebar > .window-title {
  color: #fafafa;
  letter-spacing: 1px;
  font-weight: 200;
}
```

## File Tabs

Expose color, font settings, and letter spacing for tabs (file tabs)

![image](https://user-images.githubusercontent.com/1202528/33155141-d0220836-cfbb-11e7-9176-db2562151a3d.png)

```css
.monaco-workbench .tabs-container .tab * {
  font-style: italic;
}
```

**Comment by johnpapa** [comment]
@aeschli Can you provide some feedback on which of these may be within your roadmap?

**Comment by RomainLanz** [comment]
Any news on this?

**Comment by niteshkumarniranjan** [comment]
Starting to hate vscode on ubuntu because I dont like the ubuntu font in the UI.

**Comment by ryaninvents** [comment]
I'm in the camp of people who would like to use an alternate UI font on Ubuntu. Here's how I managed to do it.

I downloaded a copy of my font of choice -- [Lato](https://fonts.google.com/specimen/Lato) -- and used FontForge to rename it to "Ubuntu". (I'd wanted to name it "BlinkMacSystemFont" so it wouldn't collide, but VS Code applies OS-specific font settings, so that wasn't possible.) I updated Regular, Italic, Bold, and Bold Italic, then copied the new font files to `~/.fonts` and ran `fc-cache -f -v` to reload the font cache.

It would be nice if there were an unused font name at the start of the `font-family` declaration, such as `LinuxSystemUI`, so we wouldn't have to "clobber" the Ubuntu font. However, I'm happy with my setup now.

![image](https://user-images.githubusercontent.com/8356669/53702621-d8bbe900-3dd6-11e9-9bf5-f0622520fd04.png)

**Comment by wsdfhjxc** [comment]
You don't have to mess with system fonts, since there is an extension called [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css), which allows you to theme VSCode in a similar way to Firefox with `userChrome.css`.

The rule to change the UI font would be like:

```css
body {
  font-family: "Roboto" !important;
  font-size: 9.5pt !important;
}
```
