### ISSUE TITLE
CompletionItemProvider#resolve not always called

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/vscode#26622]
- VSCode Version:
```
$ code --version
1.12.1
f6868fce3eeb16663840eb82123369dec6077a9b
```

- OS Version: Ubuntu 14.04 LTS

Steps to Reproduce:

1. Install the extension from this vsix file:  https://s3-us-west-1.amazonaws.com/s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-concourse-0.0.6-RC.1.vsix 
2. Create a file called 'pipeline.yml' and put this text in it:

```
resources:
- name: demo-repo
  type: git
  source:
    uri: git@github.com/kdvolder/demo-repo
    <*>
```

3. The `<*>` marks the cursor/caret position. So delete it and place cursor there.

4. Press CTRL-SPACE to invoke content assist.

Now, in order to see the problem. Only use the mouse to invoke the last proposal in the list. I.e **Do not** use the cursor keys, also *Do no* type to narrow the proposals. Instead, scroll-down (using mouse or scrollwheel) to the last proposal its text is `← ← - name`. Then **click** the proposal with the mouse to invoke it.

=> Observe: The completion simply inserts the label text. So the editor contents becomes this:

```
resources:
- name: demo-repo
  type: git
  source:
    uri: git@github.com/kdvolder/demo-repo
    ← ← - name
```

This is wrong. Compare this to the intended/correct behaviour which you can get by using cursor keys (instead of mouse) to move down and select the proposal, then press `ENTER` to invoke it. In this case the editor contents becomes this:

```
resources:
- name: demo-repo
  type: git
  source:
    uri: git@github.com/kdvolder/demo-repo
- name: 
```

I speculate that the reason for the discrepancy is as follows:

1. our completions must be resolved to get the doc-string as well as fill in the edit. 
2. When we use cursor navigation the doc-strings are revealed in the UI, and this forces the details, including the edits to be filled in.
3. When we directly click on a completion, then its doc string is never revealed and the item is therefore not being resolved. Thus, the item being invoked doesn't have a textEdit and Vscode just defaults to inserting the label text at the cursor instead.
