### ISSUE TITLE
UX: Revisit font sizes in the workbench (explorer for example)

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#26883]
Code : 13px
Windows : 12px
Result : The text looks very dense, lack of space.

Code sample (200% scale): 
![image](https://cloud.githubusercontent.com/assets/240091/26218230/d969a7cc-3c3c-11e7-94a1-fb34bb9d2d40.png)

Windows sample (200% scale):
![snipaste20170519_024919.png](https://ooo.0o0.ooo/2017/05/19/591ded00dc106.png)

**Comment by be5invis** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/media/part.css#L68
This is causing the result.

**Comment by Tyriar** [comment]
It actually does kind of look nicer at 12px (screenshots on Mac):

**13px:**

<img width="401" alt="screen shot 2017-05-19 at 12 26 50 pm" src="https://cloud.githubusercontent.com/assets/2193314/26263674/88f07c92-3c8e-11e7-812e-e4797414d38f.png">

**12px:**

<img width="333" alt="screen shot 2017-05-19 at 12 27 00 pm" src="https://cloud.githubusercontent.com/assets/2193314/26263676/8cd036f4-3c8e-11e7-91e0-00f1b098ce9a.png">

**Comment by bpasero** [comment]
Note that 13px is our default workbench font, it impacts a lot more than just the explorer.

**Comment by be5invis** [comment]
@bpasero I've tried to comment the CSS assignment about 13px and nothing seem broken.

**Comment by be5invis** [comment]
@bpasero We can assign a `font-size` into this CSS group:

```css
.explorer-viewlet .editor-group, .explorer-viewlet .explorer-item, .explorer-viewlet .open-editor {
    height: 22px;
    line-height: 22px;
    font-size: 12px;
}
```
This only affects sidebar and does not touch anywhere else.
