### ISSUE TITLE
Toggling line comment on certain file types breaks when there is already a comment

### ISSUE THREAD

**Issue by BorntraegerMarc** [microsoft/vscode#27560]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Take the following CSS code:
```css
paper-item {
	 height: 10px;
	 color: var(--komed-font-color-blue);
	/*border: solid;*/
	/*border-width: 1px;*/
	 margin-left: 3%;
	 font-size: 14px;

}
```
2. If I toggle line comment now on line 3 to 6 (select the lines and press the command shortcut for line comment)
3. Then the comments actually break because there already was some comments
```
paper-item {
	 height: 10px;
	 color: var(--komed-font-color-blue);
	border: solid;*/
	/*border-width: 1px;
	 margin-left: 3%;
	 font-size: 14px;

}
```

This only happens to file extensions where there is no actual "line comment". So CSS for example or HTML. For a JS file the editor fills in the appropriate amount of `//` comments
