### ISSUE TITLE
Emmet toggle comment on multiple cursors should not comment nodes that are children of other nodes being commented

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27874]
Since it looks like we actually fetch the nodes (https://github.com/Microsoft/vscode/commit/1d93668c0e5e8bf91aa70f92c998bd34d548c2e7), we can probably ensure that children of other nodes being commented are not included. This will prevent the following case:

<img width="258" alt="screen shot 2017-06-01 at 11 14 57 am" src="https://cloud.githubusercontent.com/assets/2193314/26694217/90e8655e-46bb-11e7-9fa2-714a3507e65a.png">

<img width="253" alt="screen shot 2017-06-01 at 11 16 00 am" src="https://cloud.githubusercontent.com/assets/2193314/26694263/b6bee212-46bb-11e7-9538-6dfaf865271c.png">

I expect the following result:

```css
/*.foo {
    display: block;
}*/
/*.bar {
    .foo {
        display: block;
    }
}*/
```
