### ISSUE TITLE
[less] syntax error if classname starts with `-`

### ISSUE THREAD

**Issue by meowtec** [Microsoft/vscode#28183]
- VSCode Version: 1.12.2 
- OS Version: OSX EI Capitan 10.11.6 (15G1510)

Steps to Reproduce:

LESS code:

```less
@color: red;
.-@{color} {
  color: @color;
}
```

It will be compiled to
```
.-red {
  color: red;
}
```

While I get a `identifier expected` error in VSCode:

<img width="190" alt="2017-06-07 8 30 57" src="https://user-images.githubusercontent.com/4006436/26878502-45e8ff32-4bc0-11e7-8c2a-9a85a2b74c1c.png">
