### ISSUE TITLE
SCSS Syntax Highlighting is now incorrect

### ISSUE THREAD

**Issue by nbar1** [Microsoft/vscode#28366]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jsx|TwentyChung|0.0.1|
|html-snippets|abusaidm|0.1.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-svn|eliean|0.1.0|
|vscode-npm|fknop|3.3.0|
|final-newline|samverschueren|0.3.2|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|;

---

Steps to Reproduce:

1. Open a SCSS file with the following content:
```
div[id$="divPAGEBAR"] {
	color: transparent;
	padding-right: 10px;
}
```
2. See that syntax highlighting is incorrect vs. using a CSS filetype.
3. This is a new issue introduced in the latest update

<img width="232" alt="screen shot 2017-06-09 at 3 36 41 pm" src="https://user-images.githubusercontent.com/622363/26991718-8496dc6c-4d29-11e7-9bef-6a374108957b.png">

**Comment by FynnZW** [comment]
Can confirm - additionally, certain selectors are getting a different color:
```scss
    a::after {
        display: block;
        height: 100%;
        width: 100%;
        // content and cursor have selector color  (would be green in this example)
        content: "";
        cursor: pointer;
    }
```
This happens even with all extensions disabled.

OSX Sierra
VSCode Version 1.13.0 (1.13.0)
