### ISSUE TITLE
Incorrect hightlight of CSS pseudo classes in saved SCSS files.

### ISSUE THREAD

**Issue by mzahor** [Microsoft/vscode#28892]
Incorrect hightlight of pseudo selectors in SCSS files.

- VSCode Version:
Version 1.13.0 (1.13.0)
- OS Version:
macOS Sierra 10.12.5

Steps to Reproduce:

1. Create new file
2. Set language to SCSS
3. Enter the following code:
```scss
.bc-player-BkxEu_AGb_default.vjs-mouse {
    font-family: Helvetica;

    &:hover:not(.vjs-native),
    &.vjs-native.test-show-controls {
        &::before {
            display: none;
        }
    }
}
```
4. Save the file with any name and `.scss` extension.

Result:
![image](https://user-images.githubusercontent.com/803142/27231021-d1b72552-52b9-11e7-964e-4d11e12abaaf.png)

Expected result:
Correct highlight as it is before file is saved.
![image](https://user-images.githubusercontent.com/803142/27231121-40a65eba-52ba-11e7-935a-fc88b49d86a1.png)
