### ISSUE TITLE
[CSS] keyframes peek/go-to definition doesn't seem to work

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#3075]
Documentation states:

”Goto Declaration and Find References
“This is supported for keyframes and variables in the same file.”

but it doesn’t look like this works for @keyframes (it does work for SASS variables)

For example with the following code:

``` css
@keyframes progress {
    0% { background-position: 0; opacity: 0; }
    100% { background-position: 100% 0; opacity: 0; }
}

body {
  animation-name: progress;
}
```

Results in this:

![screen shot 2016-02-17 at 1 50 49 am](https://cloud.githubusercontent.com/assets/465069/13105575/b93e3076-d518-11e5-8969-c28188d6a10c.png)

I'd expect it to go to the keyframes line when I right click on animation-name's value.

Strangely if you right click on any of the properties inside the keyframes, it offers both options, but they do nothing (as there is no definition) 

![screen shot 2016-02-17 at 1 52 37 am](https://cloud.githubusercontent.com/assets/465069/13105622/f64b57aa-d518-11e5-8fbf-2e45d626d65d.png)
