### ISSUE TITLE
[css] CSS variables should offer same support as SASS/LESS variables

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#3077]
With the following code, it should offer to peak/go-to definition when on the var(), the same as for variables in LESS and SASS files:

```CSS
:root {
	--bg-color: #ccc;
}

body {
  background-color: var(--bg-color);
}
````

Currently VS Code is not aware of CSS variables.
