### ISSUE TITLE
Add border options to `selectionBackground`

### ISSUE THREAD

**Issue by evandrocoan** [microsoft/vscode#30793]
- VSCode Version: 1.14.1: 
- OS Version: Windows 10 build 15063

Add border options to `selectionBackground` and `findMatchBackground`. They would be called like `selectionBorder` and `findMatchBorder`. You cannot find them on:

1. https://code.visualstudio.com/docs/getstarted/theme-color-reference

Currently the selection has no border:

![image](https://user-images.githubusercontent.com/5332158/28245458-8281e9aa-69dd-11e7-8952-ad69839e7cd4.png)

Would be awesome if it has borders like Sublime Text selections:

![image](https://user-images.githubusercontent.com/5332158/28245453-66aa5410-69dd-11e7-912b-868638cb7ffa.png)

Reproduces without extensions: Yes

___ 

Related issues:

1. https://github.com/Microsoft/vscode/issues/8050 additional options for `editor.selectionHighlight`

**Comment by ro31337** [comment]
+1

**Comment by johnpapa** [comment]
Moving here as per @aeschli and @chrisdias 

This looks awesome! :)

## Selection Highlight and Find Match

Expose border, and background for `selectionHighlight` and `findMatch`

![image](https://user-images.githubusercontent.com/1202528/33155041-f72b7de6-cfba-11e7-830f-61a5c38c8534.png)

```css
/*
  This puts a thin yellow border around the found items like Sublime did it
*/
.monaco-editor .findMatch,
.monaco-editor .selectionHighlight {
  border-top: 0.1px solid #f7ecb5;
  border-bottom: 0.1px solid #f7ecb5;
  background: transparent;
}
```
