### ISSUE TITLE
Allow to change the height of the scrollbar in title area (tabs, breadcrumb)

### ISSUE THREAD

**Issue by oinkbark** [microsoft/vscode#32192]
**Feature Request:** 
- Make horizontal scroll bar taller

**Current:**
- OS Version: Max OSX Sierra
(Light Grey Bar)
![screen shot](https://user-images.githubusercontent.com/26657360/29128017-7f4d8a3e-7cd7-11e7-92b0-829d28a7a30c.png)

**Reasoning**
At the moment, it is only a 'few pixels' tall, and can take a second to grab to make sure a file isn't pulled off instead. This can really slow down productivity, especially if you have many files open on a small screen and need to constantly switch between them.

**Comment by weinand** [comment]
Please provide a larger screenshot so that I can understand what scrollbar you mean.

**Comment by Paviluf** [comment]
The horizontal scroll bar below the tabs indeed need to be taller.

**Comment by SirIntruder** [comment]
Definitely yes, and I also feel vertical bar on the main editor should be bigger (or just easier to catch). I though huge VS bar is funny, but I kinda see it's merits now.

So is it possible to make those bar sizes customizable?

**Comment by up201505472** [comment]
Im working with 2 of my friends to resolve this issue

**Comment by zsynacl** [comment]
want this feature very much.
Also, can the horizontal slider become not so transparent. I can hardly find it when I open to many files.

**Comment by msftrncs** [comment]
Could also use either a bigger scroll-bar or other improvements to make using the tabs easier to move amongst, such as the active tab always showing the 'dirty/closed' indicators, arrows on one end to control the tabs (aka Excel's tabs) or auto scrolling when the mouse is near either edge.   I use UHD screens and the bar is very tiny, hard to grab with a mouse.

**Comment by usernamehw** [comment]
As a workaround this extension: [Custom CSS and JS loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css)

```css
.monaco-workbench>.part.editor>.content .editor-group-container>.title.tabs>.tabs-and-actions-container>.monaco-scrollable-element .scrollbar,
.monaco-workbench>.part.editor>.content .editor-group-container>.title.tabs>.tabs-and-actions-container>.monaco-scrollable-element .scrollbar .slider {
	height: 8px !important;
}
```
