### ISSUE TITLE
Emmet adds color proposal that duplicates css proposal

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#32232]
_From @aeschli on August 10, 2017 15:27_

```css
.foo {
    background: #000000;
    color: #
}
```

![image](https://user-images.githubusercontent.com/6461412/29175497-8292c476-7de9-11e7-806b-f6a3375729d5.png)

@ramya-rao-a Anything we can improve here? It's a detail, I agree...

_Copied from original issue: Microsoft/vscode-generator-code#84_
