### ISSUE TITLE
Color Picker: Colors lose precision

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#32323]
Have this CSS:

```css
body {
    color: hsla(121, 45%, 29%, 0.61);
}
```

If you hover over that color, you'll notice the ColorPicker fails to recognize the format and shows hex instead, because the way to color is passed around (to RGB and back to HSL), precision is lost and the new format would be `hsla(121, 45%, 28%, 0.61)`.
