### ISSUE TITLE
CSS Grid Bug coloring

### ISSUE THREAD

**Issue by JosepSalvia** [Microsoft/vscode#32499]
- VSCode Version: 1.15 32 bits
- OS Version: Last update windows 10 64 bits stable release

Steps to Reproduce:

1. Open new css file (name irrelevant confirmed)
2. Introduce the following code:
```css
.gridport {
    display: grid;
    grid-template-rows: 1fr 1fr;
    grid-template-columns: 1fr 1fr;
    grid-template-areas: "upleft upright" "downleft downright";
    justify-content: space-between;
    align-content: space-between;
    grid-column-gap: 20px;
    grid-row-gap: 20px;
}
.upleft {
    grid-area: upleft;
}
.upright {
    grid-area: upright;
}
.downleft {
    grid-area: downleft;
}
.downright {
    grid-area: downright;
}
```

3. Colors are not displayed properly, As can see here: http://i.imgur.com/GNpVAU3.png either "upright" should be displayed white or the other options "upleft" "downleft" and "downright" should be orange too.

Reproduces without extensions: Yes
