### ISSUE TITLE
The width of hard tab different by css property.

### ISSUE THREAD

**Issue by tarky17** [Microsoft/vscode#32865]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
beautify|Hoo|1.1.1
code-settings-sync|Sha|2.8.3
html-snippets|abu|0.1.0
vscode-caniuse|aka|0.5.3
Bookmarks|ale|0.15.2
project-manager|ale|0.19.0
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.3
jquerysnippets|don|0.0.1
python|don|0.7.0
php-debug|fel|1.11.1
php-intellisense|fel|1.5.0
auto-close-tag|for|0.4.3
rest-client|hum|0.15.1
docthis|joe|0.4.8
vscode-insertdatestring|jsy|2.1.0
MagicPython|mag|1.0.12
prettify-json|moh|0.0.3
easy-less|mrc|1.4.5
vscode-csscomb|mrm|5.1.0
mssql|ms-|1.1.0
debugger-for-chrome|msj|3.1.8
vscode-icons|rob|7.12.0
partial-diff|ryu|0.3.1
Align|ste|0.2.0
highlight-matching-tag|vin|0.4.4
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.4.1

(5 theme extensions excluded)

---

Steps to Reproduce:

1. Open new file. (Command + n)
1. Paste the sample code below.
1. Change the file type to css.
1. Set the settings of indentations.
	1. Indent Using Tabs.
	1. Tab size any. (I'm using 4)

**Sample Code**

```css
.button {
	display: inline-block;
	font-size: .7rem;
	padding: 3px 6px 1px;
	text-decoration: none;
	border-radius: 6px;
	cursor: pointer;
	box-shadow: 0 1px 0 0 #fff6af;
	background: linear-gradient(to bottom, #ffec64 5%, #ffab23 100%);
	background-color: #ffec64;
	border: 1px solid #ffaa22;
	color: #333;
	text-shadow: 0 1px 0 #ffee66;
}
```

You'll see that the tab size of under the box-shadow is abnormal.

## Normal

![nomal-tab-width](https://user-images.githubusercontent.com/13681880/29505140-42d441f4-867f-11e7-85aa-81cf597dcb06.png)

<br>

## Abnormal

![abnomal-tab-width](https://user-images.githubusercontent.com/13681880/29505142-4d914d76-867f-11e7-8f29-84194cad3dee.png)

The element.style seems to be removed by some processing.

I confirmed this problem on css, less and sass.
And I confirmed this problem on Windows 7 Home 64bit, latest vs code.

Reproduces without extensions: Yes
