### ISSUE TITLE
Hide tabs section entirely

### ISSUE THREAD

**Issue by faustinoaq** [Microsoft/vscode#33607]
- VSCode Version: 1.15.0
- OS Version: Manjaro Linux x64 Gellivara

Steps to Reproduce:

1. Configure `settings.json`

```
{
  "workbench.editor.showTabs": false
}
```

2. Tabs are hidden but tabs section still fill the space.

Reproduces without extensions: Yes

Some captures:

1. Face to face with Vim

![screenshot_20170831_111904](https://user-images.githubusercontent.com/3067335/29933705-34de99d4-8e3e-11e7-81aa-2a01efef8049.png)

2. Proposed setting:

```
{
  "workbench.editor.showTabs": "none | one | all"
}
```

With `"workbench.editor.showTabs": "none"` then

![screenshot_20170831_112820](https://user-images.githubusercontent.com/3067335/29934088-8081d7c4-8e3f-11e7-8654-c36488789f65.png)

**Comment by fabiospampinato** [comment]
I think you might achieve what you want today via a [third party extension](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) and some custom CSS.

**Comment by faustinoaq** [comment]
> This extension modifies some VS Code files so use it at your own risk.

Yes, [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) is useful and risky.

**Comment by cpxPratik** [comment]
Also is there any way to shorten height of tabs (file's tab headings), ? Tabs are noticeably tall and waste screen space. I can't find issue related to it. Surely, someone must have notice it.

**Comment by fabiospampinato** [comment]
@faustinoaq there's actually barely any risk involved with it. In case anything breaks a simple re-installation of VSC would fix it.

@cpxPratik Unless they fix https://github.com/Microsoft/vscode/issues/459 the only option remains to use the [extension](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css).

**Comment by skyhirider** [comment]
Has this been added yet? The more space for actual text the better.

**Comment by TwatBurglar** [comment]
Has this been added yet? The more space for actual text the better.

**Comment by thany** [comment]
Second that.
The tabs are useless to me. They waste valuable screen real estate. The open files show in the side bar perfectly fine.

**Comment by charlesferreira** [comment]
Still waiting for this feature. I really love other editor's ability to go full screen and zero bars/tabs/menus distraction. I can achieve that in like Jetbrains' IDEs and it's totally awesome.

Please, guys. I'm loving VS Code, but the tab bar, beyond not being able to hide them, is too large!

**Comment by well1791** [comment]
:wave: Hi everyone!

:thinking: I have some (silly :sweat_smile:) workaround if you just work with one project all day (and you don't want to bother yourself with _Custom CSS and JS Loader_ plugin).

1. Toggle Developer Tools
1. Inspect the row
1. Delete the element :rofl:

I haven't seen any errors yet :man_shrugging: but (as you have already guessed), it only works during your current session.

Anyway, I just hope the **VS Code team** still consider this _feature-request_ :pray:

**Comment by dimitarnestorov** [comment]
@well1791 don't you have an empty space between your code and terminal? Like so:
![image](https://user-images.githubusercontent.com/8790386/45941239-e2e6e980-bfe5-11e8-8310-6fdf56a9545e.png)

Not really a workaround, you're not getting that screen real estate back

**Comment by fuzihaofzh** [comment]
You can use the plugin "Custom CSS & JS" and use the following code
````
.title.show-file-icons {
    display: none !important;
}
````

**Comment by thany** [comment]
That's not really a solution. The extension needs permission for VSCode to change itself, which is frankly terrifying. This needs a proper fix.

**Comment by Isti115** [comment]
Has anyone figured out how to actually make that space available after hiding the tab div?
I couldn't make it fill the extra height using just CSS, so I guess that something is calculated in JS that would need to be changed as well.

**Comment by Isti115** [comment]
Wow, I've become so desperate over the last few days that I finally managed to write a script that pushes the window off the top of the screen, thus hiding the (to me useless) title bar and tab bar!
All the other elements (Activity Bar, Status Bar and maybe minimap, but I like to keep that one around sometimes) can be hidden in VSCode, so I guess that this is solved for me as long as the window is at the top of the screen. :)

For reference here is the AutoHotKey code that worked for me, but you could call the DLL from any of your favorite languages.

````
SetTitleMatchMode, 2
WinTitle := "Visual Studio Code"

; --- WinMove version

; WinMove, %WinTitle%, , 0, -64, 1280, 1504

; -- DLL version

WinGet, id, , %WinTitle%
Result := DllCall("SetWindowPos", "uint", id, "uint", HWND_TOP, "Int", 0, "Int", -64, "Int", 1280, "Int", 1504, "UInt", 0x400)
```

ps.: The 0x400 corresponds to the `SWP_NOSENDCHANGING` flag that prevents the window from realizing that it has been resized and jumping back on screen.

**Comment by jinyaozhuzhu** [comment]
> 👋 Hi everyone!
> 
> 🤔 I have some (silly 😅) workaround if you just work with one project all day (and you don't want to bother yourself with _Custom CSS and JS Loader_ plugin).
> 
> 1. Toggle Developer Tools
> 2. Inspect the row
> 3. Delete the element 🤣
> 
> I haven't seen any errors yet 🤷‍♂️ but (as you have already guessed), it only works during your current session.
> 
> Anyway, I just hope the **VS Code team** still consider this _feature-request_ 🙏
> are you doubi（逗比）？

**Comment by liquidvisual** [comment]
This seems like such a basic feature. Why has it not been implemented yet?

**Comment by EliasCK** [comment]
Would love this! And then possibly an option to only show tabs if multiple files are open?

If I could configure vscode, to always open files in a new window (no tabs), and then only add tabs if I drag in a file to an existing window or open a folder/project. That would be amazing.

**Comment by wangchou** [comment]
I tried <code>Custom CSS and JS Loader</code> extension with 

```css
.title.show-file-icons {
    display: none !important;
}
```
(vscode version: 1.35.1)

Then, I found the tab bar is gone but the <code>editor area size didn't change.</code> 
The editor area only moved up 35px... and generated new blank space at bottom.

Any other workaround?

**Comment by sepehrHosseini** [comment]
This how I removed the blank space in the bottom of screen:
```
.title.show-file-icons {
     display: none !important;
 }
 
 .editor-container,
 .editor-instance > div,
 .monaco-editor.mac,
 .overflow-guard,
 .editor-scrollable {
     height: 100% !important;
 }
```

**Comment by TamasBarta** [comment]
@sepehrHosseini I tried something similar, but that caused the last line to be visible, which disappears when the last pixel of it would be covered by the status bar. Does your solution solve this?

**Comment by wangchou** [comment]
@sepehrHosseini 
I tried the css. On my mac (vscode 1.35.1), the empty space at bottom just didn't go away... 😢 

I also found there is a pull request for hiding tabs. (https://github.com/microsoft/vscode/pull/70140)

**Comment by wangchou** [comment]
@sepehrHosseini Sorry, I was wrong. It did increase editor area slightly. But the empty space is still there. Not sure which setting / extension causes this... It's too complex, so I'm trying make peaceful life with tabs bar, now. 😿 

with css off
![スクリーンショット 0001-06-20 0 03 35](https://user-images.githubusercontent.com/32716/59782125-dd59ce00-92ef-11e9-9c05-d3fa4e68e546.jpg)

with css on
![スクリーンショット 0001-06-20 0 03 24](https://user-images.githubusercontent.com/32716/59782137-e480dc00-92ef-11e9-9d08-ea6535a4f32a.jpg)

**Comment by sepehrHosseini** [comment]
@wangchou Great 🎉 
Yes, it appears that when you apply `height: 100%` on these elements the last line gets disappeared when it's near the bottom of the view.

**Comment by saivan** [comment]
I have to chime in here too and say please. The header area is distracting, and it doesn't really serve a huge purpose for me, I can always just bring back the tab bar if I need that information

**Comment by bruddah** [comment]
Seems like an interesting idea, I'd definitely try this one out.

**Comment by stevenvachon** [comment]
Do it.

**Comment by toger5** [comment]
This would be really great to have!

**Comment by ruskimarcin** [comment]
custom css ext. doens't really solve the issue, it's just a hack.
What if I'd like to have it on the toggle, or map it with settings cycler ext.? Currently not possible AFAIK

**Comment by fr3fou** [comment]
any news regarding this? it's been 2 years

**Comment by mokhosh** [comment]
@sepehrHosseini this one breaks settings search bar, and removing it doesn't seem to have any negative effect:
```
.monaco-editor.mac
```

**Comment by roboslone** [comment]
Oh please, do it! Tab bar is even visible in Zen mode :(

**Comment by stevenvachon** [comment]
This is one of the few things keeping me from seriously contemplating a switch from Sublime Text 3. 🤷

**Comment by Tysiachnyi** [comment]
so what?

**Comment by ZayRTun** [comment]
any updates? I tried the css plugin to hide it but the plugin is not working in the latest vs code version. this feature would be really nice.

**Comment by ZayRTun** [comment]
I got it working on ubuntu. Install the `custom CSS and js` plugin then create a CSS file at `"file:///home/youname/.vscode/hide-title-bar.css"` and add the following styles and reload the plugin.
```css
.editor .title {
    display: none !important;
}
```

**Comment by ssmooncoder** [comment]
chrome macOS has the option to hide the tab toolbar, yet this hasn't been implemented for 4 years now

**Comment by stpoa** [comment]
any updates?

**Comment by stpoa** [comment]
any updates?

**Comment by eimfach** [comment]
Fork ?

**Comment by tejasvi** [comment]
The empty space at the bottom is due to limited number of rendered lines. Bumping this limit by 3-4 lines will solve the issue.
![](https://i.imgur.com/doimyYs.jpg)

**Comment by JulienBe** [comment]
Jumping in the bandwagon, I would love this too ;)

**Comment by well1791** [comment]
So, this is it.

We all have been selected (either by comments or emojis) to do something (or nothing) for the sake of our lives as programmers, or writers, or just people staring the screen 🤷‍♂️  (it's up to you what you do with your time), anyway, just because we feel the same pain in the eyes, and because we believe the title is a unnecessary waste of space, and/or because we just like to read this issue getting longer and longer across the years. Let's all raise our hand (just one) for a moment, and maybe touch the ceiling, or a cat in a tree, but always remember this "thread", maybe one day we'll have our beloved feature (most certainly not), or maybe one day we'll forget about this feature-request (that's nope for sure), but no matter what happen or maybe it matters, we.. I don't know, I just wanted to share this plugin https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui, it works! Good luck with that!

And now my time has come! I won't forget you everybody <3!
But know this, I'll be there watching you...r comments! because I activated notifications obviously.
So, farewell my friends!

**Comment by pacifio** [comment]
pleaseeeeee

**Comment by OceanBelongsToMe** [comment]
pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by OceanBelongsToMe** [comment]
> 

how to do this？

**Comment by OceanBelongsToMe** [comment]
@tejasvi can you tell me your solution？

**Comment by Aqa-Ib** [comment]
At least let the user hide it on Zen Mode.
Thanks

**Comment by laralove143** [comment]
better solution, have a pixel number setting for tab size instead of just normal/large.. this way we can just put 0 to disable it, this is how other sizes are handled anyway like the scrollbar, anything limiting this?

**Comment by SichangHe** [comment]
# Working workaround (hack)
I just spent a few hours and final have [a working configuration](https://github.com/SichangHe/.config/blob/main/Code/User/custom.css) using [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css).
*Disclaimer: this configuration is licensed under [an MIT license](https://github.com/SichangHe/.config/blob/main/LICENSE) (don't blame me if you get hacked! 😄)*

I'll paste it here as well:

```css
/* # Hide tab bar and float utility buttons to the right. */
#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.title.tabs.show-file-icons {
    float: right;
    z-index: 1;
}

#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.title.tabs.show-file-icons>div.tabs-and-actions-container>div.monaco-scrollable-element>div.tabs-container {
    display: none;
}

/* ## Force the editor area to use full height. */
#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.editor-container,
#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.editor-container>div>div,
#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.editor-container>div>div>div.overflow-guard>div.monaco-scrollable-element.editor-scrollable.vs,
#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.editor-container>div>div>div.overflow-guard>div.monaco-scrollable-element.editor-scrollable.vs>div.lines-content.monaco-editor-background>div.view-lines.monaco-mouse-cursor-text {
    height: 100% !important;
}

#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.editor-container>div>div>div.overflow-guard {
    height: 100% !important;
    position: absolute;
}


/* # Show the bottom bar even if it is toggled off. */
body>div.file-icons-enabled.reduce-motion.monaco-workbench.chromium.nosidebar.nopanel.noauxiliarybar.maximized.vs.nostatusbar>div.monaco-grid-view>div>div>div.monaco-scrollable-element>div.split-view-container>div:nth-child(4),
body>div.file-icons-enabled.reduce-motion.monaco-workbench.chromium.nopanel.noauxiliarybar.nostatusbar.maximized.vs>div.monaco-grid-view>div>div>div.monaco-scrollable-element>div.split-view-container>div:nth-child(4) {
    bottom: 0px;
    height: unset !important;
    top: unset !important;
    display: unset;
}

#workbench\.parts\.statusbar {
    height: unset !important;
}

/* ## Show the horizontal scrollbar */
#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.editor-container>div>div>div.overflow-guard>div.monaco-scrollable-element.editor-scrollable.vs>div.visible.scrollbar.horizontal,
body>div.file-icons-enabled.reduce-motion.monaco-workbench.chromium.nopanel.noauxiliarybar.maximized.vs.nostatusbar.nosidebar>div.monaco-grid-view>div>div>div.monaco-scrollable-element>div.split-view-container>div:nth-child(3)>div>div>div.monaco-scrollable-element>div.visible.scrollbar {
    bottom: 12px !important;
}
```

If it does not work for you, perhaps you need to delete some classes in the code above (maybe your vscode does not have those classes so the elements are not correctly selected).

- The tab bar is hidden
- The buttons on the right hand side floats (I find them useful)
  - To hide it completely, you want to set
```css
#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.title.tabs.show-file-icons
```
to `display: none;` instead of `float: right;`
- You need to toggle the status bar *off*
  - But it still shows, because I hacked it to always show (I find it useful, plus that space should have been blank anyway)
  - By toggling the status bar off, vscode is tricked to render (potentially) one more line ("solving" the problem of not rendering enough lines and having a blank area at the bottom)
- The horizontal scroll bar is bumped up (it should have been blocked by the status bar), but only showing a little bit because I want it short. If you want it taller, set
```css
#workbench\.parts\.editor>div.content>div.grid-view-container>div>div>div>div.monaco-scrollable-element>div.split-view-container>div>div>div.editor-container>div>div>div.overflow-guard>div.monaco-scrollable-element.editor-scrollable.vs>div.visible.scrollbar.horizontal,
body>div.file-icons-enabled.reduce-motion.monaco-workbench.chromium.nopanel.noauxiliarybar.maximized.vs.nostatusbar.nosidebar>div.monaco-grid-view>div>div>div.monaco-scrollable-element>div.split-view-container>div:nth-child(3)>div>div>div.monaco-scrollable-element>div.visible.scrollbar
```
to `bottom: 20px !important;` or something instead of `bottom: 12px !important;`

Hopefully, this is helpful! I got ***2** more lines* (had 34) in my vscode 🎉
Please give suggestions if improvements can be made. Please give proper credit if you share.

Steven Hé (Sīchàng)

**Comment by SichangHe** [comment]
Just realized that I did not support Zen mode, which many people want. [Fixed it](https://github.com/SichangHe/.config/commit/a1943fb12b2feba8c384539653057659d967819a).

**Comment by kklot** [comment]
I just found out that I could live with zooming out the whole windows interface until the tab height/status bar height is what you wanted (~vim tab/status bar for me), at at the same time increase the editor and terminal font size.

Only drawback is font size of other stuffs would be too small to read (extension, outlines,...), but I rarely look at them anyway. But I'd be great if we increase the font size of UI as well - anyone know where to change the UI font size?

**Comment by starball5** [comment]
Related on Stack Overflow: [How to hide the VS Code bar with file name, breadcrumbs, run java, split editor and more actions?](https://stackoverflow.com/q/74272910/11107541)

**Comment by a-constantin** [comment]
I decided to try out vscode again today, haven't used it since the PR that added this very basic feature was rejected for reasons I still don't understand four years ago, so I guess I'll try again in a few more years.

**Comment by maxxxxxdlp** [comment]
Rather than simply hiding the title section, I decided to still make the title action buttons available just in case, but without preventing the editor from occupying the rest of the area:

![Screenshot 2023-08-02 at 20 16 44](https://github.com/microsoft/vscode/assets/40512816/bc9f432a-2fc0-4015-9ad9-b780cc38ffbf)

CSS (for the [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) extension) if you want to do similar:
```css
.title.show-file-icons {
    position: absolute !important;
    top: 0;
    right: 0;
    z-index: 100;
    opacity: 0.5;
}

.title.show-file-icons:hover {
    opacity: 1;
}

.title.show-file-icons .label-container {
    display: none !important;
}
```
