### ISSUE TITLE
[SCSS] Incorrect tab indentation when color preview is present

### ISSUE THREAD

**Issue by bounasserabdelwahab** [Microsoft/vscode#34512]
- VSCode Version:
![vscode-version](https://user-images.githubusercontent.com/1855505/30512071-45050198-9ade-11e7-87e0-d7c66874c2d2.PNG)

- OS Version:
Windows 10 Pro
Version 1703
OS Build 15063.608
System Type: x64

Steps to Reproduce:
1. Create a `.scss` file and add something like this:
```scss
.parent {
  color: #f00;

  .child {
    color: #f0f;
    whatever: whatever;
  }
}
```
**Note** Tabs must be used to indent the rules above.

![indentation-issue](https://user-images.githubusercontent.com/1855505/30512068-2cf89196-9ade-11e7-8d69-85b4e8d8e484.PNG)

Reproduces without extensions: Yes
