### ISSUE TITLE
CSS and SCSS indentation using tabs is off with lines with the color decorator

### ISSUE THREAD

**Issue by zmoazeni** [Microsoft/vscode#34725]
- VSCode Version: 1.16.1
- OS Version: Ubuntu Linux 16.04 Gnome

Steps to Reproduce:

1. Start a blank file `/tmp/foo.css/`
2. Paste this code in there:

```css
/* I've intentionally indented with 2 spaces */
.foo {
  padding: 10px;
  color: #123;
}
```

3. Go to the bottom right and click the tab size box and select "Convert indentation to Tabs".
4. The `color` line has slightly different indentation.

Reproduces without extensions: Yes

Here's a screenshot with `code --disable-extensions`:

![foo css_023](https://user-images.githubusercontent.com/314/30672400-29ba5e38-9e3a-11e7-9395-ed8e3cbac4ec.png)

Believe me, I prefer spaces for indentation, but I'm on a couple code bases where the team has chosen tabs. And this is a weird annoyance. 

This goes away if I set: `"editor.colorDecorators": false` in the settings.
