### ISSUE TITLE
[css] highlighting within @keyframes is messed up

### ISSUE THREAD

**Issue by Lonefy** [Microsoft/vscode#3481]
Screen shot:
![image](https://cloud.githubusercontent.com/assets/7921431/13347659/2bc37b7c-dcaa-11e5-9c89-e711ee0b4810.png)
```css
@keyframes bounce {
    from, 20%, 53%, 80%, to {
        -webkit-animation-timing-function: cubic-bezier(0.075, 0.82, 0.165, 1);
    }

}
```
