### ISSUE TITLE
[css] no intellisense inside @supports condition

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#35072]
Testing #34994

```css
@supports (color: red)
{
	div {
		color: red;
	}
}
```

If you put your cursor right after `color:` in the supports clause, you won't get any meaningful intellisense. If you put it right before the `red`, it will work.

![peek 2017-09-26 12-38](https://user-images.githubusercontent.com/22350/30856112-a5f81e50-a2b7-11e7-9399-3a3a5b06fb7c.gif)
