### ISSUE TITLE
Folder explorer is faded for some reason

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3569]
Not sure what I did to get it into this state and I don't know how to get it out apart from restarting:

![image](https://cloud.githubusercontent.com/assets/2193314/13412218/873371ee-def6-11e5-861e-d17e612112ad.png)

`.explorer-item-label` is inheriting `color: #ccc` from:

```css
.monaco-workbench.vs-dark {
    background-color: #252526;
    color: #ccc;
}
```
