### ISSUE TITLE
SCSS:  Tags nested inside rules are not styled as tags

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#36923]
- VSCode Version: Code - Insiders 1.18.0-insider (509630ffe3fabf2e1f49b416bb83f5ff0877b042, 2017-10-25T05:11:41.369Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.8.3
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.17.0
project-manager|ale|0.22.0
vscode-eslint|dba|1.4.0
gitlens|eam|5.7.1
tslint|eg2|1.0.12
vscode-console-wrapper|fab|0.4.0
auto-rename-tag|for|0.0.14
svg|joc|0.0.9
Angular2|joh|2.10.0
ecdc|mit|0.10.3
HTMLHint|mka|0.4.0
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.19.1
stylelint|shi|0.30.0
Align|ste|0.2.0
change-case|wma|1.0.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.  Using code such as

````scss
.showcase-modal_overview_header {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
  margin-bottom: 12px;
  h3 {
    margin: 0 0 -7px;
  }
}
````
2. The `h3` is not colored as a tag:

<img width="341" alt="screen shot 2017-10-25 at 2 12 52 pm" src="https://user-images.githubusercontent.com/835148/32015286-a125be12-b98e-11e7-9647-59ede2a6d0e7.png">

This is a regression.
