### ISSUE TITLE
Hover draws a dot in the top left corner when there is no text

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#39316]
![hover](https://user-images.githubusercontent.com/9638156/33378067-b07b5e1a-d524-11e7-9e40-62642ef9c50b.png)
An example is script in `package.json` -> `"scripts"` section with your script.
Hover invokes => there is no text => draws a dot (border actually)
```css
.monaco-editor .monaco-editor-hover {
    border: 1px solid #75715e;
}
```
