### ISSUE TITLE
Expose the border style for the debug bar

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#39324]
As per conversation with @aeschli , @chrisdias and @seanmcbreen , here is a list of style settings I'd love to see exposed in VS Code. 

## Debug bar

Expose the border for the debug bar. I find this helps make it stand out, kinda like the border for peek view.

![image](https://user-images.githubusercontent.com/1202528/33155135-bb944eec-cfbb-11e7-8436-12cf5e7f4b0f.png)

```css
.vs-dark .monaco-workbench .debug-actions-widget {
  border-top: 1px solid #b15a91;
  border-bottom: 1px solid #b15a91;
}
```

https://github.com/Microsoft/vscode/issues/38990
