### ISSUE TITLE
Expose theming for Git Diffs

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#39325]
As per conversation with @aeschli , @chrisdias and @seanmcbreen , here is a list of style settings I'd love to see exposed in VS Code. 

## Git Diffs

Expose the margin, border, box shadow and background color for the git diff indicators. We currently have the background color, but the others are not. This would allow a cool effect like this:

![image](https://user-images.githubusercontent.com/1202528/33155131-ad8e0586-cfbb-11e7-96b9-5555a9bd83e0.png)

```css
.monaco-editor .dirty-diff-added {
  margin-left: 16pt;
  box-shadow: -4pt 0 4pt 2pt #27ff00;
  border-left: 4pt solid #00ff00;
  background-color: #00ff00;
}

.monaco-editor .dirty-diff-modified {
  margin-left: 16pt;
  box-shadow: -4pt 0 4pt 2pt #4fb4d8;
  border-left: 4pt solid #4fb4d8;
  background-color: #4fb4d8;
}
```

cc https://github.com/Microsoft/vscode/issues/38990
