### ISSUE TITLE
Bug: Variable interpolation as a property in LESS

### ISSUE THREAD

**Issue by keenondrums** [Microsoft/vscode#39429]
- VSCode Version: 1.18.1
- OS Version: Ubuntu 17.10

Steps to Reproduce:
1. Create a new less file 
2. Insert the following code:
```less
@var: 'color';

.class-1 {
  // LESS linter marks it as an error
  @{var}: red;
}
```
Current result:
LESS linter fails with errors '[less] } expected' and '[less] at-rule or selector expected'

Expected result: 
LESS linter should allow this syntax. More on interpolation as property in LESS (here)[https://stackoverflow.com/questions/11258677/using-a-less-variable-as-a-property-instead-of-a-value]

Reproduces without extensions: No
