### ISSUE TITLE
Italics and bold remove link syntax highlighting in markdown

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#3947]
![image](https://cloud.githubusercontent.com/assets/2193314/13660691/3391e7ee-e641-11e5-857f-e25d10fb172c.png)

**Comment by donaldpipowitch** [comment]
It would be nice if `__` and `**` would be colored, too, much like `[]()` or `>`.

**Comment by bpasero** [comment]
Please reopen if you still see this with our new markdown extension.

**Comment by Tyriar** [comment]
Verified, but created the related issue https://github.com/Microsoft/vscode/issues/7785

**Comment by Tyriar** [comment]
Still occurring, just more obvious now:

![image](https://cloud.githubusercontent.com/assets/2193314/16129269/0bb73c5e-33b9-11e6-8c94-6d3c6c18195d.png)

The style overriding link styling is:

```css
.monaco-editor.vs-dark.vscode-theme-defaults-themes-dark_plus-json .token.markup.italic {
    font-style: italic;
    color: rgba(86, 156, 214, 1);
}
```
