### ISSUE TITLE
[scss] Wrong "cursor" property highlighting 

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#40723]
- VSCode Version: 1.19.1, 1.20
- OS Version: Win10

![bad_highlight](https://user-images.githubusercontent.com/9638156/34302816-a0a894c2-e743-11e7-8e3b-1a12a39a648d.png)

Reproduces without extensions: Yes

**Comment by weinand** [comment]
Sorry, but I cannot spot what is wrong here.

**Comment by usernamehw** [comment]
@weinand, other properties have the right TM selectors:
```
support.type.property-name.css
meta.property-name.scss
meta.property-list.scss
source.css.scss
```
But `cursor` identifies itself as a tag
```
entity.name.tag.css
meta.property-list.scss
source.css.scss
```

**Comment by usernamehw** [comment]
Also applies to `mask`, `content`, `filter`, `font`
```scss
body {
    cursor: pointer;
    ::before {
        content: '';
    }
    filter: blur(5px);
    font: 12px/14px sans-serif;
    mask: none;
}
```
