### ISSUE TITLE
Nested at-rules don't parse correctly

### ISSUE THREAD

**Issue by Gastror** [Microsoft/vscode#42086]
- VSCode Version: 1.19.2 
- OS Version: Confirmed on OSX High Sierra, Ubuntu Artful Aartvark, Windows 10 fall update

Steps to Reproduce:

1. Create a SCSS file
2. Define a nested keyframe function

Does this issue occur when all extensions are disabled?: Yes

Example: 

```scss
$margin: 8px;
$steps: 10;
$width: 20;
@keyframes wiggleWiggleWiggle {
    @for $i from 0 through $steps {
        #{$i * (100%/$steps)} {
            $direction: (1deg - ($i % 2) * 2);
            $rotate: rotate(($margin - $i * ($width / $steps)) * $direction);
            $translate: translateX(-50%);
            transform: $rotate $translate;
        }
    }
}
```

The following errors are given:  
Line 5:
`[scss] } expected`

Line 6:
`[scss] at-rule or selector expected`

Line 10:
`[scss] { expected`

Line 13:
`[scss] at-rule or selector expected` 

  
All of these are false positives, the above code is valid SCSS and produces the expected output.
