### ISSUE TITLE
[less] @plugin at-rule unknown

### ISSUE THREAD

**Issue by thorn0** [Microsoft/vscode#42271]
### Issue Type
Bug

### Description

Create/open a LESS file containing a `@plugin` rule. E.g.:
```less
@plugin "test"; // <- "[less] at-rule unknown" error

test {
  color: myfunction(); // `myfunction` is added by test.js
}
```
Docs: http://lesscss.org/features/#plugin-atrules-feature

Also, while there is a group of settings `less.lint.*`, there is no rule for suppressing this specific error message.

### VS Code Info

VS Code version: Code - Insiders 1.20.0-insider (ed4c237467bfe7c37b173da782cb65e333484a13, 2018-01-26T06:14:33.313Z)
OS version: Windows_NT ia32 6.1.7601
