### ISSUE TITLE
Progress bar takes long time when opening large files

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#42660]
- VSCode Version: 1.20 Insiders
- OS Version: macOS

Steps to Reproduce:

1. Open a large file (100+ MB)
2. Profile

![image](https://user-images.githubusercontent.com/876920/35641697-bd664e50-0675-11e8-90d3-c014715dbdee.png)

Model building takes ~900ms while rendering takes ~370ms in above case. If we take a deep look into the graph

![image](https://user-images.githubusercontent.com/876920/35641753-e897764e-0675-11e8-936d-e0ce77931f58.png)

Layout/Update layer tree is triggered multiple times when we are loading the file. Disable progress bar decreases the time by ~300ms.

**Comment by bpasero** [comment]
This would apply to any progress bar we show, not just the editor I guess.

**Comment by bpasero** [comment]
@rebornix I fear this is not under our control, we use CSS animations to a) move the progress tick around and b) change its width (grow + shrink while moving).

Maybe we should push for https://github.com/Microsoft/vscode/issues/42474 so that we are not showing this animated progress while the large file loads?

**Comment by rebornix** [comment]
Sounds good to me, let's close this one and track it in https://github.com/Microsoft/vscode/issues/42474

**Comment by bpasero** [comment]
Actually maybe I spoke to soon. Our progress bar seems to be using a very slow form of animation, I will check in March if I can move it to a better one ([some inspiration](https://medium.com/outsystems-experts/how-to-achieve-60-fps-animations-with-css3-db7b98610108)).

**Comment by bpasero** [comment]
@rebornix can you please measure this scenario again with the following change to `progressbar.css` which will change the animation to use `transform`:

```css
.monaco-progress-container.infinite .progress-bit {
	animation-name: progress;
	animation-duration: 4s;
	animation-iteration-count: infinite;
	animation-timing-function: linear;
	will-change: transform;
}

@keyframes progress { from { transform: translateX(0%) scaleX(1) }	50% { transform: translateX(2500%) scaleX(2) } to { transform: translateX(4900%) scaleX(1) } }
```
