### ISSUE TITLE
A bug in highlighting YAML files when using multi-line strings

### ISSUE THREAD

**Issue by eugene-babichenko** [Microsoft/vscode#43065]
- VSCode Version: 1.19.3
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Try using a multi-line string starting with a vertical bar.
2. Write some text on the next line.
3. Add text in quotes.
4. The last quote should be on a new line.
5. The rest of the text gets highlighted like a string.

**EXAMPLES**:
1. This produce the bug (see the attached image):
```yaml
field1: 12
field2: |
  bash -c "
  git init
  "
field3:
  - 1234
```
<img width="154" alt="screen shot 2018-02-07 at 00 25 10" src="https://user-images.githubusercontent.com/15912853/35889788-62cd71da-0b9d-11e8-9b79-1ceb7855f8d2.png">

2. This too:
```yaml
field1: 12
field2: |
  bash -c "git init
  "
field3:
  - 1234
```

3. But this does not:
```yaml
field1: 12
field2: |
  bash -c "git init
  && git add ."
field3:
  - 1234
```

So, the whole thing looks like it gets messed when a multi-line statement initialized with a vertical bar has a line with only quote.

Does this issue occur when all extensions are disabled?: Yes
