### ISSUE TITLE
[css] Lab colors and other CSS Color Module Level 4 features

### ISSUE THREAD

**Issue by thorn0** [Microsoft/vscode#43111]
See the [CSS Color Module Level 4](https://drafts.csswg.org/css-color/#specifying-lab-lch) specification.

While the specification is still a draft and browsers don't support these features yet, there already exists a [PostCSS plugin](postcss-color-lab) that (partially) implements them, so it's actually already possible to use at least a part of them.

```css
.example {
	background-color: lab(33 43 -47);
	box-shadow: 0 0 20px lch(54 107 41 / 10%);
}
```

Would be nice to get previews for those colors in VS Code like it's shown for rgb/rgba/hsl colors.
