### ISSUE TITLE
[less] `} expected` when having nested declarations as mixin arguments

### ISSUE THREAD

**Issue by MLefebvreICO** [Microsoft/vscode#43333]
- VSCode Version: 1.20
- OS Version: Windows 10 Pro 64bits

Having the following : 
```LESS
.someClass {
  .some-mixing({
    border: 1px solid black;

    .someOtherClass {

     }
  });
}
```
VSCode puts an error on 
* `.` (of `.someOtherClass`) : `} expected`
* `}` (ending of `someOtherClass`) : `} expected`
* `}` (of the end of the `some-mixing` ... `});`) : `at-rule or selector expected`
* `}` (ending of `someClass`) : `at-rule or selector expected`

**Comment by octref** [comment]
How is your mixin defined? I went through the examples on http://lesscss.org/features/#mixins-feature but I don't see any mention that variables could be rules with selectors.

And on this playground http://lesscssismore.com/stl65i/, this throws out a syntax error.

![image](https://user-images.githubusercontent.com/4033249/38327230-997e6780-37fc-11e8-9b95-6293c8729e8d.png)

**Comment by aeschli** [comment]
@octref I think there's an example in the http://lesscss.org/features/#detached-rulesets-feature section (3rd source example)

**Comment by octref** [comment]
Simpler repro:

```less
.mixin(@rules) {
  .foo { @rules(); }
}

.mixin({
  .baz {
    color: red;
  }
});
```

lessc compiles file, but VS Code complains about the nested declaration as the detached ruleset.
