### ISSUE TITLE
Incorrect syntax highlighting with YAML-multiline strings

### ISSUE THREAD

**Issue by aripalo** [Microsoft/vscode#43827]
- VSCode Version: `1.19.3`
- OS Version: macOS `10.13.3`

Steps to Reproduce:

1. Write YAML with multiline string, like this:
```yml
foo: bar
multiline: >
  This is a multiline string.
  This is still a multiline string, but has a colon: As you see, the syntax
  highlight doesn't work correctly as it thinks the text before colon is a key.
baz: quux
```
2. Save the YAML-file and notice the syntax highlight is incorrect:

![screen shot 2018-02-16 at 15 02 26](https://user-images.githubusercontent.com/679146/36308745-978753e8-132a-11e8-9fbf-4db7ff6ca905.png)

Screenshot taken with VS Code started with `code --disable-extensions`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aripalo** [comment]
Also same problem exists for multiline strings prefixed with pipe character `|`:

## Input
```yml
foo: bar
multiline: |
  This is a multiline string.
  This is still a multiline string, but has a colon: As you see, the syntax
  highlight doesn't work correctly as it thinks the text before colon is a key.
baz: quux
```

## Output:

![screen shot 2018-02-16 at 15 26 10](https://user-images.githubusercontent.com/679146/36309545-c06090d8-132d-11e8-9d8f-d288073e9a9b.png)
