### ISSUE TITLE
Make color and shape of error markers configurable

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#4388]
_From @Franziskus1988 on March 3, 2016 14:6_

Sometimes it's difficult to find/see the green marked linting errors. Especially when a file contains a lot of comments (normally green).

Would it be possible to make the color and maybe the line thickness configurable?  

_Copied from original issue: Microsoft/vscode-tslint#31_

**Comment by egamma** [comment]
Rendering diagnostics is a general vscode feature.

Moving to vscode

**Comment by bmayen** [comment]
Is there any workaround for this in the meantime? With dark themes it is very easy to miss the green-on-black, rendering tslint far less useful than it should be.

**Comment by lambda4fun** [comment]
@bmayen 

Yes, there is :)
![vscode-yellow-squiggly](https://cloud.githubusercontent.com/assets/24240922/24333049/482449b8-128c-11e7-8312-8f1e695e7c4c.png)

Install [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) extension, then use the following style as the custom CSS:

```css
.monaco-editor.vs-dark .greensquiggly,
.monaco-editor.vs .greensquiggly {
  /* yellow squiggly */
  background: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' height='3' width='6'><g fill='#FF0'><path d='M5.5 0l-3 3H1.1l3-3z'/><path d='M4 0l2 2V.6L5.4 0zM0 2l1 1h1.4L0 .6z'/></g></svg>") repeat-x 0 100%;

  /* rectangle */
  /* background: none;
     border: 1px solid yellow; */

  /* underline */
  /* background: none;
     border-bottom: 1px solid yellow; */
}
```

Please let me know whether it worked :]
