### ISSUE TITLE
Task selector dropdown in Terminal window is too short

### ISSUE THREAD

**Issue by yuval-gilboa** [microsoft/vscode#43997]
### Issue Type
Bug

### Description

I remember this was reported in the past, but i could not find the exact issue. In any case , the problem still remains - i.e., the task selector dropdown in the integrated Terminal window is too short and cannot be resized, and thus long task names are cut off. See picture below:

![image](https://user-images.githubusercontent.com/4710322/36401466-4474d406-15e0-11e8-85c0-fd1efb9542ac.png)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:34:36.336Z)
OS version: Windows_NT x64 6.1.7601

**Comment by bpasero** [comment]
@cleidigh fyi, what is your strategy for the size of the list widget?

@yuval-gilboa from that screenshot it is not clear to me if the last element has more text?

**Comment by yuval-gilboa** [comment]
No the last element in the dropdown is shown in full. The expanded dropdown is fine. The problem is that in the collapsed state it is narrower than in the expanded state and then the text is cut.

**Comment by bpasero** [comment]
@yuval-gilboa got it. this is just a matter of how much space we reserve for the dropdown.

**Comment by Tyriar** [comment]
@isidorn I believe I created a similar issue after you did some refactoring and you just increased the width a little? It's much easier to hit the max width now:

![image](https://user-images.githubusercontent.com/2193314/36431486-915fa0e4-160c-11e8-9703-6bebaecb11ae.png)

**Comment by isidorn** [comment]
@Tyriar it is possible to have a better layouting strategy in the title area, however the issue is with the pushing of elements and who has priority. It can get quite complex if multiple of elements in that area have a variable width.
Currently I am using flex for everything to work nicely. People who want to play with this and try to fix it are very welcome, code pointer
https://github.com/Microsoft/vscode/blob/isidorn/searchPanel/src/vs/workbench/browser/parts/media/compositepart.css#L11

**Comment by yuval-gilboa** [comment]
@isidorn  I tested the following fix (written in .less format) and it works. It automatically expands/contracts the selection box based on its contents, without affecting the overall flex layout of the title bar.
 
Hope this helps.

```less
.monaco-workbench > .part.panel > .composite.title > .title-actions {
   flex-grow: 1;                 // allow the actions area to grow (was set to 0 by some other rule)

   & .actions-container {
      display: block;            // let the actions container to fit to content

      & .select-container {
         max-width: none;        // remove the hard-coded max-width constraint (was set to 170px)

         & .select-box {
            margin-top: 0;       // fix the vertical position of the selection box
            margin-bottom: 7px;
         }

      }
   }
} 
```
