### ISSUE TITLE
Indent style from pasted content should be honored

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#46381]
I have the following CSS code:

```css
body {
  background-color: black;
}
```

I paste it into VSC. Because CSS is set to use 4 spaces by default in my VSC, this gets formatted as:

```css
body {
    background-color: black;
  }
```

This is the worse of both worlds, because not only does it change the indentation from 2 spaces to 4, it also indents the closing brace by two spaces.

VSC should instead get the indent style of the pasted content and apply it to that document, at least if the document is empty, as was the case in the examples above.
