### ISSUE TITLE
[css] Unknown property: 'overscroll-behavior'

### ISSUE THREAD

**Issue by nicolashenry** [Microsoft/vscode#46866]
- VSCode Version: 1.21.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open a css file
2. Add overscroll-behavior property somewhere : 
```css
.my-selector {
    overscroll-behavior: contain;
}
```
3. Warning occurs: ```Unknown property: 'overscroll-behavior'```

Does this issue occur when all extensions are disabled?: Yes
