### ISSUE TITLE
[css] Problem with `grid-template` shorthand of CSS Grid Layout.

### ISSUE THREAD

**Issue by alxmcr** [Microsoft/vscode#46902]
Issue Type: <b>Bug</b>

1. Create a CSS file. For example: `styles.css`
2. Please, write this lines in `styles.css`:

```css
main {
  height: 100vh;
  display: grid;
  grid-gap: 10px;
  font-family: sans-serif;
    
  /* Shorthand 'grid-template' */
    grid-template: 
    [ini] 'header header header' 1fr
    [contenido-start] 'left1 info right1' 1fr
    'left1 info right2' 1fr
    'left1 footer footer' 1fr [end]
    / 
    [ini] 1fr [info-start] 2fr 1fr [end];    
}
```

3. (Windows 10) Press `CTRL + shift + M` or Click `View > Problems`

![semi-colon expected](https://image.ibb.co/i9RNEn/vscode_error_1.png)

**Error message:** `semi-colon expected`

I tried put it in the same line.

```css
main {
  height: 100vh;
  display: grid;
  grid-gap: 10px;
  font-family: sans-serif;
    
  /* Shorthand 'grid-template' */
    grid-template: 
    [ini] 'header header header' 1fr
    [contenido-start] 'left1 info right1' 1fr
    'left1 info right2' 1fr
    'left1 footer footer' 1fr [end] / [ini] 1fr [info-start] 2fr 1fr [end];    
}
```

But, Unfortunately, the problem continued.  I think, the problem is with the square brackets `[ ]`, because I commented them:

```css
main {
  height: 100vh;
  display: grid;
  grid-gap: 10px;
  font-family: sans-serif;
    
  /* Shorthand 'grid-template' */
    grid-template: 
    [ini] 'header header header' 1fr
    [contenido-start] 'left1 info right1' 1fr
    'left1 info right2' 1fr
    'left1 footer footer' 1fr /*[end]*/
    / 
    /*[ini]*/ 1fr [info-start] 2fr 1fr [end];    
}
```

**Code without warnings**

![Code without warnings](https://image.ibb.co/dP7OLS/vscode_ok_1.png)

Please, Can you help me to resolve this problem? I would appreciate your help 🙂. I don't know, How Can I resolve it?

Corrections or comments are completely welcome. Have a nice day!

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:46:47.128Z)
OS version: Windows_NT x64 10.0.16299

Extensions: none
Reproduces without extensions
