### ISSUE TITLE
[scss] Lint error when define variable in keyframes at-rule

### ISSUE THREAD

**Issue by ZerglingGo** [Microsoft/vscode#47285]
- VSCode Version: 1.22.1
- OS Version: Windows 10 Pro 1709 (Build 16299.309)

Steps to Reproduce:

1. Write below code in SCSS Language mode:
```scss
@keyframes test-keyframe {
    @for $i from 1 through 60 {
        $s: ($i * 100) / 60 + "%";
        #{$s} {
            $x: ($i % 10 - 1) * -396px;
            $y: ceil($i / 10) * -158px;
            background-position: $x $y;
        }
    }
}
```

Does this issue occur when all extensions are disabled?: Yes

Error messages:
```json
{
	"resource": "Untitled-1",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "css-rcurlyexpected",
	"severity": 8,
	"message": "} expected",
	"source": "scss",
	"startLineNumber": 3,
	"startColumn": 9,
	"endLineNumber": 3,
	"endColumn": 11
}
```
```json
{
	"resource": "Untitled-1",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "css-ruleorselectorexpected",
	"severity": 8,
	"message": "at-rule or selector expected",
	"source": "scss",
	"startLineNumber": 10,
	"startColumn": 1,
	"endLineNumber": 10,
	"endColumn": 2
}
```

This code is compiled successfully in Webpack (Laravel Mix).
