### ISSUE TITLE
[css] Parse error with space in global rule

### ISSUE THREAD

**Issue by majelbstoat** [Microsoft/vscode#49010]
Migrated from here: https://github.com/Grimones/vscode-styled-jsx-languageserver/issues/3

A small bug in the CSS language server causes an incorrect parse error on legal syntax when there is a space between (pseudo-)selectors in a `:global` style rule.

- VSCode Version: 1.22.2
- OS Version: OSX 10.13.4

Steps to Reproduce:

Define this rule in a plain css file:

```css
:global(.output ::selection) {
  background: red;
}
```

Expected outcome: the rule is accepted.

Actual outcome: parse error: `[css] ) expected`

Note that defining the rule without the space does not trigger a parse error, but gives materially different results in the browser.

```css
:global(.output::selection) {
  background: red;
}
```
