### ISSUE TITLE
Hovering over inline color swatch does not reveal built-in color picker

### ISSUE THREAD

**Issue by brianblakely** [Microsoft/vscode#49232]
Issue Type: <b>Bug</b>

1. Create a new CSS file with this content:
    ```css
    #p1 {background-color: #ff0000;}   /* red */
    #p2 {background-color: #00ff00;}   /* green */
    #p3 {background-color: #0000ff;}   /* blue */
    ```
2. Hover over the inline swatch that should appear beside any of the three color values.

**Expected Result**

The built-in color picker should appear when hovering over the inline color swatch.

**Actual Result**

Hovering over the inline color swatch reveals a tooltip describing the purpose of the `background-color` property.

*****

VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:14.634Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (7.29GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled
