### ISSUE TITLE
[scss] pseudo selector function with interpolation

### ISSUE THREAD

**Issue by HitalloExiled** [Microsoft/vscode#49589]
- VSCode Version: 1.23.0
- OS Version: Windows 10

Steps to Reproduce:

Input:
```sass
:host
{
  display: none;
  
  @at-root 
  #{&}([foo=bar][bar=foo]) // Error: "{ expected"
  {
    display: block;
  }
}
```

On https://www.sassmeister.com/ and with node-sass this style transpile fine to:
```css
:host {
  display: none;
}
:host([foo=bar][bar=foo]) {
  display: block;
}
```

Does this issue occur when all extensions are disabled?: Yes/No
Yes
