### ISSUE TITLE
Add theme key for the "alternating" row color in keybindings editor/settings UI and change default

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#49655]
@roblourens pointed out this color https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/media/keybindingsEditor.css#L74, this makes the alt row overly grey in mine and other themes. We should add a key for this.

<img width="103" alt="screen shot 2018-05-10 at 4 50 11 pm" src="https://user-images.githubusercontent.com/2193314/39899719-5b38aa02-5472-11e8-8012-125c7d0d1831.png">

Also I think the default should be `rgba(255,255,255,0.2)` for dark themes and `rgba(0,0,0,0.2)` for light themes. This will just lighten or darken the color as opposed to moving it closer towards grey.

**Comment by Tyriar** [comment]
This also applies to the extensions editor tables as well. Here's what the CSS would look like if we wanted to change the colors:

```css
.keybindings-editor > .keybindings-body > .keybindings-list-container .monaco-list-row.odd:not(.focused):not(.selected):not(:hover),
.keybindings-editor > .keybindings-body > .keybindings-list-container .monaco-list:not(:focus) .monaco-list-row.focused.odd:not(.selected):not(:hover),
.keybindings-editor > .keybindings-body > .keybindings-list-container .monaco-list:not(.focused) .monaco-list-row.focused.odd:not(.selected):not(:hover) {
	background-color: rgba(0, 0, 0, 0.02);
}
.vs-dark .keybindings-editor > .keybindings-body > .keybindings-list-container .monaco-list-row.odd:not(.focused):not(.selected):not(:hover),
.vs-dark .keybindings-editor > .keybindings-body > .keybindings-list-container .monaco-list:not(:focus) .monaco-list-row.focused.odd:not(.selected):not(:hover),
.vs-dark .keybindings-editor > .keybindings-body > .keybindings-list-container .monaco-list:not(.focused) .monaco-list-row.focused.odd:not(.selected):not(:hover) {
	background-color: rgba(255, 255, 255, 0.02);
}
.hc-black .keybindings-editor > .keybindings-body > .keybindings-list-container .monaco-list-row.odd:not(.focused):not(.selected):not(:hover),
.hc-black .keybindings-editor > .keybindings-body > .keybindings-list-container .monaco-list:not(:focus) .monaco-list-row.focused.odd:not(.selected):not(:hover),
.hc-black .keybindings-editor > .keybindings-body > .keybindings-list-container .monaco-list:not(.focused) .monaco-list-row.focused.odd:not(.selected):not(:hover) {
	background-color: rgba(255, 255, 255, 0.1);
}
```
