### ISSUE TITLE
[YAML] Syntax highlighting quirk

### ISSUE THREAD

**Issue by Stanzilla** [Microsoft/vscode#49752]
- VSCode Version: 1.23.1
- OS Version: Windows 10 1803 x64

Steps to Reproduce:

1. Create a new YAML file
2. Paste

```
language: minimal

addons:
  apt:
    packages:
    - luarocks

install:
  - eval $(luarocks path --bin)
  - luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"

script:
  - [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]] && ./wowace_translations.sh
  - [[ "$TRAVIS_TAG" == "8.0-"* ]] && curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -og 8.0
  - [[ "$TRAVIS_TAG" != "8.0-"* ]] && curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -o


notifications:
  email:
    on_failure: always
    on_success: never

cache:
  apt: true
  directories:
    - $HOME/.luarocks
```

Does this issue occur when all extensions are disabled?: Yes

![code_2018-05-12_15-45-15](https://user-images.githubusercontent.com/75278/39957938-9b050ce0-55fb-11e8-8c57-537ae3693e78.png)

Not sure what causes it to highlight the different script lines differently.
