### ISSUE TITLE
[scss] no code completion after complex selector with pseudo class in selector

### ISSUE THREAD

**Issue by bambusoideae** [microsoft/vscode#51156]
- VSCode Version: 1.23.1
- OS Version: openSUSE Leap 15.0 (KDE)

Steps to Reproduce:

1. This two case IntelliSense is not working after complex selector in SCSS
The first:

```scss
.story {
  &:hover &__caption {
    opacity: 1;
    transform: translate(-50%, -50%);
  }

  // BEGIN: Lost autocomplete
}
```

The second:
```scss
.story {
  &:not(:last-child) {
    padding-bottom: 10rem;
  }

  // BEGIN: Lost autocomplete
  //.why
  // .why::not
}
```
2. IntelliSense for selector with pseudo class is not working after "BEGIN: Lost autocomplete" comments. Such as
```scss
&:hov
.why:hov
```

With real scss file sometime it look like #18340 (Add extra colon).

Does this issue occur when all extensions are disabled?: Yes
