### ISSUE TITLE
Use proper font family for East Asian languages (CJK)

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#5260]
- VSCode Version: 1.0
- OS Version: Windows 10 x64 1511

![image](https://cloud.githubusercontent.com/assets/240091/14535552/f8013ece-02a0-11e6-844a-c4a16996dc60.png)

Electron assigns a **serif** font, `SimSun`, as the default **sans-serif** font for zh-CN. This is extremely inconsistent.

A workaround may be
```css
whatever:lang(zh-CN) {
    font-family: <your current setting>, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Source Han Sans SC", sans-serif;
}
whatever:lang(zh-TW) {
    font-family: <your current setting>, "PingFang TC", "Microsoft JhengHei", "Source Han Sans TC", sans-serif;
}
```

**Comment by jackqq** [comment]
Hi @be5invis, I guess you have either installed additional fonts (such as Monaco) or modified the FontSubstitutes registry settings or so. I have the default font set and VSCode falls back to Consolas in the editing area. It looks OK.

![vscode-zh-cn-01](https://cloud.githubusercontent.com/assets/7012225/14557191/a2f26c76-032e-11e6-94f1-669874d6cf86.png)


However, in the explorer area the text looks a little blurry, but can be fixed by increasing the font-size to 12px. Please note the difference between two Chinese lines in the image below, 资源管理器 (original) and 工作文件 (up-sized to 12px). I guess it's because at 12px SimSun performs well with raster glyphs instead of vector ones, which can be quite blurry at small sizes.

![vscode-zh-cn-02](https://cloud.githubusercontent.com/assets/7012225/14557201/a9fae76e-032e-11e6-9e6b-c304b444883b.png)    ![vscode-zh-cn-03](https://cloud.githubusercontent.com/assets/7012225/14557202/ac1c6522-032e-11e6-8854-ae140f5a2aff.png)

**Comment by be5invis** [comment]
@jackqq The edit area uses [Inziu Iosevka SC](http://be5invis.github.io/Iosevka/inziu.html). What I am talking about is the font used in the UI, instead of the editing area, since it is configurable, and you can actually set to ANY fallback sequence you want.

**Comment by dbaeumer** [comment]
@bpasero I move this to you. If we should set different fonts in the explorer depending on the UI language you can use the API vs/base/common/platform#language to know the languge used for the UI.

**Comment by bpasero** [comment]
@dbaeumer the original bug report is about the editor though? if there are multiple issues discussed in here I suggest to split them up by topic.

**Comment by be5invis** [comment]
@dbaeumer No, this bug has no relationship with the editor. It's just the “UI”. Actually we can specify the fallback requense for the editor.

**Comment by bpasero** [comment]
@be5invis in your screenshot, you say the font in the explorer is broken? it looks good to me.

**Comment by bpasero** [comment]
@be5invis can you try the workaround you describe to see if it helps?

**Comment by be5invis** [comment]
@bpasero The Latin fonts are OK, but focus on the “工作目录” and “资源管理器”. They are in consistent with the Latin one (which is Segoe UI).

**Comment by be5invis** [comment]
@bpasero 
![image](https://cloud.githubusercontent.com/assets/240091/14559259/f825992e-0339-11e6-9918-17c7198afb41.png)

**Comment by bpasero** [comment]
@be5invis does it work adding those other fonts you mentioned in your comment?

**Comment by be5invis** [comment]
@bpasero If I manually add fonts to `.monaco-shell` using the dev tool then yes, it works.
![image](https://cloud.githubusercontent.com/assets/240091/14563091/ae2cce1e-0352-11e6-8e9b-7e029bf5d2f9.png)
![image](https://cloud.githubusercontent.com/assets/240091/14563106/bfb1f9fc-0352-11e6-8a1a-d0634e254fd4.png)

**Comment by bpasero** [comment]
@be5invis ok thanks!

**Comment by Tyriar** [comment]
@dbaeumer is `lang` on `html` going to be set to the correct language in https://github.com/Microsoft/vscode/issues/3841 ? It would be nice to utilize the `:lang` pseudo-class for this as mentioned in https://github.com/Microsoft/vscode/issues/5260#issue-148417433

**Comment by bpasero** [comment]
I would appreciate if people could tell the `font-family` to use for Japanese as well. I like the idea of connecting this with the `lang` attribute on the root element.

**Comment by be5invis** [comment]
@bpasero That's exactly what I suggested. 
```css
.monaco-shell:lang(zh-CN){
    font-family: ...; /* Chinese fallback sequence*/
}
.monaco-shell:lang(ja){
    font-family: ...; /* Japanese fallback sequence */
}
```

**Comment by bpasero** [comment]
Does simplified vs traditional Chinese make any difference?

**Comment by be5invis** [comment]
@bpasero Yes. zh-CN and zh-TW should use different fallback sequence to provide correct glyphs. An example of different character shapes in East Asia is this:
![](https://raw.githubusercontent.com/adobe-fonts/locl-test/master/resources/locl-example.jpg)

**Comment by bpasero** [comment]
Ok, I was asking if someone could comment here with the 3 different font families for Traditional, Simplified and Japanese.

**Comment by be5invis** [comment]
@bpasero 
Five actually, `zh-CN`, `zh-TW`, `zh-HK`, `ja`, `ko`. Though for `zh-HK` there may not be a specialized font designed for it.

**Comment by bpasero** [comment]
Well, but we do not have translations for all 5 of those languages.

**Comment by bpasero** [comment]
Actually: Simplified Chinese, Traditional Chinese, Japanese, Korean

**Comment by be5invis** [comment]
@bpasero If `zh-HK` is not provided, then it can be removed :)

**Comment by anyong** [comment]
Noto CJK has excellent support for all of these variants and would provide a consistent UI in all CJK languages. I'm not sure how other Chinese users feel about Noto but I personally am a huge fan. Or does the font need to be a system font that comes with the OS?

**Comment by be5invis** [comment]
@anyong 
Noto CJK (and Source Han Sans) is LARGE and they are CFF.
A well-hinted TTF is even larger.

**Comment by anyong** [comment]
I'm not sure how code manages fonts but presumably for UI only a small subset of a single variant is needed. Extracting just characters used in the UI would be negligible size-wise...

**Comment by be5invis** [comment]
@anyong
Subsetting a font is hard, especially when it is a CFF.
My suggestion is simply using the system font.

**Comment by bpasero** [comment]
I think there is a general need to be able to set the overall font for the UI outside the editor and I think this would solve the issue of people having custom fonts installed that they want to use.

However, in this issue we want to pick a font family that solves the problem for all users by relying on good OS installed fonts.

I would appreciate for input on which families to use on Windows, Mac and Linux for which of the three languages.

**Comment by anyong** [comment]
@bpasero So for UI the equivalent of "sans serif" in Chinese is *hei ti* (黑體), and in Japanese and Korean *gothic*. I've put together this list by locale and operating system using *hei ti* / * gothic* fonts, the latest default OS UI font where possible, or in the case of Linux, the most popular alternative(s). For the multi-locale Chinese fonts, both simplified and traditional locales are included in the font and they will simply work as expected.

Thanks for the attention to detail here, it's really very important that the font looks correct for the user in each specific locale (even if the change is as small as the dot at the top slanting to the left or right, etc.)

Locale | OS | Font
:-- | :-- | :--
zh-CN, zh-TW | Windows | Microsoft Yahei (微软雅黑)
zh-CN | OSX >= 10.11 | PingFang SC (苹方-简)
zh-TW | OSX >= 10.11 | PingFang TC (蘋方-繁)
zh-CN | OSX >= 10.6 | Heiti SC (黑体-简)
zh-TW | OSX >= 10.6 | Heiti TC (黑體-繁)
zh-CN, zh-TW | OSX < 10.6 | STXihei (华文细黑)
zh-CN, zh-TW | Linux | WenQuanYi (文泉驿正黑)
ja | Windows | Meiryo (メイリオ)
ja | OSX | Hiragino Kaku Gothic (ヒラギノ角ゴ)
ja | Linux | Sazanami Gothic (さざなみゴシック) [Fallbacks: IPA Gothic, Mona Font]
ko | Windows |
ko | OSX >= 10.8 | Apple SD Gothic Neo (애플 SD 산돌고딕 Neo)
ko | OSX < 10.8 | AppleGothic (애플고딕)
ko | Linux | UnDotum (은돋움) [Fallback: FBaekmuk Gulim (백묵굴림)]

**Comment by be5invis** [comment]
@anyong Microsoft YaHei is not suitable for zh-TW.
The proper one is Microsoft Jhenghei.

**Comment by anyong** [comment]
Actually 雅黑 does support 繁體字 correctly in zh-TW, but 正黑 is fine, too.

**Comment by bpasero** [comment]
@anyong thanks so much, this list is very useful. maybe the table could be edited based on feedback in this issue from others and this week I can start looking into adding it in together with #4433.

**Comment by bpasero** [comment]
@be5invis just curios, our rules seem to be this:

`font-family: "Segoe WPC", "Segoe UI", "SFUIText-Light", "HelveticaNeue-Light", sans-serif, "Droid Sans Fallback"`

Does it already work better if you remove the last rule so that `sans-serif` becomes the fallback:

`font-family: "Segoe WPC", "Segoe UI", "SFUIText-Light", "HelveticaNeue-Light", sans-serif`

**Comment by be5invis** [comment]
@bpasero 

No.
`Droid Sans Fallback` is Android-only, so on Windows and OS X the rule is identical to `font-family: "Segoe WPC", "Segoe UI", "SFUIText-Light", "HelveticaNeue-Light", sans-serif`.

My suggestion is:

* For `zh-CN` : `font-family: "Segoe WPC", "Segoe UI", "SFUIText-Light", "HelveticaNeue-Light", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Source Han Sans SC", sans-serif`
* For `zh-TW` : `font-family: "Segoe WPC", "Segoe UI", "SFUIText-Light", "HelveticaNeue-Light", "PingFang TC", "Microsoft Jhenghei", "Source Han Sans TC", sans-serif`
* For `ja` : `font-family: "Segoe WPC", "Segoe UI", "SFUIText-Light", "HelveticaNeue-Light", "Hiragino Kaku Gothic", "Meiryo", "Source Han Sans J", "Sazanami Gothic", "IPA Gothic", sans-serif`
* For `ko` : `font-family: "Segoe WPC", "Segoe UI", "SFUIText-Light", "HelveticaNeue-Light", "Apple SD Gothic Neo", "AppleGothic", "Malgun Gothic", "Nanum Gothic", "Dotom", "Source Han Sans K", "UnDotum", "FBaekmuk Gulim", sans-serif`

**Comment by bpasero** [comment]
Thanks much, I can apply these rules and people will have a chance to verify these improvements from our next insider build later this week.

**Comment by espresso3389** [comment]
@be5invis,

For `ja`, `"Hiragino Kaku Gothic Pro"` seems better than `"Hiragino Kaku Gothic"`.
At least, I cannot find web sites using `"Hiragino Kaku Gothic"`.

**Comment by be5invis** [comment]
@espresso3389 thanks

**Comment by bpasero** [comment]
Pushed a change to pick up the font-family from https://github.com/Microsoft/vscode/issues/5260#issuecomment-211505841

We plan to release a new insider soon so that this can be verified.

Thanks for everyone's help and looking forward to hear back how this change goes!

**Comment by be5invis** [comment]
@bpasero Where is the `lang` attribute assigned to? If it is not assigned to the element you specify a CSS to (i.e. `.monaco-shell`) the style will not work.
If the `lang` attribute is assigned to the `<html>`, the style should be this: (for `.monaco-shell`):

```css
.monaco-shell { font-family: "Segoe WPC", "Segoe UI", "SFUIText-Light", "HelveticaNeue-Light", sans-serif, "Droid Sans Fallback"; }
:lang(zh-Hans) .monaco-shell { font-family: "Segoe WPC", "Segoe UI", "SFUIText-Light", "HelveticaNeue-Light", "Noto Sans", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Source Han Sans SC", "Source Han Sans CN", "Source Han Sans", sans-serif; }
:lang(zh-Hant) .monaco-shell { font-family: "Segoe WPC", "Segoe UI", "SFUIText-Light", "HelveticaNeue-Light", "Noto Sans", "PingFang TC", "Microsoft Jhenghei", "Source Han Sans TC", "Source Han Sans", "Source Han Sans TW", sans-serif; }
:lang(ja) .monaco-shell { font-family: "Segoe WPC", "Segoe UI", "SFUIText-Light", "HelveticaNeue-Light", "Noto Sans", "Hiragino Kaku Gothic Pro", "Meiryo", "Source Han Sans J", "Source Han Sans JP", "Source Han Sans", "Sazanami Gothic", "IPA Gothic", sans-serif; }
:lang(ko) .monaco-shell { font-family: "Segoe WPC", "Segoe UI", "SFUIText-Light", "HelveticaNeue-Light", "Noto Sans", "Apple SD Gothic Neo", "AppleGothic", "Malgun Gothic", "Nanum Gothic", "Dotom", "Source Han Sans K", "Source Han Sans JR", "Source Han Sans", "UnDotum", "FBaekmuk Gulim", sans-serif; }
```
