### ISSUE TITLE
Setting to change the image preview background

### ISSUE THREAD

**Issue by PmmaGit** [Microsoft/vscode#52717]
Hello,

Right now whenever you open an image file in VSCode, a .png or a .ico for example, 
the image preview will render with the checkered white and gray squares as the background.

It would be nice if we could edit this behavior with a setting in the user settings file, something like
`"imagepreview.background" = css_color`.

In the meantime, is there a way to change this at all?

**Comment by TomSputz** [comment]
This has my support - Imo, the node that needs to be exposed is
```css
.vs-dark .monaco-resource-viewer.image {
    background-image: linear-gradient(45deg,#141414 25%,transparent 0,transparent 75%,#141414 0,#141414),linear-gradient(45deg,#141414 25%,transparent 0,transparent 75%,#141414 0,#141414);
}
```
Though I can understand the want to keep the pattern there consistent, the way that it works at the moment means that using #141414 as the background colour for the editor makes this checker pattern invisible. 

Potentially it could be automatically set to the inverse of the "editor.background" property, however that would look unpleasant in many themes, not to mention some of the ones that want to keep that background subtle.

For now, @PmmaGit , all we can do to edit the area is set 
```json
"workbench.colorCustomizations": {
        "editor.background": "[Your colour]"
    },
```
in user settings - this changes the white background to whichever colour you want, but also changes the background colour for any editor so far as I can tell. Not ideal
