### ISSUE TITLE
Intellisense parsing error in CSS with Media Queries

### ISSUE THREAD

**Issue by steinhaug** [Microsoft/vscode#53619]
Looks like the parser breaks when media queries are used, example:
`
    @media only screen and (min-width: 480px) {
        .xs-text-right { text-align-right; }
    }
    @media only screen and (min-width: 768px) {
        .sd-text-right { text-align-right; }
    }
`

Screenshot here with explained error messages: https://imgur.com/a/YONrVrg

**Comment by octref** [comment]
You have the wrong grammar. It's `text-align: right`, not `text-align-right`.

```css

@media only screen and (min-width: 480px) {
  .xs-text-right {
    text-align: right;
  }
}

@media only screen and (min-width: 768px) {
  .sd-text-right {
    text-align: right;
  }
}
```
