### ISSUE TITLE
editor.detectIndentation does not change indentation

### ISSUE THREAD

**Issue by akaRem** [Microsoft/vscode#54034]
- VSCode Version:
```
1.25.0
0f080e5267e829de46638128001aeb7ca2d6d50e
x64
```
- OS Version: 
```
macOs Sierra 10.12.6 (16G1408)
```
Steps to Reproduce:

1. add custom editor.tabSize for language, for example
```
{
  "editor.detectIndentation": true,
  "editor.tabSize": 6,
  "[yaml]": {
    "editor.tabSize": 8,
  }
}
```
2. restart VSCode (not required)
3. open yaml file, for example with following content:
```
---
- job-template:
    name: 'helper-{job-name}'
    description: Sample
    properties:
    - heavy-job:
        weight: 1
    - throttle:
        max-total: 1
        option: project
    - build-discarder:
        days-to-keep: 10
        num-to-keep: 50
        artifact-days-to-keep: 30
        artifact-num-to-keep: 100
```
4. Force detect indent (not required)

In status bar 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/1472728/42567783-9043412c-8513-11e8-8a0a-4bf5f99b6229.png">
indent is 4 (`Пробелов == Spaces` )

5. Click to change

<img width="538" alt="image" src="https://user-images.githubusercontent.com/1472728/42567815-b940ee44-8513-11e8-98f8-c981f8ea0e46.png">

It detected that indent should be 8, but set as 4
`Настроенный размер шага табуляции == configured indentation`

Does this issue occur when all extensions are disabled?: Yes/No
**YES**
