### ISSUE TITLE
CSS Syntax highlighting broken after upgrade to 1.25

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#54145]
- VSCode Version: 1.25.0
- OS Version: Windows 10

While using the css `@value` declaration within my code, the immediately succeeding block gets a different syntax highlight from the rest of the code. This is new in vscode 1.25 - it was working fine till 1.24.

Steps to Reproduce:

1. Write this code in vscode:

```css
@value main from 'css/shared/theme.css';

.title {
  font-size: 2rem;
  color: main;
  font-weight: lighter;
  text-transform: uppercase;
  letter-spacing: 0.1em;
}

.grid {
  height: 30rem;
  width: 100%;
  margin-bottom: 3rem;
}
```

2. See the `.title` incorrectly highlighted

![image](https://user-images.githubusercontent.com/760112/42622192-6f0f7078-85dd-11e8-919f-a3df32c1339d.png)

Does this issue occur when all extensions are disabled?: Yes
