### ISSUE TITLE
To Make it possble to change font-family of .monaco-shell:lang(*) & .context-view.monaco-menu-container

### ISSUE THREAD

**Issue by Copay** [Microsoft/vscode#54546]
I've found that the font-family of `.monaco-shell:lang(*)` & `.context-view.monaco-menu-container` is fixed, which means I can't change it for a better view as the default font doesn't looks so clear on my screen.

So can it be changeable in `User Settings` ?

the css snippets list below.

```css
.monaco-shell:lang(zh-Hans) {/* maybe other languages */
    font-family: -apple-system,BlinkMacSystemFont,Segoe WPC,Segoe UI,HelveticaNeue-Light,Noto Sans,Microsoft YaHei,PingFang SC,Hiragino Sans GB,Source Han Sans SC,Source Han Sans CN,Source Han Sans,sans-serif;
}
```
```css
.monaco-shell {
    height: 100%;
    width: 100%;
    margin: 0;
    padding: 0;
    overflow: hidden;
    font-size: 11px;
    user-select: none;
    font-family: -apple-system,BlinkMacSystemFont,Segoe WPC,Segoe UI,HelveticaNeue-Light,Ubuntu,Droid Sans,sans-serif;
}
```
```css
.context-view.monaco-menu-container {
    font-family: Segoe WPC,Segoe UI,\.SFNSDisplay-Light,SFUIText-Light,HelveticaNeue-Light,sans-serif;
    outline: 0;
    box-shadow: 0 2px 8px #a8a8a8;
    border: none;
    color: #646465;
    background-color: #fff;
    -webkit-animation: fadeIn 83ms linear;
    animation: fadeIn 83ms linear;
}
```
