### ISSUE TITLE
[css] use folding regions in outline 

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#55068]
It would be great to see CSS code-folding regions used as Outline sections along with their coinciding header, in much the same way that Markdown headings appear right now.

For example, this code:
```css
/*#region This is a section */
.classA {
  color: blue;
}

.classB {
  color: green;
}
/*#endregion*/
```
Currently creates a collapsible section in VSCode, which is incredibly helpful. However, the new Outline view still only shows a single-level list of every single rule in the document, so you can't see where those collapsible sections start and end:

![image](https://user-images.githubusercontent.com/2294248/43208954-927a49a4-8ff9-11e8-80c7-f585acfa3bd5.png)

I'm using VSCode 1.26.0-insider on Windows 10.
