### ISSUE TITLE
Color picker is not preserving HEX when color length is equal 3

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#55331]
Issue Type: <b>Bug</b>

When using 6-char length HEX color it's working fine:
```css
body {
    background-color: #ffffff;
}
```

But using 3-char:
```css
body {
    background-color: #fff;
}
```
The result is RGB, which is not what was expected.

P.S. I know I can click on color to change its format, that's not the best option.

---

VS Code version: Code - Insiders 1.26.0-insider (dae69dbf00357ff8a3fe740a1f211d66b0b4681c, 2018-07-27T05:17:55.890Z)
OS version: Windows_NT x64 10.0.17134
