### ISSUE TITLE
Wrong YAML syntax highlighting in some corner cases for strings

### ISSUE THREAD

**Issue by Yajo** [Microsoft/vscode#55355]
Issue Type: <b>Bug</b>

Comments inside the image explain the wrong syntax highlighting problems; see:
![captura de pantalla de 2018-07-30 10-20-20](https://user-images.githubusercontent.com/973709/43388884-402dbbc6-93e2-11e8-8b2e-6708f062c195.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.17.6-200.fc28.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX-7500 Radeon R7, 10 Compute Cores 4C+6G (4 x 1722)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 2|
|Memory (System)|14.63GB (0.15GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
fish|Ted|0.0.4
vscode-markdownlint|Dav|0.19.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
xml|Dot|2.3.1
gc-excelviewer|Gra|2.1.25
beautify|Hoo|1.3.2
restructuredtext|lex|65.0.0
fish-ide|lun|0.3.1
rainbow-csv|mec|0.4.2
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
language-gettext|mro|0.1.1
vscode-language-pack-es|MS-|1.25.2
python|ms-|2018.7.1
azure-account|ms-|0.4.2
vscode-docker|Pet|0.1.0
qub-xml-vscode|qub|1.2.8
sass-indented|rob|1.4.9
jinja|who|0.0.8

</details>

**Comment by aeschli** [comment]
@Yajo Would you mind pasting the code example here? Thanks a lot!

**Comment by texastoland** [comment]
I just reproduced it:

```yaml
key: string
  "flows" | here
```

**Comment by Yajo** [comment]
```yaml
# Highlight here is OK
- name: build docker-compose project {{ project.key }}
  # Highlight is misleading. All of this block is a string
  split spaces: |
    - i'm a string
    - [not an array]
    - {nor a dict}
  # same here
  join spaces: >
    - i'm a string
    - [not an array]
    - {nor a dict}
  when:
    # This is all a single string
    - not build_cache|bool or "ERROR: for odoo" in result.stderr
  command:
    # Highlighting in line 42 is misleading. All of this is a string too
    docker-compose build --pull
    {% if not build_cache|bool %} --no-cache {% endif %}
```
