### ISSUE TITLE
css grammar: scope flex/grid keywords such as self-end like other keywords

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55644]
From #53606

For the css:

```css
.test {
    justify-items: self-end;
    text-align: center;
}
```

Notice that `self-end` is not colored the same way as `center`:

![screen shot 2018-08-02 at 12 15 45 pm](https://user-images.githubusercontent.com/12821956/43578002-ce57811c-964d-11e8-9a6f-fde5ce4cad0c.png)

Does this issue occur when all extensions are disabled?: Yes
