### ISSUE TITLE
[css] outline information is wrong

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#56478]
* have the snippet below
* open outline, breadcrumbs, or quick outline
* 🐛 you have two entries

```css
foo-tree-row:not(.selected) {
    color: red;
    background-attachment: fixed;
}
```
