### ISSUE TITLE
[scss] warn if declaration ends without a semicolon

### ISSUE THREAD

**Issue by rowild** [microsoft/vscode#56761]
Done
 Not Done

- VSCode Version: 1.26.1
- OS Version: Mac OS 10.13

Steps to Reproduce:

1. Disable all VSCode extensions
2. Create a Vue-Cli 3 project
3. Create a scss file with the following code:

```scss
.x-change {
  &-enter {
    transform: translateX(100%) // <== Please pay attention to the missing semicolon here!

    &-to {
      transform: translateX(0);
    }
  }
}
```

4. Compile the project with "npm run serve"

Does this issue occur when all extensions are disabled?: Yes

EXPECTED: 

VSCode should indicate the missing semicolon as error.

WHAT HAPPENS:

VSCode does not recognize the missing semicolon as error and compiles, which results in wrong css that looks like this:
```css
.x-change-enter {
  transform: translateX(100%) .x-change-enter -to; // <== this is a mess!
    transform-transform: translateX(0);
}
```

FURTHER COMMENTS:

Tested with a vanilla version of phpStrom: there the error is recognized. So it cannot be a project setup error...
