### ISSUE TITLE
AutoWrapping do not provide enough granularity

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#57455]
Testing #57317

https://github.com/Microsoft/vscode/issues/36259#issue-265458405

The author specifically asked for disabling brackets but not parenthesis.
The new setting does not allow that.

Two common scenarios that I always run into:

In SCSS, let's say I have:

```scss
.foo {
  color: blue;
}
```

And I want to wrap `color: blue` in a `.bar` nested selector, so it becomes

```scss
.foo {
  .bar {
    color: blue;
  }
}
```

Currently the editing process is very cumbersome because of auto-closing `{`

```scss
// enter .bar{
.foo {
  .bar {}
  color: blue;
}

// Press Enter
.foo {
  .bar {

  }
  color: blue;
}

// Then I need to move `color: blue;` into the middle of that brackets
```

I would prefer having no auto wrapping for bracket in this case.

Same case if I want to wrap some JS code into a function

```js
console.log('foo')

// Wrapping that into
function () {
  console.log('foo')
}
```
