### ISSUE TITLE
SCSS parser have problems with trailing commas

### ISSUE THREAD

**Issue by bgoscinski** [Microsoft/vscode#57858]
- VSCode Version: 
```
Version: 1.27.0-insider
Commit: 7b9afc4196bda60b0facdf62cfc02815509b23d6
Date: 2018-09-03T09:14:29.879Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Set language mode to scss
2. Paste following code 
```scss
@mixin m($a,) {            // [scss] variable name expected
  a: $a;                   // [scss] { expected
}                          // [scss] at-rule or selector expected

@function f($a,) {         // [scss] variable name expected
  @return $a + 1;          // [scss] unknown at rule @return
}                          // [scss] at-rule or selector expected

.foo {
  $test1: f(3,);           // [scss] expression expected
  @include m($test1,);     // [scss] expression expected
  $test2: f($a: 4,);       // [scss] expression expected
  @include m($a: $test2,); // [scss] expression expected
}
```
3. See the problems at problems tab or hover underlines
4. It compiles fine with node-sass:
```sh
$ ./node_modules/.bin/node-sass ./Untitled-1.scss
.foo {
  a: 4;
  a: 5; }
$ ./node_modules/.bin/node-sass -v
node-sass       4.9.3   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```

Does this issue occur when all extensions are disabled?: Yes
