### ISSUE TITLE
[less] `} expected` when having nested declarations as mixin arguments

### ISSUE THREAD

**Issue by incompletude** [microsoft/vscode#60722]
VSCode last version.

Steps to reproduce:

```less
@size-desktop: 1200px;

@media-desktop: ~"(min-width:" @size-desktop ~")";

.onDesktop(@rules) { @media @media-desktop { @rules(); }};

.absolute() {
    position: absolute;
}

.onDesktop({
    .absolute;  // shows error on this line and forward
});
```

This compiles just fine, but the VSCode less parser incorrectly points to an error.
