### ISSUE TITLE
Make centered layout editor width constant.

### ISSUE THREAD

**Issue by FancyBanana** [Microsoft/vscode#61292]
Now, in centered mode, when i toggle sidebar or vertical terminal, editor's size changes even though there's clearly enough space for it to preserve it's width. It would be much nicer if it would try to retain it's width.  

![Width](https://thumbs.gfycat.com/SlimBitesizedAsianporcupine.webp)

In css talk:
```css
.editor{
  width:90%;
  max-width: 400px; /* this value is controlled by resizing editor; */
}
```

edit: added comment to css for clarification, typos
