### ISSUE TITLE
[less] syntax highlight failed when value starts with decimal point

### ISSUE THREAD

**Issue by viko16** [Microsoft/vscode#6206]
- VSCode Version: 1.0.0
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Language mode: Less
2. Code:
```less
.logo {
  width: 1.25rem;
  height: .26rem;
}
```

Screenshot:
![image](https://cloud.githubusercontent.com/assets/5064777/15105304/34552a10-15f3-11e6-8cdb-55a2014600d7.png)
