### ISSUE TITLE
Problems: Tree misalignment if an error has long message

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#62489]
1.28:

![image](https://user-images.githubusercontent.com/4033249/47928194-b6df4380-de82-11e8-991a-b599bfa825bd.png)

Repro: Write below to a css file.

```css
.foo {
  color: blue !important;
  font-family: 'Courier New', Courier, monospace;
}

.bar .foo {
  animation-delay: inherit;
  bar: 123;
  k
}
```
