### ISSUE TITLE
[scss] problem with mixin (2th)

### ISSUE THREAD

**Issue by Babelfisch** [Microsoft/vscode#65600]
The bug #56743 still occurs if the selector has more than one dash.

```scss
@mixin sc-cols($postfix) {
	.sc-col#{$postfix}-2-1 {
		@include flex-basis(50%);
		max-width: 100%;
	}
}
```

Same error as four months ago.
