### ISSUE TITLE
VS Code fails to detect the correct indentation for certain YAML files

### ISSUE THREAD

**Issue by segevfiner** [Microsoft/vscode#65668]
- VSCode Version: 1.30.1
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. Save the following as `foo.yml`:
```yaml
version: 2

jobs:
  build:
    docker:
      - circleci/golang:1.11

  environment:
    TEST_RESULTS: /tmp/test-results

  steps:
    - checkout
    - run: mkdir -p $TEST_RESULTS # create the test results directory

    - restore_cache:
        keys:
          - v1-pkg-cache

    - run:
        name: dep ensure
        command: dep ensure -v

    - run:
        name: Run unit tests
        command: |
          trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
          go test -v ./... | tee ${TEST_RESULTS}/go-test.out

    - run:
        name: Build
        command: go build -v

    - save_cache:
        key: v1-pkg-cache
        paths:
          - "/go/pkg"

    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output

    - store_test_results:
        path: /tmp/test-results
```
2. Check the detected indentation, it will be 4 spaces, despite the file being indented with 2 spaces.

I didn't change any related settings.

The code that does this is [src/vs/editor/common/model/indentationGuesser.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/indentationGuesser.ts) and using the developer tools I can see that it returns 4 spaces for this file.

Does this issue occur when all extensions are disabled?: Yes
