### ISSUE TITLE
[scss] Root-level @at-root selector in partial causes false syntax errors

### ISSUE THREAD

**Issue by briman0094** [microsoft/vscode#65976]
When placing an `@at-root` directive at the root-level of a SCSS file, Visual Studio Code's tokenizer seems to break completely, highlighting the `@at-root` and most other SCSS features in the proceeding block as syntax errors. Normally the `@at-root` selector would be useless at the root-level, but in a partial file which is included inside a selector from another file, it makes sense and is valid SCSS.

- VSCode Version: 1.30.1
- OS Version: Windows 10 build 1803

Reproduction files:

test.scss
```scss
$a-variable: 4px;

#main {
    @import "testpartial";
}

#main2 {
    background-color: red;
}
```

_testpartial.scss
```scss
.some-class {
    color: red;
}

@at-root #main2 .some-class {
    color: blue;
    padding-left: calc( #{$a-variable} + 8px );
}
```

Resulting CSS from `node-sass test.scss` (correct output):

```css
#main .some-class {
  color: red; }

#main2 .some-class {
  color: blue;
  padding-left: calc( 4px + 8px); }

#main2 {
  background-color: red; }
```

Screenshot of the false errors in Code:
![image](https://user-images.githubusercontent.com/816612/50647099-62694a80-0f3d-11e9-90a4-77e5635801a2.png)

Does this issue occur when all extensions are disabled?: Yes
