### ISSUE TITLE
Support IE10 Repeat Syntax

### ISSUE THREAD

**Issue by FizzBuzz791** [microsoft/vscode#66703]
- VSCode Version: 1.23.1
- OS Version: Windows 8

Steps to Reproduce:

1. View the following code in IE; https://s.codepen.io/fizzbuzz791/debug/EGBxdq/XBkGRZQpnRNA
2. Confirm that it's valid syntax and displays a grid with 3 columns
3. Open a CSS file in VS Code, copy the CSS from codepen and view the following error;
 
![image](https://user-images.githubusercontent.com/2747764/51363652-f594a980-1b13-11e9-9fec-90ca52d26e3b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Can you paste the code here? It looks the link is expired.

**Comment by aeschli** [comment]
Closing due to the lack of additional information

**Comment by FizzBuzz791** [comment]
Sorry, I completely missed this. Does this link work better?
https://codepen.io/fizzbuzz791/pen/EGBxdq

**Comment by aeschli** [comment]
Yes, thanks!
```css
.grid {
  display: grid;
  display: -ms-grid;
  grid-template-columns: repeat(3, 1fr);
  -ms-grid-columns: (1fr)[3];  
}

.cell1 {
  -ms-grid-column: 1;
}

.cell2 {
  -ms-grid-column: 2;
}

.cell3 {
  -ms-grid-column: 3;
}
```
