### ISSUE TITLE
[css] no code assist proposals after variable declaration

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6744]
From testing #6656

```css
:root {
  --foo: block;
  //code assist here


}
```
Code assist should show regular rule proposals, such as display or background.
