### ISSUE TITLE
Discussion: should we handle dash in default smart selection

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67495]
Testing #67236

Should we offer default smart selection for dash-separated-word? I can see arguments on both side:

- Camelcase is handled, so dash-case should be handled. (What about underscore_case?)
- For some cases it can be useful, such as all the `aria-` attributes. But if I want to update `aria-foo` to be `aria-bar`, does it hurt that much if I have to select all of `aria-foo`, type `abar` and complete?

Take this CSS snippet with some [BEM](http://getbem.com/introduction/) and some custom data:

```css
.foo:elite-class {
  font-family: AvenirNext, 'Courier New', Courier, monospace;
}
.foo::fictional-element {
  row-gap: 'foo';
}
.button {
  display: inline-block;
  background-image: linear-gradient(#EEE, #DDD);
}
.button--state-success {
  background: #569E3D linear-gradient(#79D858, #569E3D) repeat-x;
}
```

I can see both cases, when handling dash would be useful and not useful.
