### ISSUE TITLE
[css] word rule should include '-'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6752]
```css
.five {
  background-color: var(--main-bg-color);
}
```

Double click `background-color` or `--main-bg-color`. This should select the full identifer.
