### ISSUE TITLE
[css] completions for variables adds too much

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6754]
From testing #6656

```css
:root {
  --main-bg-color: block;
}
.five {
  background-color: var(-);
}
```

- Invoke code assist after `var(-`
- Pick `--main-bg-color`.
- Results in `background-color: var(var(--main-bg-color));`
