### ISSUE TITLE
[less] grammar does not highlight variables correctly

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6765]
```less
:root {
  --main-bg-color: block;
  
}
```
![image](https://cloud.githubusercontent.com/assets/6461412/15499613/6b4756a2-21a5-11e6-9ae6-c2e0db6737c2.png)
