### ISSUE TITLE
CSS variable go to definition does not follow Sass/Less @import's

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6820]
#6656

Create a.scss:

```scss
:root {
  --css-var: red;
}
```

Create b.scss:

```scss
@import "a";

a {
  background-color: var(--css-var);
}
```

Go to definition on `--css-var` doesn't work.
