### ISSUE TITLE
Language-specific OpenType Feature Names for Programming Ligatures

### ISSUE THREAD

**Issue by be5invis** [microsoft/vscode#6918]
Given the fact that in different languages, the symbol combination should be combined into a ligature are different, is it possible to provide a language-specific feature name to distinct them? For example, in C++, `>>=` should not be combined together, and we can assign a feature `XCPP` to combine `>>` only. In Haskell, `>>=` should be combined, and feature `XHS_` will be applied. The default `calt` can be restricted to "most-common" languages only.

cf. tonsky/FiraCode#192, atom/atom#11846, Microsoft/vscode#6918, chrissimpkins/Hack#211, larsenwork/monoid#155

**Comment by be5invis** [comment]
for Code, this feature can be impelmented in CSS only: Assign `font-feature-settings` to `token.<type>`, like:
```css
token.js{
    --webkit-font-feature-settings: "XJS_" 1;
    font-feature-settings: "XJS_" 1;
}
```
Perhaps it can be automated...

**Comment by be5invis** [comment]
A preview:
![image](https://cloud.githubusercontent.com/assets/240091/15580068/db383e36-2399-11e6-86ee-a7e4d0bd30e1.png)

Code is injected with this CSS:
```css
token.haskell{ font-feature-settings: "XHS_" 1 }
```
Therefore the ligature for `>>=` is only enabled in Haskell, not in C++.
