### ISSUE TITLE
Tree expands all children 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#69464]
* open outline with the SCSS sources below
* collapse the `.foo` node
* add a space to the last rule
* 🐛 all nodes expand

![feb-26-2019 17-25-35](https://user-images.githubusercontent.com/1794099/53429185-69b44e00-39ec-11e9-9e90-905d439e4506.gif)

```css
.foo {
  .foobar {
    .barfoo {
      outline-color: blue;
    }
  }
}


.fokzlb {}

.baaaa {
  counter-reset: unset; 
}
```
