### ISSUE TITLE
Improve display of inline code segments in completion/hover

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#69970]
Currently we are using `monospace` for inline `<code>`. That can fallback to a random font that doesn't go with the rest of the UI. In the below gif, it's `Courier New`. It looks totally out of the place.

![bad-font](https://user-images.githubusercontent.com/4033249/53980455-3dbc5b00-40c5-11e9-8d25-5a80864195b7.gif)

On macOS, we are using `-apple-system` which resolves to SF Next for text, so we should use SF Mono for the inline code. Here's how it would look like:

![system-font](https://user-images.githubusercontent.com/4033249/53980460-401eb500-40c5-11e9-9166-6071c7b37257.gif)

We should look at Windows and Linux and find a monospace font that matches the UI font.

**Comment by beastdestroyer** [comment]
I think perhaps one of these fonts would look nice on Windows or Linux;

- Consolas (it's used in debugger as well)
- Ubuntu (I've seen it and it's kinda like SF Mono in a sense)
- Droid Sans Mono
- DejaVu Sans Mono
- Fira Code (my fav)
- Operator Mono (another fav, but pair haha...)

You may also perhaps setting it to the editor font by default, and maybe allow users to configure the font too, like what you guys did with the terminal?

**Comment by bpasero** [comment]
PS: this is the monospace font definition as it is being used in the workbench:

```css
.mac { --monaco-monospace-font: Monaco, Menlo, Inconsolata, "Courier New", monospace; }
.windows { --monaco-monospace-font: Consolas, Inconsolata, "Courier New", monospace; }
.linux { --monaco-monospace-font: "Droid Sans Mono", Inconsolata, "Courier New", monospace, "Droid Sans Fallback"; }
```
