### ISSUE TITLE
XML syntax highlighting with other language highlighting

### ISSUE THREAD

**Issue by JeeebeZ** [Microsoft/vscode#70986]
Currently I use Sublime. I use it because almost all the work I do is XML based with different languages in different fields. 

For example: XML and Java:
```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE Rule PUBLIC>
<Rule language="beanshell" name="Testing">
  <Description>This rule is used by the connector.</Description>
  <Inputs>
    <Argument name="tested">
      <Description>
        Item being passed and tested.
      </Description>
    </Argument>
    </Inputs>
    <Returns>
      <Argument name="result">
        <Description>Returned object</Description>
      </Argument>
    </Returns>
  </Signature>
  <Source>        
    import org.apache.log4j.Logger; 
    Logger log = Logger.getLogger("app.demo.testing"); 

    log.debug("tested");
    result = true;

    return result;
  </Source>
</Rule>
```

What I would like is a way to have the java be highlighted properly. This is simple to do in Sublime, but I've been searching for hours and can't find a way to do it in vscode.

Simplicity of sublime: everything between <*Source*> and <*/Source*> is highlighed in Java, while everything else is highlighted as XML
```
%YAML 1.2
---
# See http://www.sublimetext.com/docs/3/syntax.html

name: XMLJava
file_extensions:
 - xmlj
scope: text.xmlj

contexts:
  main:
    - match: ""
      push: "Packages/XML/XML.sublime-syntax"
      with_prototype:

        - match: '< *Source *>'
          push: Packages/Java/Java.sublime-syntax
          with_prototype:
            - match: '(?=</ *Source *>)'
              pop: true

```
