### ISSUE TITLE
[css] Support 8 (#RRGGBBAA) and 4 (#RGBA) value hex colors

### ISSUE THREAD

**Issue by yisibl** [Microsoft/vscode#7383]
- VSCode Version: 1.3.0-insider
- OS Version: OS X 10.11.4 (15E65)

``` css
.foo {
  color: #dd1c1cff;
}
```

Chrome, Firefox and Safari Nightly has supported.

Spec: https://drafts.csswg.org/css-color/#hex-notation
