### ISSUE TITLE
[Bug] Sass linter wrong errors for Sass each over a map

### ISSUE THREAD

**Issue by Luchillo** [Microsoft/vscode#7538]
- VSCode Version: 0.1.2
- OS Version: Mac OSX El Capitan

Steps to Reproduce:

1.  Paste this into a new file with Sass syntax:
```scss
@each $color, $hex in $colors {
  
  .color-#{$color} {
    color: $hex;
  }

  .border-#{$color} {
    border: 1px solid $hex;
    border-radius: 2px;

  }

  @each $side in ('top', 'left', 'right', 'bottom') {
    .border-#{$side}-#{$color} {
      border-#{$side}: 1px solid $hex;
      border-radius: 2px;
    }
  }

  .background-#{$color} {
    background: $hex;
  }
}
```
Current output: 
![image](https://cloud.githubusercontent.com/assets/9698639/15967782/9bf5681a-2eee-11e6-8e91-c61dfde297d3.png)

The errors of the linter:
![image](https://cloud.githubusercontent.com/assets/9698639/15967799/afd12bbc-2eee-11e6-8a7e-b2b945473984.png)
