### ISSUE TITLE
Settings GUI scrollbar has empty space to the right

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#75724]
Issue Type: <b>Bug</b>

1. Go Fullscreen
1. Open Settings GUI
1. Put your cursor at the scrollbar at the rightmost part of the screen
1. There is an empty space between scrollbar and the screen edge that doesn't respond to events such as clicking (all other editors / webview work fine)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

**Comment by usernamehw** [comment]
```css
.settings-editor>.settings-body .settings-tree-container {
    margin-right: 1px; /* <= */
    margin-top: 14px;
    border-spacing: 0;
    border-collapse: separate;
    position: relative;
}
```
