### ISSUE TITLE
Many repeated console log messages after small edit

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#76507]
This is pretty weird:

```scss
.foo {
    .foobar {
        .barfoo {
            outline-color: blue; cool
        }
    }
}


.fokzlb {}

.baaaa {
    counter-reset: unset;
}
```

1. Create `file.scss` with the contents above.
2. Go to end of line 6 and type `a`.

There will be 747 messages printed to the console:

![image](https://user-images.githubusercontent.com/22350/60576517-db771c80-9d7d-11e9-98fe-4278d4f005e1.png)

Is it an air travel ad?

![image](https://user-images.githubusercontent.com/22350/60576602-095c6100-9d7e-11e9-9059-1afabd424202.png)
