### ISSUE TITLE
Hide Error / Warning by using a Inline comment (// @ignore)

### ISSUE THREAD

**Issue by SamBrishes** [microsoft/vscode#76759]
Hellow,

[@code](https://twitter.com/code/status/1147197376328695809) on Twitter probably wanted me to contact you here about a feature [request].

It would be really awesome if **Visual Studio Code** would offer a special comment to hide an error / warning, which can be set on the end of the respective line. Something like `// @ignore` or anything else, WITHOUT to disable the Syntax / Error highlighting at all (on the complete file), of course. 

I'm asking because **VSCode** sometimes thinks to recognize an error, which isn't one. I documented a small example already on [microsoft/vscode-css-languageservice](https://github.com/microsoft/vscode-css-languageservice/issues/141#issuecomment-508669032), which shows the following Less code. This code references two properties within a Guard namespace to two variables. The first assignment gets shown with an error, the second one not. Both are valid, I swear!

```less
@color: light;

#scheme() when (@color = light){
    primary: #f0f0f0;
    secondary: #000000;
    /* [...] */
}
#scheme() when (@color = dark){
    primary: #121212;
    secondary: #FFFFFF;
    /* [...] */
}

@primary: #scheme[primary]; // <-- "scheme" gets an error with css-varvalueexpected!
@secondary: #scheme[secondary]; // <-- It's fine, doesn't get shown as error!

.my-color{
    color: @primary;
}
```

![less](https://user-images.githubusercontent.com/31392477/60751731-39dd0e80-9fbb-11e9-8ceb-272b30a8ef4b.PNG)

- **VSCode Version**: 1.36.0
- **OS Version**: Windows 10
- **Extensions**: CSS, Dart & Flutter, Emmet, Git, GitHub Pull Requests, Grunt, Gulp, HTML, Jake, JSON, LESS (even it is called Less), Markdown, Merge Conflict, Node debug, Npm (even it is called npm), PHP, Reference Search V ..., SCSS (Sass), Select line configur..., TypeScript

Sincerely,
Sam.
