### ISSUE TITLE
DevContainer follows symlinks in workspaceFolder

### ISSUE THREAD

**Issue by adinunzio84** [microsoft/vscode#77594]
- VSCode Version: 1.36.1
- OS Version: Windows 10 1709

Steps to Reproduce:

Folder structure (**myrepo** contains a subfolder that I wish to open in VS Code, called goproject, but I wish to open a symlink so its cwd is in `/go/src/`. It also contains the `.git` folder):
```
D:\DEV\myrepo
│   docker-compose.yaml
│
└───goproject
    └───.devcontainer
            devcontainer.json
            Dockerfile
```
`D:\DEV\myrepo\docker-compose.yaml`:
```yaml
version: '3'
services:
  goproject:
    build:
      context: .
      dockerfile: ./goproject/.devcontainer/Dockerfile
    volumes:
      - ../:/workspace

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
```

`D:\DEV\myrepo\goproject\.devcontainer\Dockerfile`: (mostly borrowed from: https://github.com/Microsoft/vscode-remote-try-go):

```
<snip> // contents from remote-try-go here

ENV GIT_DIR="/workspace/myrepo/.git"
RUN \
    mkdir -p /go/src/mydomain.com ; \
    ln -s /workspace/myrepo/goproject /go/src/mydomain.com/goproject

ENV \
    SHELL=/bin/bash
```
And the devcontainer.json file... Notice I set the `workspaceFolder` to the location of the symlink I created in the Dockerfile.

`D:\DEV\myrepo\goproject\.devcontainer\devcontainer.json`:
```json
{
	"name": "goproject",
	"dockerComposeFile": ["../../docker-compose.yaml"],
	"service": "goproject",
	"workspaceFolder": "/go/src/mydomain.com/goproject",
	"appPort": 9000,
	"extensions": [
		"ms-vscode.go"
	],
	"settings": {
		"go.gopath": "/go",
		"go.inferGopath": true,
		"go.useLanguageServer": true,
		// "search.followSymlinks": false, // tried this only half-expecting it to work in this case
	}
}
```

From issues like microsoft/vscode#18837 and microsoft/vscode#74104, it seems like **not** following symlinks is now the desired default behavior for VS Code, except for searches, and it's the behavior I'm looking for. Since it follows symlinks, I am unable to set my VSCode workspaceFolder to the symlink (a folder in the GOPATH) - it opens the subdirectory of my workspace instead.

Does this issue occur when all extensions are disabled?: Yes/No
I don't think I can run devcontainers with extensions disabled.
