### ISSUE TITLE
Italic markup style color should not be applied in markdown

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7785]
![image](https://cloud.githubusercontent.com/assets/2193314/16129269/0bb73c5e-33b9-11e6-8c94-6d3c6c18195d.png)

The style overriding link styling is:

```css
.monaco-editor.vs-dark.vscode-theme-defaults-themes-dark_plus-json .token.markup.italic {
    font-style: italic;
    color: rgba(86, 156, 214, 1);
}
```
