### ISSUE TITLE
Task: allow inputs in inputs and commands for pickString

### ISSUE THREAD

**Issue by tdegrunt** [microsoft/vscode#81370]
This may be two features in one, but this could greatly improve tasks without having to write an extension. 

The first is allowing inputs in inputs:
```yaml
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "kill: process",
            "type": "shell",
            "command": "kill",
            "args": [
                "-9",
                "${input:pid}",
            ],
            "problemMatcher": []
        }
    ],
    "inputs": [
        {
            "id": "pid",
            "type": "pickString",
            "description": "pid to kill",
            "command": "pgrep",
            "args": [
                "${input:procesName}"
            ]
        },
        {
            "id": "procesName",
            "type": "promptString",
            "description": "process name",
            "default": "code"
        }
    ]
}
```

The second is allowing commands to run under pickString, used in the above example as well.
Say I want to ping one of my interface ip's, I would want to pick the IP address from a list, filled by a command:

```yaml
"command": "ifconfig | awk '/inet/ {gsub(\"addr:\", \"\", $2); print $2}'"
```

Perhaps this is already possible by running a VSCode command using the command type input, but I might be unaware.
