### ISSUE TITLE
Clean our monospace font stack

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#81692]
Currently it sit at:

```css
.mac { --monaco-monospace-font: "SF Mono", Monaco, Menlo, Inconsolata, "Courier New", monospace; }
.windows { --monaco-monospace-font: Consolas, Inconsolata, "Courier New", monospace; }
.linux { --monaco-monospace-font: "Droid Sans Mono", Inconsolata, "Courier New", monospace, "Droid Sans Fallback"; }
```

@bpasero Do you know where these choices come from? `Inconsolata` is rather narrow and not good for UI display. `Droid Sans Mono` isn't available on Fedora, for example, and it causes UI to fallback to use a serif font `Liberation Serif`.

IMO it should be:

```css
.mac { --monaco-monospace-font: "SF Mono", Monaco, Menlo, Courier, monospace; }
.windows { --monaco-monospace-font: Consolas, "Courier New", monospace; }
.linux { --monaco-monospace-font: "Ubuntu Mono", "Liberation Mono", "DejaVu Sans Mono", monospace; }
```

Justifications:

- `font-family: monospace` fallback chosen by Chrome:
  - Win: `Courier New`
  - macOS: `Courier`
  - Ubuntu / Fedora: `Liberation Mono`
- Ubuntu Mono is bundled in Ubuntu
- DejaVu Sans Mono is [bundled](https://en.wikipedia.org/wiki/DejaVu_fonts) in all major distros:

    > DejaVu fonts can be obtained from the DejaVu project on GitHub. Some operating systems (OpenBSD, Solaris, Haiku, AmigaOS 4, GNU/Linux distributions such as Ubuntu, Debian, Fedora, and RHEL) include DejaVu fonts in their default installation,[3][4][5][6][7] sometimes even using them as their system fonts.

- Inconsolata looks like this:

  ![image](https://user-images.githubusercontent.com/4033249/65921116-2cef7180-e396-11e9-8b56-91d78ddcefca.png)
  
  Normally

  ![image](https://user-images.githubusercontent.com/4033249/65921112-2b25ae00-e396-11e9-8bdc-bd27c2f4c3d0.png)
