### ISSUE TITLE
Setting to hide paths for open editors in explorer

### ISSUE THREAD

**Issue by Wolfenberg** [microsoft/vscode#81899]
I would like an option to hide those file paths of open editors in explorer to keep the list cleaner and more focused on the names of the files.
![image](https://user-images.githubusercontent.com/477746/66126746-70dab480-e5ea-11e9-8c75-f7ab1e86b676.png)

**Comment by isidorn** [comment]
This is a fair feature request, however it is not currently on our plan, thus assigning to the backlog.

**Comment by karthik-k-r** [comment]
@Wolfenberg Just found a work around! Couple of extensions to be installed. These extensions inject the custom css to the editor. Also even changed the font too! To customize anything related, just Inspect the VS Code by **Help > Toggle Developer Tools** and update the **settings.json** accordingly.
Hope this helps!

FYI.. @Tyriar @isidorn

[https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui](url)
[https://marketplace.visualstudio.com/items?itemName=iocave.monkey-patch](url)

![image](https://user-images.githubusercontent.com/65346620/121773995-3a19b780-cb9d-11eb-9a24-7798a4830fd9.png)
![image](https://user-images.githubusercontent.com/65346620/121774231-13f51700-cb9f-11eb-918c-f01dcd941147.png)

**Comment by xjArea** [comment]
At this folder `yourPath\VSCode\resources\app\out\vs\workbench\`, 
Open this file `workbench.desktop.main.css`，add this css code :
```css
.vs .monaco-icon-label>.monaco-icon-label-container>
.monaco-icon-description-container>.label-description{opacity:0;}
.vs .monaco-icon-label>.monaco-icon-label-container:hover >
.monaco-icon-description-container>.label-description{opacity:0.75;}
```
Restart VSCode, Then the path will hidden，but hover still show out, 
VSCode will tell you something is wrong, but who care, 
click the gear icon set don't alert out again !
