### ISSUE TITLE
Line-height in list modals is incorrect when using custom color theme

### ISSUE THREAD

**Issue by Duncank** [microsoft/vscode#82685]
Multiline texts in overlay-lists are displayed close to each other. It happens with the custom Monokai Mega theme, but not with Material Theme or any of the default themes. The Monokai Mega theme however only consists of json-code, no changes to the css, so the creator thinks this has to do something with VSCode itself.

![image](https://user-images.githubusercontent.com/719365/66916573-c6b45100-f01b-11e9-8375-77d74976b49c.png)
Using the Monokai Mega theme

If I change this in the developer tools, everything is displayed properly:
```css
.quick-input-list .monaco-list .quick-input-list-entry {
    padding: 0 5px;
    height: 18px;
    align-items: center;
}
```
to:
```
   min-height: 18px
```

- VSCode Version: 1.39.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install Monokai Mega color theme and apply it.
2. Execute an action in Gitlens (pull, push, apply stash, etc). All of these actions use a multi-lined overlay.

Does this issue occur when all extensions are disabled?: No, since it has to do with a custom theme.
