### ISSUE TITLE
Emmet: saving a file outside the current directory in the case of using Encode/Decode command

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#8569]
Help to testing #8207 

**VSCode Version**: 1.3.0-insiders (a21c12346f388e51858c930875ca30968604c116)
**OS Version**: Windows 10 Pro (build 10586.420)

**Steps to Reproduce:**
1. Open any directory and create a CSS file:
   
   ``` css
   .test { background-image: url(https://avatars1.githubusercontent.com/u/7034281?v=3&s=460) }
   ```
2. Run `Emmet: Encode\Decode`.
3. Run `Emmet: Encode\Decode` and write `../test.png`.
4. The file will be saved.

**Questions:**
1. This is correct behavior?
2. Prevent saving a file outside the current workspace? For example: `"The path **{0}** is located outside the current workspace."`
3. Provide choice to the user?

**P.S.:** This is the last problem that i could find.
