### ISSUE TITLE
Support for SVG 2 CSS Properties

### ISSUE THREAD

**Issue by boyum** [microsoft/vscode#85828]
SVG 2 introduces the possibility of setting SVG properties in CSS. This means this example should be valid:

```css
circle {
  r: 2;
  x: 10;
  y: 100;
}

path {
  d: 'L0 100';
}
```

However, these properties trigger the `[s]?css(unknownProperties)` warning: 
![image](https://user-images.githubusercontent.com/9085189/69872287-4ab55600-12b5-11ea-9865-9c6d9dfeb1ab.png).

I'm not too familiar with VS Code's insides and what program checks for valid properties. If this belongs somewhere else, I'd be happy to re-issue there. 

Thanks! ✨
