### ISSUE TITLE
Go to definition across modules in SCSS does not work

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#86085]
Testing #85979

* Create a file `provider.scss`:
```scss
@mixin gradient-striped($color: rgba(255, 255, 255, .15), $angle: 45deg) {
  background-image: -webkit-linear-gradient($angle, $color 25%, transparent 25%, transparent 50%, $color 50%, $color 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient($angle, $color 25%, transparent 25%, transparent 50%, $color 50%, $color 75%, transparent 75%, transparent);
  background-image: linear-gradient($angle, $color 25%, transparent 25%, transparent 50%, $color 50%, $color 75%, transparent 75%, transparent);
}

.test1 {
  @include gradient-striped;
  background-size: 40px 40px;
}
```

* Create a file `consumer.scss`:
```scss
@use "provider" as p;

.test2 {
  @include p.gradient-striped;
  background-size: 40px 40px;
}
```

In file `provider.scss` executing jump to definition on `gradient-striped` will correctly jump to the mixin declaration location. But when trying the same in file `consumer.scss`, nothing happens.
