### ISSUE TITLE
[remote] Support `code --install-extension` on the remote

### ISSUE THREAD

**Issue by bradwilson** [microsoft/vscode#86232]
I am running WSL 2 (from the 20H1 Slow Ring, build 19033), and I have VS Code installed on the Windows side. I have noticed that adding `Remote - WSL` breaks some of the WSL-to-Windows communication paths, namely the ability to invoke `code --install-extension` from WSL and have it install the extension in Code for Windows.

Note that this functionality works fine without "Remote - WSL" installed; it's only the installation of the remote extension inside of VS Code that breaks the communication.

**Without WSL - Remote**: `code --install-extension` from WSL correctly installs the extension on the Windows side of VS Code (without any UI popup)

**With WSL - Remote**: `code --install-extension` incorrectly pops up the VS Code UI (does not open any folder, just pops up the UI) and the extension is not installed.

**Comment by bradwilson** [comment]
The fact that `code --install-extension` works just fine to install extensions to the Windows side before your extension is installed, means to me that `code --install-extension` should continue to install extensions to the Windows side even after your extension is added, for consistency purposes (it doesn't make sense that adding your extension would change the behavior).

Adding an additional flag to `code --install-extension` when "Remote - WSL" is installed to install Linux-side extensions would also be a nice to have feature, but that's not actually what I'm asking for. I just want you to un-break this behavior that my Ansible playbooks depend on. 😄

**Comment by aeschli** [comment]
@bradwilson To install extensions on Windows 'the old way', you need to call the WIndows code command (code.cmd), not code.sh.

I first thought you wanted the WSL code command to install extensions in WSL. That is possible when in the remote integrated terminal: https://github.com/microsoft/vscode-remote-release/issues/2589

**Comment by bradwilson** [comment]
@aeschli You misread my issue and then closed it based on your misunderstanding.

**Comment by aeschli** [comment]
@bradwilson Yes, I'm a bit confused. Can you clarify what your request is?

- running `code --install-extension` in a Windows command prompt (running `code.cmd`) will install extensions in the Windows side. I tested that this works regardless if the `Remote WSL` extension is installed or not.
- running `code --install-extension` in a WSL shell (running `code.sh`)  will
   - without `Remote WSL` extension installed install extensions in the Windows side.
   - with `Remote WSL` extension not do anything. If it were to do something it should install an extension on the WSL side.
   
My suggestion was that installing an extension on the Windows side was what you want, run `code.cmd`.

**Comment by bradwilson** [comment]
It's quite simple:

- Before installing "WSL - Remote", I'm able to install extensions via the `code` command in WSL.
- After installing "WSL - Remote", I'm unable to install extensions via the `code` command in WSL.

Something in this extension breaks the way `code` works such that I can no longer install extensions.

Your proposed workaround is "don't do that", except that's sort of irrelevant. You've broken something that works, and just because you didn't break _something else_ (running `code` from Windows) isn't the point.

-----

If what you're really asking is "why do you want to run `code` from WSL?", the answer is: I automate the standing up of my Linux-based development environment with [Ansible scripts](https://github.com/bradwilson/ansible-dev-pc). Obviously these work fine on native Linux; they also work fine within WSL, _**right up to the moment where "WSL - Remote" is installed**_ at which point my automation is now broken.

Here's an [example of one such script](https://github.com/bradwilson/ansible-dev-pc/blob/91270cdad3cb0440f6e2996519a99402bfc9a0ad/dotnet/vscode.yaml):

```yaml
- name: .NET Core (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install VS Code Extensions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - formulahendry.dotnet-test-explorer    # .NET Core Test Explorer
        - k--kato.docomment                     # C# XML Documentation Comments
        - ms-dotnettools.csharp                 # C#
```

The end result is that once the Ansible script installs "Remote - WSL" (by way of installing `ms-vscode-remote.vscode-remote-extensionpack`), then Ansible is immediately no longer able to install any new extensions into VSCode. (There's a small amount of unintended irony that I install "WSL - Remote" with the feature which you then immediately break. 😂)

If you choose not to fix this, then that's your decision, but your suggested workaround is wholly unacceptable to my usage. I also don't think you should have the right to decide to arbitrarily break a built-in feature which was already working, but that's my personal interpretation.

**Comment by phealy** [comment]
In this particular case the problem is that code.cmd (the Windows command shell script) handles the functionality to install extensions. That functionality is still there and usable, even with Remote-WSL installed. However, once Remote-WSL is added, `code` from the Linux shell now gets `code.sh` instead of `code.cmd`, and `code.sh` doesn't have that functionality, because it's for launching via the Remote-WSL server instead of the Windows side.

Explicitly calling `code.cmd`, as was mentioned earlier, still works and is probably the workaround you need. However, you have to call it via cmd.exe, because otherwise bash tries to parse it as a shell script.

```shell
$ /mnt/c/Windows/System32/cmd.exe /C "C:\Program Files\Microsoft VS Code\bin\code.cmd" --install-extension ms-vscode.vscode-node-azure-pack
Installing extensions...
```

You could key off one of the environment variables WSL sets by default to have an ansible playbook that will work in either location:
```yaml
- name: .NET Core (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - include_tasks: set_vscode_facts.yml

    - name: Install VS Code Extensions
      command: "{{ vscode_command }} --install-extension {{ item }}"
      args:
        creates: "{{ vscode_extensions }}/{{ item }}-*/package.json"
      loop:
        - formulahendry.dotnet-test-explorer    # .NET Core Test Explorer
        - k--kato.docomment                     # C# XML Documentation Comments
        - ms-dotnettools.csharp                 # C#
```

`set_vscode_facts.yml`:
```yaml
- name: Set VS Code facts (Linux)
  set_fact:
    vscode_command: code
    vscode_extensions: ~/.vscode/extensions
  when: "'WSL_INTEROP' not in ansible_env"

- name: Set VS Code facts (WSL)
  set_fact:
    vscode_command: '/mnt/c/Windows/System32/cmd.exe /C "C:\Program Files\Microsoft VS Code\bin\code.cmd"'
    vscode_extensions: /mnt/c/Users/$USER/.vscode/extensions
  when: "'WSL_INTEROP' in ansible_env"
```
