### ISSUE TITLE
suggest widget misplaced

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#86243]
Version: 1.41.0-insider (user setup)
Commit: 43e3581aa635406ada2d8138d7ee242ddabefc1c
Date: 2019-12-04T05:29:38.104Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

Also on Ubuntu 18.04

Create
```scss
@use "../";
.element {
    background-color: bootstrap.$body-bg;
    @include bootstrap.float-left;
}
```

- code completion in`use`. Suggestvwidget is off.
![image](https://user-images.githubusercontent.com/6461412/70131089-ff6ac100-1681-11ea-83fe-91e3f137c535.png)
