### ISSUE TITLE
Several CJK strings on the UI are very difficult to read on standard definition monitors due to font weight and size

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8653]
- VSCode Version: Code - Insiders 1.3.0-insider (a2b9738a942237b59cb920940b93a0206f1b61d0, 2016-07-01T19:24:33.352Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

`--locale=zh-CN` bold in debug panel headings:

![image](https://cloud.githubusercontent.com/assets/2193314/16535731/9eb01c4c-3f9e-11e6-8202-f78fea6e3a6b.png)
![image](https://cloud.githubusercontent.com/assets/2193314/16535735/ab2fb5ea-3f9e-11e6-9a6e-15b8534fb10d.png)

`--locale=ko` output panel title (it is 출 but it's awfully close to 춤 and 춥):

![image](https://cloud.githubusercontent.com/assets/2193314/16535754/d34acd6c-3f9e-11e6-898e-3fe15139ff9b.png)

/cc @dbaeumer @bpasero @rebornix

**Comment by bpasero** [comment]
If this can be fixed by tweaking our CSS with some rules for CJK, we are good. Otherwise the bigger story is to support setting font from a setting. Moving to Brad first to see if we can fix this with some CJK CSS rules in the same way we do it here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/media/shell.css#L20

**Comment by Tyriar** [comment]
How about something like this?

```css
:root {
  --title-scale: 1em;
}
.monaco-shell:lang(zh-Hans),
.monaco-shell:lang(zh-Hant),
.monaco-shell:lang(ja),
.monaco-shell:lang(ko) {
  --title-scale: 1.2em;
}
.tiny-titles {
  font-size: var(--title-scale);
}
```
