### ISSUE TITLE
css-lcurlyexpected error with nested media querie, supports

### ISSUE THREAD

**Issue by obendev** [microsoft/vscode#86903]
- VSCode Version: 1.41.0
- OS Version: Windows_NT x64 10.0.18363

I noticed that I'm getting an `scss(css-lcurlyexpected)`-error when doing this:

```css
@supports (display: grid) {
    @media screen and (max-width: 400px) {
        column-gap: 0.5rem;
    }
}
```

It does work without an error outside `@supports` though.

The error:
```
{
	"resource": "resource",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "css-lcurlyexpected",
	"severity": 8,
	"message": "{ expected",
	"source": "scss",
	"startLineNumber": 29,
	"startColumn": 27,
	"endLineNumber": 29,
	"endColumn": 28
}
```

**Comment by aeschli** [comment]
The snippet is not valid scss, it lacks a rule. Should it be
```scss
.foo {
    @supports (display: grid) {
        @media screen and (max-width: 400px) {
            column-gap: 0.5rem;
        }
    }
}
```

That's a dup of https://github.com/microsoft/vscode-css-languageservice/issues/152 which I just fixed
