### ISSUE TITLE
The mode has failed while tokenizing the input.

### ISSUE THREAD

**Issue by SachinMaharana** [Microsoft/vscode#8950]
- VSCode Version: 1.3
- OS Version: Linux Mint 17

Steps to Reproduce:

1. Restarting the code gives the error mentioned in title.
2.

**Comment by tryangul** [comment]
same here: 
* vs code 1.3
* ubuntu 14.04

**Comment by SachinMaharana** [comment]
@tryangulI had it solved by removing and reinstalling. might work out for you.
sudo apt-get remove --purge code
Also, remove /usr/share/code and ~/.vscode
Reinstall again. It worked.

**Comment by Tyriar** [comment]
Did you upgrade from something other than v1.2.0? See #8876

Possible work around:

```bash
sudo rm -rf /usr/share/code/resources/app/node_modules/vscode-textmate/node_modules
```

**Comment by elvarb** [comment]
Having the same problem on Windows here, trying reinstall

**Comment by Tyriar** [comment]
@elvarb can you create another issue with more details on this?

**Comment by Zolomon** [comment]
I had the same issue:
From about:
```
Version 1.3.0
Commit e724f269ded347b49fcf1657fc576399354e6703
Date 2016-07-07T16:50:12.291Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```

Running `sudo rm -rf /usr/share/code/resources/app/node_modules/vscode-textmate/node_modules` worked.

**Comment by TylerCode** [comment]
Same here, persisted through an update. 

Version 1.5.3 currently and Ubuntu 16.04 LTS

Using the command posted by Zolomon fixed the issue.

`sudo rm -rf /usr/share/code/resources/app/node_modules/vscode-textmate/node_modules`

**Comment by oxitech239** [comment]
Using Gentoo/Sabayon, same issue but 

/usr/share/code/resources/app/node_modules/vscode-textmate/node_modules

 does not exist.

**Comment by oxitech239** [comment]
Version 16.7.3
Commit e698221ac971850e0a3766dc5bafda21e7ee796d
Date 2016-08-03T19:24:49.649Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

**Comment by Tyriar** [comment]
Going to close this off as you should only need to run the workaround once after upgrading from a pre-1.3 version:

```
sudo rm -rf /usr/share/code/resources/app/node_modules/vscode-textmate/node_modules
```

**Comment by oxitech239** [comment]
Tylar,  i don't know where you got the perception from this resolves anything ?!

**Comment by pwwang** [comment]
I was trying the compile VSCode with [conda](https://anaconda.org/). This problem appeared, and couldn't be fixed by the the solutions.

Here is the process:
`meta.yaml`:
```yaml
package:
    name: vscode
    version: 1.9.1
source:
    fn: vscode.rpm
    url: https://go.microsoft.com/fwlink/?LinkID=760867
build:
    number: '0'
requirements:
    build:
    run:
test:
    commands:
        - code
about:
    home: https://code.visualstudio.com/
    summary: Visual Studio Code is a lightweight but powerful source code editor which runs on your desktop and is available for Windows, macOS and Linux.
```

`build.sh`:
```bash
#!/usr/bin/env bash

rpm2cpio vscode.rpm | cpio -idv
mv usr $PREFIX
ln -s $PREFIX/usr/share/code/code $PREFIX/bin/code
libffmpegso=$PREFIX/lib/libffmpeg.so
libnodeso=$PREFIX/lib/libnode.so

if [ ! -d $PREFIX/lib ]; then
    mkdir $PREFIX/lib
fi

if [ ! -e $libffmpegso ]; then
    cp $PREFIX/usr/share/code/libffmpeg.so $libffmpegso
fi

if [ ! -e $libnodeso ]; then
    cp $PREFIX/usr/share/code/libnode.so $libnodeso
fi
```

Then VSCode was running normally after installed it: `conda install vscode --use-local`. However when I tried to open any file, this message `The mode has failed while tokenizing the input.` appeared, and the syntax wasn't highlighted. 

I checked the folder `$PREFIX/usr/share/code/resources/app/node_modules/vscode-textmate/node_modules`, it didn't exist. I also tried to make an empty one, which still didn't work.

Anybody has any ideas?

Platform:
CentOS release 6.8 (Final)
VSCode: 1.9.1

Thanks.
