### ISSUE TITLE
CSS color preview gets hidden or moves when moving a line around it using shortcuts

### ISSUE THREAD

**Issue by greengiraffe** [Microsoft/vscode#9207]
- VSCode Version: 1.3.1
- OS Version: OS X 10.11.3

**Steps to Reproduce:**
1. Open a CSS file that has a color declaration (e.g. `border: 1px solid red`) in it. A color preview should be visible.
2. Set your cursor to a (non-empty) line above or below the color declaration.
3. Move the line up or down by using the `alt` + `arrow-up/arrow-down` shortcut so that it switches the line with the line from step 1.

**Observations:**
- When moving a line from the bottom _above_ the line with the color preview, the preview square sticks to the left of the moving line.
-  When moving a line from the top _below_ the line with the color preview, the preview square becomes invisible.
- In both cases, the preview resets itself to its original location after a short time.
- The issue persists when starting VSC with `--disable-extensions`.

**Test code snippet:**

``` css
.test {
  display: block;
  border: 1px solid red;
  width: 100px;
  height: 100px;
  background-color: green;
  position: relative;
}
```

**Screencast:**

![vsc-bug-report](https://cloud.githubusercontent.com/assets/9062294/16803541/3f945882-4907-11e6-827f-454ab13ab630.gif)
