### ISSUE TITLE
A Font issue

### ISSUE THREAD

**Issue by Photonico** [microsoft/vscode#92245]
Hello,

In VSCode, I have set "FiraComp" is my monospace font in editor space.
However, the monospace font in dialog is also "Hack".
![font](https://discuss.getsol.us/assets/files/2020-03-09/1583715385-223933-20200309a.png)
I wish that it is allowed to set the dialog font.

Sincerely,

**Comment by octref** [comment]
Hey @Photonico, can you try change the setting `editor.fontFamily`? We don't necessarily read system font setting.

**Comment by Photonico** [comment]
> editor.fontFamily
Hello,

I have changed the `editor.fontFamily` as `Fira Comp`, but the dialog monospace font is still the system default font.

**Comment by octref** [comment]
The system font we are using on Linux is below now:

```css
linux { --monaco-monospace-font: "Ubuntu Mono", "Liberation Mono", "DejaVu Sans Mono", monospace; }
```

Previously it was

```css
.linux { --monaco-monospace-font: "Droid Sans Mono", Inconsolata, "Courier New", monospace, "Droid Sans Fallback"; }
```

I guess on your computer, `monospace` falls back to Hack to your configuration.

You can verify that by opening a HTML file in Chrome:

```html
<div style="font-family: monospace">text</div>
```

Your request is tracked in #519.
