### ISSUE TITLE
Beautifier wrap inline comments near css rules

### ISSUE THREAD

**Issue by Unknow-max** [microsoft/vscode#93007]
- VSCode Version: Version: 1.43.0 (user setup)

- OS Version: Windows 10 Home 6/03/2020

## Input
The code looked like this before beautification:

```css
.hero-about {
  background: linear-gradient(rgba(0, 0, 0, .4),
      rgba(0, 0, 0, .6)), url("../../images/backgrounds/team.png") center/cover; /* 1 */
  height: .1rem; /* 2 */
  min-height: 100vh;
}
```

## Expected Output
The code should have looked like this after beautification (same):

```css
.hero-about {
  background: linear-gradient(rgba(0, 0, 0, .4),
      rgba(0, 0, 0, .6)), url("../../images/backgrounds/team.png") center/cover; /* 1 */
  height: .1rem; /* 2 */
  min-height: 100vh;
}
```

## Actual Output
The  code actually looked like this after beautification, you can note that beautify wrap the inline comments, and obviously I don't want this ugly behavior.

```css
.hero-about {
  background: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.6)), url("../../images/backgrounds/team.png") center/cover;
  /* 1 */
  height: .1rem;
  /* 2 */
  min-height: 100vh;
}
```
---

## Steps to Reproduce
Simply copy the css code, and try to run beautifier.

## Environment
OS: Windows 10 Home 6/03/2020 18363.720

---
