### ISSUE TITLE
Vs code take the first property in css as rendered value not considering if there is a duplicate style definition

### ISSUE THREAD

**Issue by Unknow-max** [microsoft/vscode#94777]
**Hi everyone**
I notice a bug when there is a multiple style definition (property repeated two or more times) in a css selector, see more there:

![immagine](https://user-images.githubusercontent.com/59534318/78891461-e5921e00-7a67-11ea-84d2-b9e865548ad5.png)

As you can see vscode tell me with a warning that there is a duplicate style definition (`display:block, display: inline-block`). Perfectly fine.
But the third warning is a little bit more interesting, see below:

![immagine](https://user-images.githubusercontent.com/59534318/78891576-21c57e80-7a68-11ea-9804-bf8305032ea9.png)

The rendered display, in the browser is `display: inline-block`, compatible with vertical align middle, but the text editor tell me that the rendered display is `block`, not compatibile with vertical align middle. It take the first `display` property as a rendered value.

### Vs code Version:
Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create simply a css file
2. Paste this code snippet:
```css
.myMagicClass {
  content: "";
  display: block;
  width: 0;
  height: 0.15rem;
  background-color: #3557f0;
  margin-right: .8rem;
  display: inline-block;
  vertical-align: 18%;
  transition: width .3s .5s;
}
```
3. Read the warnings

Does this issue occur when all extensions are disabled?: Yes, no difference
