### ISSUE TITLE
OSX 10.15 WindowServer high cpu load showing ProgressBar

### ISSUE THREAD

**Issue by fnicastri** [microsoft/vscode#97900]
Really high CPU load of the WindowServer process on OSX during the use of the dart-code extension.
I have tracked it down to the displayed progress bar.
When a notification with the progress bar is shown WindowServer CPU usage go between 50% and 80%.
Stopping the task it drop to the usual sub 10% value.

I could see a similar behaviour with other extensions.

Possible duclicate of https://github.com/microsoft/vscode/issues/83991.
But that issue is closed and the problem is still present.

- VSCode Version: 1.46.0-insider
- OS Version: MacOS X 10.15.4

Steps to Reproduce:

1. Launch a command that show a ProgressBar
2. look at cpu usage of WindowServer
3. stop the task

**Comment by bpasero** [comment]
This seems very similar to https://github.com/microsoft/vscode/pull/96096 (@evangrayk @joaomoreno fyi) and I wonder if using the `steps` trick helps here too. 

@fnicastri since this is very likely browser reproducible, can you try to:
* open https://jsfiddle.net/
* paste the code [1] for HTML and [2] for CSS
* run it
* monitor the CPU usage

[1] HTML

```html
<div class="monaco-progress-container infinite">
  <div class="progress-bit">
  
  </div>
</div>
```

[2] CSS

```css
.monaco-progress-container {
	width: 100%;
	height: 5px;
	overflow: hidden; /* keep progress bit in bounds */
  background-color: red;
}

.monaco-progress-container .progress-bit {
	width: 2%;
	height: 5px;
	position: absolute;
	left: 0;
}

.monaco-progress-container.infinite .progress-bit {
	animation-name: progress;
	animation-duration: 4s;
	animation-iteration-count: infinite;
	animation-timing-function: linear;
	transform: translate3d(0px, 0px, 0px);
  background-color: blue;
}

/**
 * The progress bit has a width: 2% (1/50) of the parent container. The animation moves it from 0% to 100% of
 * that container. Since translateX is relative to the progress bit size, we have to multiple it with
 * its relative size to the parent container:
 *  50%: 50 * 50 = 2500%
 * 100%: 50 * 100 - 50 (do not overflow): 4950%
 */
@keyframes progress { from { transform: translateX(0%) scaleX(1) } 50% { transform: translateX(2500%) scaleX(3) } to { transform: translateX(4950%) scaleX(1) } }
```
