### ISSUE TITLE
YAML Syntax highlignting doesnt include multiline scalars anymore

### ISSUE THREAD

**Issue by MaxRink** [microsoft/vscode#99025]
- VSCode Version: 1.45.1
- OS Version: Win10x86

Steps to Reproduce:
In previous versions vscode linted yaml in  multiline scalars, now it doesnt anymore:
This happens without ANY plugins installed.

1.45.1
![image](https://user-images.githubusercontent.com/4894735/83263623-32b88380-a1bf-11ea-964a-5ce9c9e1d7d6.png)

1.39.1
![image](https://user-images.githubusercontent.com/4894735/83263568-1f0d1d00-a1bf-11ea-805b-b7fdd6f46a76.png)

It also happens with the insider build (e.g. 1.46)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Can you please provide a copy/paste-able example?

**Comment by MaxRink** [comment]
sure
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-customer-configmap
  namespace: ingress-system
data:
  values.yaml: |
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: "10.27.50.35/32"
      loadBalancerIP: "10.27.50.35"
```
